import type {
  PlaygroundCategoryId,
  PlaygroundEntry,
  PlaygroundScenarioId,
} from './types';

const scenario = (...ids: PlaygroundScenarioId[]) => ids.map((id) => ({ id }));

const common = (id: string, name: string, scenarios: PlaygroundScenarioId[] = ['default']): PlaygroundEntry => ({
  id,
  name,
  category: 'foundation',
  sourcePath: `components/common/${name}.tsx`,
  scenarios: scenario(...scenarios),
});

const entry = (
  category: PlaygroundCategoryId,
  id: string,
  name: string,
  sourcePath: string,
  scenarios: PlaygroundScenarioId[] = ['default'],
  canvas: PlaygroundEntry['canvas'] = 'padded',
): PlaygroundEntry => ({ id, name, category, sourcePath, scenarios: scenario(...scenarios), canvas });

export const PLAYGROUND_CATEGORIES: readonly PlaygroundCategoryId[] = [
  'foundation',
  'layout',
  'dashboard',
  'alerts',
  'history',
  'signals',
  'reports',
  'runFlow',
  'settings',
  'stockSearch',
  'tasks',
  'watchlist',
];

export const PLAYGROUND_CATALOG: readonly PlaygroundEntry[] = [
  common('button', 'Button', ['variants', 'sizes', 'states']),
  common('pressable', 'Pressable', ['interactive', 'states']),
  common('selection-chip', 'SelectionChip', ['interactive', 'states']),
  common('icon-button', 'IconButton', ['variants', 'sizes', 'states']),
  common('spinner', 'Spinner', ['sizes', 'states']),
  common('progress', 'Progress', ['variants', 'loading']),
  common('file-input', 'FileInput', ['interactive', 'states']),
  common('field', 'Field', ['states']),
  common('textarea', 'Textarea', ['states']),
  common('segmented-control', 'SegmentedControl', ['interactive', 'states']),
  common('search-input', 'SearchInput', ['interactive', 'states']),
  common('notification-panel', 'NotificationPanel', ['default', 'empty']),
  common('surface', 'Surface', ['variants', 'interactive']),
  common('section', 'Section'),
  common('state-panel', 'StatePanel', ['variants']),
  common('alert', 'Alert', ['variants', 'interactive']),
  common('card', 'Card', ['variants']),
  common('checkbox', 'Checkbox', ['interactive', 'states']),
  common('app-page', 'AppPage'),
  common('workspace-page', 'WorkspacePage'),
  entry('foundation', 'workspace-layout', 'WorkspaceLayout', 'components/common/WorkspacePage.tsx'),
  common('responsive-filter-panel', 'ResponsiveFilterPanel', ['interactive', 'states']),
  common('responsive-rail', 'ResponsiveRail', ['interactive']),
  common('workspace-navigation', 'WorkspaceNavigation', ['interactive']),
  common('tabs', 'Tabs', ['interactive', 'states']),
  entry('foundation', 'tab-panel', 'TabPanel', 'components/common/Tabs.tsx'),
  common('summary-strip', 'SummaryStrip', ['variants']),
  common('section-card', 'SectionCard'),
  common('stat-card', 'StatCard', ['variants']),
  common('empty-state', 'EmptyState', ['default', 'states']),
  common('inline-alert', 'InlineAlert', ['variants']),
  common('sticky-action-bar', 'StickyActionBar'),
  common('toolbar', 'Toolbar'),
  common('filter-bar', 'FilterBar', ['interactive', 'states']),
  common('applied-filter-chips', 'AppliedFilterChips', ['interactive', 'empty']),
  entry('foundation', 'filter-chip', 'FilterChip', 'components/common/AppliedFilterChips.tsx', ['interactive', 'states']),
  common('advanced-filter-sheet', 'AdvancedFilterSheet', ['interactive', 'states']),
  common('data-table', 'DataTable', ['interactive', 'loading', 'empty', 'error']),
  common('toast-viewport', 'ToastViewport'),
  common('toast-provider', 'ToastProvider', ['interactive']),
  common('page-header', 'PageHeader'),
  common('input', 'Input', ['states', 'sizes']),
  common('credential-input', 'CredentialInput', ['interactive', 'states']),
  common('date-picker', 'DatePicker', ['interactive', 'states']),
  entry('foundation', 'date-range-picker', 'DateRangePicker', 'components/common/DatePicker.tsx', ['interactive', 'states']),
  common('time-picker', 'TimePicker', ['interactive', 'states']),
  common('eye-toggle-icon', 'EyeToggleIcon', ['states']),
  common('loading', 'Loading'),
  common('drawer', 'Drawer', ['interactive']),
  common('sheet', 'Sheet', ['interactive']),
  entry('foundation', 'filter-sheet', 'FilterSheet', 'components/common/Sheet.tsx', ['interactive', 'states']),
  common('scroll-area', 'ScrollArea'),
  common('api-error-alert', 'ApiErrorAlert', ['default', 'error']),
  common('collapsible', 'Collapsible', ['interactive']),
  common('score-gauge', 'ScoreGauge', ['variants', 'interactive']),
  common('json-viewer', 'JsonViewer', ['default', 'empty']),
  common('select', 'Select', ['interactive', 'states']),
  common('searchable-select', 'SearchableSelect', ['interactive', 'states']),
  common('switch', 'Switch', ['interactive', 'states']),
  common('badge', 'Badge', ['variants']),
  common('status-dot', 'StatusDot', ['variants']),
  common('tooltip', 'Tooltip', ['interactive']),
  common('popover', 'Popover', ['interactive']),
  common('pagination', 'Pagination', ['interactive']),
  common('confirm-dialog', 'ConfirmDialog', ['interactive', 'error']),
  common('modal', 'Modal', ['interactive']),

  entry('layout', 'shell', 'Shell', 'components/layout/Shell.tsx', ['default'], 'full'),
  entry('layout', 'command-palette', 'CommandPalette', 'components/command-palette/CommandPalette.tsx', ['interactive']),
  entry('layout', 'notification-bell', 'NotificationBell', 'components/notifications/NotificationBell.tsx', ['interactive', 'empty', 'error']),
  entry('layout', 'sidebar-nav', 'SidebarNav', 'components/layout/SidebarNav.tsx', ['default', 'states']),
  entry('layout', 'sidebar-profile', 'SidebarProfile', 'components/layout/SidebarProfile.tsx', ['interactive']),
  entry('layout', 'page-loading-fallback', 'PageLoadingFallback', 'components/layout/RouteBoundary.tsx', ['loading']),
  entry('layout', 'route-boundary', 'RouteBoundary', 'components/layout/RouteBoundary.tsx', ['default', 'error']),
  entry('layout', 'route-outlet-boundary', 'RouteOutletBoundary', 'components/layout/RouteBoundary.tsx'),
  entry('layout', 'standalone-route-boundary', 'StandaloneRouteBoundary', 'components/layout/RouteBoundary.tsx', ['default', 'error']),
  entry('layout', 'deep-link-guard', 'DeepLinkGuard', 'components/routing/DeepLinkGuard.tsx'),
  entry('layout', 'session-continuity-guard', 'SessionContinuityGuard', 'components/routing/SessionContinuityGuard.tsx'),
  entry('layout', 'route-focus-coordinator', 'RouteFocusCoordinator', 'components/routing/RouteFocusCoordinator.tsx'),
  entry('layout', 'theme-toggle', 'ThemeToggle', 'components/theme/ThemeToggle.tsx', ['interactive']),
  entry('layout', 'ui-language-toggle', 'UiLanguageToggle', 'components/i18n/UiLanguageToggle.tsx', ['interactive']),

  entry('dashboard', 'dashboard-panel-header', 'DashboardPanelHeader', 'components/dashboard/DashboardPanelHeader.tsx'),
  entry('dashboard', 'dashboard-state-block', 'DashboardStateBlock', 'components/dashboard/DashboardStateBlock.tsx', ['default', 'loading', 'empty']),
  entry('dashboard', 'home-readiness-card', 'HomeReadinessCard', 'components/home/HomeReadinessCard.tsx', ['default', 'loading', 'empty', 'error']),
  entry('dashboard', 'home-onboarding-section', 'HomeOnboardingSection', 'components/onboarding/HomeOnboardingSection.tsx', ['default', 'empty']),
  entry('dashboard', 'onboarding-today-plan-card', 'OnboardingTodayPlanCard', 'components/onboarding/OnboardingTodayPlanCard.tsx', ['default']),
  entry('dashboard', 'agent-onboarding-wizard', 'AgentOnboardingWizard', 'components/onboarding/AgentOnboardingWizard.tsx', ['interactive']),
  entry('dashboard', 'zero-config-first-run-panel', 'ZeroConfigFirstRunPanel', 'components/onboarding/ZeroConfigFirstRunPanel.tsx', ['default', 'empty']),

  entry('alerts', 'alert-rule-form', 'AlertRuleForm', 'components/alerts/AlertRuleForm.tsx', ['interactive', 'states']),
  entry('alerts', 'alert-rule-list', 'AlertRuleList', 'components/alerts/AlertRuleList.tsx', ['default', 'loading', 'empty']),
  entry('alerts', 'alert-trigger-history', 'AlertTriggerHistory', 'components/alerts/AlertTriggerHistory.tsx', ['default', 'loading', 'empty']),
  entry('alerts', 'alerts-workspace', 'AlertsWorkspace', 'components/alerts/AlertsWorkspace.tsx', ['default'], 'full'),

  entry('history', 'history-list', 'HistoryList', 'components/history/HistoryList.tsx', ['default', 'loading', 'empty']),
  entry('history', 'history-list-item', 'HistoryListItem', 'components/history/HistoryListItem.tsx', ['default', 'states']),
  entry('history', 'stock-bar', 'StockBar', 'components/history/StockBar.tsx', ['default', 'loading', 'empty']),
  entry('history', 'stock-bar-item', 'StockBarItemComponent', 'components/history/StockBarItem.tsx', ['default', 'states']),
  entry('history', 'stock-history-trend-drawer', 'StockHistoryTrendDrawer', 'components/history/StockHistoryTrendDrawer.tsx', ['default', 'loading', 'empty', 'error']),

  entry('signals', 'decision-signal-card', 'DecisionSignalCard', 'components/decision-signals/DecisionSignalDisplay.tsx', ['default', 'interactive', 'states']),
  entry('signals', 'decision-signal-details', 'DecisionSignalDetails', 'components/decision-signals/DecisionSignalDisplay.tsx', ['default', 'loading', 'empty', 'error']),
  entry('signals', 'decision-signal-memory-controls', 'DecisionSignalMemoryControls', 'components/decision-signals/DecisionSignalMemoryControls.tsx', ['default', 'error']),
  entry('signals', 'decision-signal-outcome-badge', 'DecisionSignalOutcomeBadge', 'components/decision-signals/DecisionSignalDisplay.tsx', ['variants']),
  entry('signals', 'decision-signal-outcome-explorer', 'DecisionSignalOutcomeExplorer', 'components/decision-signals/DecisionSignalOutcomeExplorer.tsx', ['default', 'empty', 'error']),
  entry('signals', 'portfolio-signal-summary', 'PortfolioSignalSummary', 'components/decision-signals/DecisionSignalDisplay.tsx', ['default', 'loading', 'empty']),
  entry('signals', 'timeline-tooltip', 'TimelineTooltip', 'components/decision-signals/DecisionSignalTimeline.tsx'),
  entry('signals', 'decision-signal-timeline', 'DecisionSignalTimeline', 'components/decision-signals/DecisionSignalTimeline.tsx', ['default', 'loading', 'empty', 'error']),
  entry('signals', 'decision-signal-create-drawer', 'DecisionSignalCreateDrawer', 'components/decision-signals/DecisionSignalCreateDrawer.tsx', ['interactive', 'states']),
  entry('signals', 'decision-signal-outcome-run-panel', 'DecisionSignalOutcomeRunPanel', 'components/decision-signals/DecisionSignalOutcomeRunPanel.tsx', ['interactive', 'empty', 'error']),
  entry('signals', 'decision-signal-outcome-stats-card', 'DecisionSignalOutcomeStatsCard', 'components/decision-signals/DecisionSignalOutcomeStatsCard.tsx', ['default', 'empty', 'loading']),
  entry('signals', 'decision-signal-profile-calibration', 'DecisionSignalProfileCalibration', 'components/decision-signals/DecisionSignalProfileCalibration.tsx', ['default', 'states']),
  entry('signals', 'skill-outcome-performance-table', 'SkillOutcomePerformanceTable', 'components/skill-outcomes/SkillOutcomePerformanceTable.tsx', ['default', 'empty']),
  entry('signals', 'skill-outcome-recent-lists', 'SkillOutcomeRecentLists', 'components/skill-outcomes/SkillOutcomeRecentLists.tsx', ['default', 'empty']),
  entry('signals', 'skill-outcome-run-panel', 'SkillOutcomeRunPanel', 'components/skill-outcomes/SkillOutcomeRunPanel.tsx', ['interactive', 'empty', 'error']),

  entry('reports', 'analysis-context-summary', 'AnalysisContextSummary', 'components/report/AnalysisContextSummary.tsx', ['default', 'empty']),
  entry('reports', 'market-review-report-view', 'MarketReviewReportView', 'components/report/MarketReviewReportView.tsx', ['default', 'loading', 'error']),
  entry('reports', 'market-structure-card', 'MarketStructureCard', 'components/report/MarketStructureCard.tsx', ['default', 'empty']),
  entry('reports', 'report-details', 'ReportDetails', 'components/report/ReportDetails.tsx', ['interactive', 'empty']),
  entry('reports', 'report-diagnostics', 'ReportDiagnostics', 'components/report/ReportDiagnostics.tsx', ['default', 'loading', 'error']),
  entry('reports', 'report-markdown', 'ReportMarkdown', 'components/report/ReportMarkdown.tsx', ['interactive']),
  entry('reports', 'report-markdown-body', 'ReportMarkdownBody', 'components/report/ReportMarkdownBody.tsx'),
  entry('reports', 'report-markdown-drawer', 'ReportMarkdownDrawer', 'components/report/ReportMarkdownDrawer.tsx', ['interactive']),
  entry('reports', 'report-markdown-panel', 'ReportMarkdownPanel', 'components/report/ReportMarkdownPanel.tsx', ['default', 'loading', 'error']),
  entry('reports', 'report-news', 'ReportNews', 'components/report/ReportNews.tsx', ['default', 'loading', 'empty', 'error']),
  entry('reports', 'report-overview', 'ReportOverview', 'components/report/ReportOverview.tsx', ['default', 'states']),
  entry('reports', 'report-strata', 'ReportStrata', 'components/report/ReportStrata.tsx', ['default', 'empty']),
  entry('reports', 'report-strategy', 'ReportStrategy', 'components/report/ReportStrategy.tsx', ['default', 'empty']),
  entry('reports', 'report-structured-insights', 'ReportStructuredInsights', 'components/report/ReportStructuredInsights.tsx', ['default', 'empty']),
  entry('reports', 'report-summary', 'ReportSummary', 'components/report/ReportSummary.tsx', ['default', 'loading', 'error']),
  entry(
    'reports',
    'report-version-compare-view',
    'ReportVersionCompareView',
    'components/report-version-compare/ReportVersionCompareView.tsx',
    ['default', 'empty', 'states'],
  ),
  entry('reports', 'share-image-button', 'ShareImageButton', 'components/report/ShareImageButton.tsx', ['default', 'states']),
  entry('reports', 'market-review-region-selector', 'MarketReviewRegionSelector', 'components/market-review/MarketReviewRegionSelector.tsx', ['interactive', 'states']),
  entry('reports', 'deep-research-panel', 'DeepResearchPanel', 'components/chat/DeepResearchPanel.tsx', ['interactive', 'empty', 'error']),
  entry('reports', 'chat-composer', 'ChatComposer', 'components/chat/ChatComposer.tsx', ['default', 'loading', 'error']),
  entry('reports', 'chat-message-list', 'ChatMessageList', 'components/chat/ChatMessageList.tsx', ['default', 'loading', 'empty']),
  entry('reports', 'chat-session-sidebar', 'ChatSessionSidebar', 'components/chat/ChatSessionSidebar.tsx', ['default', 'loading', 'empty', 'error']),
  entry('reports', 'chat-thinking-details', 'ChatThinkingDetails', 'components/chat/ChatThinkingDetails.tsx', ['default']),
  entry('reports', 'chat-thinking-toggle', 'ChatThinkingToggle', 'components/chat/ChatThinkingDetails.tsx', ['interactive']),

  entry('runFlow', 'run-flow-event-list', 'RunFlowEventList', 'components/run-flow/RunFlowEventList.tsx', ['default', 'empty']),
  entry('runFlow', 'run-flow-graph', 'RunFlowGraph', 'components/run-flow/RunFlowGraph.tsx', ['default', 'interactive']),
  entry('runFlow', 'run-flow-node-details', 'RunFlowNodeDetails', 'components/run-flow/RunFlowNodeDetails.tsx', ['default', 'empty']),
  entry('runFlow', 'run-flow-panel', 'RunFlowPanel', 'components/run-flow/RunFlowPanel.tsx', ['default', 'loading', 'error']),
  entry('runFlow', 'run-flow-summary-bar', 'RunFlowSummaryBar', 'components/run-flow/RunFlowSummaryBar.tsx'),

  entry('settings', 'ai-overview-matrix', 'AiOverviewMatrix', 'components/settings/AiOverviewMatrix.tsx', ['default', 'states']),
  entry('settings', 'agent-behavior-panel', 'AgentBehaviorPanel', 'components/settings/AgentBehaviorPanel.tsx', ['interactive', 'states', 'empty', 'error']),
  entry('settings', 'auth-settings-card', 'AuthSettingsCard', 'components/settings/AuthSettingsCard.tsx', ['interactive', 'error']),
  entry('settings', 'change-password-card', 'ChangePasswordCard', 'components/settings/ChangePasswordCard.tsx', ['interactive', 'error']),
  entry('settings', 'data-providers-panel', 'DataProvidersPanel', 'components/settings/DataProvidersPanel.tsx', ['interactive', 'empty']),
  entry('settings', 'first-run-wizard', 'FirstRunWizard', 'components/settings/FirstRunWizard.tsx', ['interactive', 'error']),
  entry('settings', 'generation-backend-status-panel', 'GenerationBackendStatusPanel', 'components/settings/GenerationBackendStatusPanel.tsx', ['default', 'loading', 'error']),
  entry('settings', 'kronos-status-panel', 'KronosStatusPanel', 'components/settings/KronosStatusPanel.tsx', ['default', 'loading', 'error']),
  entry('settings', 'kronos-settings-fields', 'KronosSettingsFields', 'components/settings/KronosSettingsFields.tsx', ['default', 'empty']),
  entry('settings', 'local-models-with-kronos', 'LocalModelsWithKronos', 'components/settings/LocalModelsWithKronos.tsx', ['default', 'loading', 'error']),
  entry('settings', 'intelligent-import', 'IntelligentImport', 'components/settings/IntelligentImport.tsx', ['interactive', 'error']),
  entry('settings', 'intelligence-sources-panel', 'IntelligenceSourcesPanel', 'components/settings/IntelligenceSourcesPanel.tsx', ['default', 'loading', 'empty', 'error']),
  entry('settings', 'investment-framework-settings-card', 'InvestmentFrameworkSettingsCard', 'components/settings/InvestmentFrameworkSettingsCard.tsx', ['default', 'empty', 'error']),
  entry('settings', 'investment-framework-prompt-preview', 'InvestmentFrameworkPromptPreview', 'components/settings/InvestmentFrameworkPromptPreview.tsx', ['default', 'empty']),
  entry('settings', 'settings-mode-toggle', 'SettingsModeToggle', 'components/settings/SettingsModeToggle.tsx', ['interactive']),
  entry('settings', 'settings-agent-onboarding-host', 'SettingsAgentOnboardingHost', 'components/onboarding/SettingsAgentOnboardingHost.tsx', ['interactive']),
  entry('settings', 'settings-onboarding-hosts', 'SettingsOnboardingHosts', 'components/onboarding/SettingsOnboardingHosts.tsx', ['interactive']),
  entry('settings', 'llm-channel-editor', 'LLMChannelEditor', 'components/settings/LLMChannelEditor.tsx', ['interactive', 'empty', 'error']),
  entry('settings', 'llm-config-mode-banner', 'LLMConfigModeBanner', 'components/settings/LLMConfigModeBanner.tsx', ['default', 'loading', 'error']),
  entry('settings', 'local-models-panel', 'LocalModelsPanel', 'components/settings/LocalModelsPanel.tsx', ['default', 'interactive', 'empty', 'error']),
  entry('settings', 'model-fallback-editor', 'ModelFallbackEditor', 'components/settings/ModelFallbackEditor.tsx', ['interactive', 'empty']),
  entry('settings', 'model-multi-select', 'ModelMultiSelect', 'components/settings/ModelMultiSelect.tsx', ['interactive', 'empty']),
  entry('settings', 'multi-select-dropdown', 'MultiSelectDropdown', 'components/settings/MultiSelectDropdown.tsx', ['interactive', 'states']),
  entry('settings', 'notification-channels-panel', 'NotificationChannelsPanel', 'components/settings/NotificationChannelsPanel.tsx', ['interactive', 'empty']),
  entry('settings', 'notification-test-panel', 'NotificationTestPanel', 'components/settings/NotificationTestPanel.tsx', ['interactive', 'loading', 'error']),
  entry('settings', 'provider-quick-links', 'ProviderQuickLinks', 'components/settings/ProviderQuickLinks.tsx'),
  entry('settings', 'settings-alert', 'SettingsAlert', 'components/settings/SettingsAlert.tsx', ['variants']),
  entry('settings', 'settings-configuration-summary', 'SettingsConfigurationSummary', 'components/settings/SettingsConfigurationSummary.tsx'),
  entry('settings', 'system-config-summary', 'SystemConfigSummary', 'components/settings/SettingsConfigurationSummary.tsx'),
  entry('settings', 'settings-error-summary', 'SettingsErrorSummary', 'components/settings/SettingsErrorSummary.tsx', ['default', 'empty']),
  entry('settings', 'settings-field', 'SettingsField', 'components/settings/SettingsField.tsx', ['default', 'states']),
  entry('settings', 'settings-help-button', 'SettingsHelpButton', 'components/settings/SettingsHelpButton.tsx', ['interactive']),
  entry('settings', 'settings-loading', 'SettingsLoading', 'components/settings/SettingsLoading.tsx', ['loading']),
  entry('settings', 'settings-section-nav', 'SettingsSectionNav', 'components/settings/SettingsNavigation.tsx', ['interactive', 'states']),
  entry('settings', 'settings-view-tabs', 'SettingsViewTabs', 'components/settings/SettingsNavigation.tsx', ['interactive']),
  entry('settings', 'settings-panel-error-boundary', 'SettingsPanelErrorBoundary', 'components/settings/SettingsPanelErrorBoundary.tsx', ['default', 'error']),
  entry('settings', 'settings-section-card', 'SettingsSectionCard', 'components/settings/SettingsSectionCard.tsx'),

  entry('reports', 'dcf-sensitivity-panel', 'DcfSensitivityPanel', 'components/valuation/DcfSensitivityPanel.tsx', ['default', 'empty', 'interactive']),
  entry('stockSearch', 'kline-chart', 'KlineChart', 'components/charts/KlineChart.tsx', ['default', 'empty', 'states']),
  entry('stockSearch', 'risk-heatmap', 'RiskHeatmap', 'components/charts/RiskHeatmap.tsx', ['default', 'empty']),

  entry('stockSearch', 'mini-sparkline', 'MiniSparkline', 'components/screening/MiniSparkline.tsx'),
  entry('stockSearch', 'screen-alert-message', 'ScreenAlertMessage', 'components/screening/ScreenAlertMessage.tsx'),
  entry('stockSearch', 'screening-configuration-modal', 'ScreeningConfigurationModal', 'components/screening/ScreeningConfigurationModal.tsx', ['interactive']),
  entry('stockSearch', 'screening-hotspots-section', 'ScreeningHotspotsSection', 'components/screening/ScreeningHotspotsSection.tsx', ['default', 'empty']),
  entry('stockSearch', 'screening-results-section', 'ScreeningResultsSection', 'components/screening/ScreeningResultsSection.tsx', ['default', 'empty']),
  entry('stockSearch', 'screening-run-status-card', 'ScreeningRunStatusCard', 'components/screening/ScreeningRunStatusCard.tsx', ['default', 'loading']),
  entry('stockSearch', 'screening-strategy-bar', 'ScreeningStrategyBar', 'components/screening/ScreeningStrategyBar.tsx', ['interactive']),

  entry('stockSearch', 'stock-autocomplete', 'StockAutocomplete', 'components/StockAutocomplete/StockAutocomplete.tsx', ['interactive', 'states']),
  entry('stockSearch', 'suggestions-list', 'SuggestionsList', 'components/StockAutocomplete/SuggestionsList.tsx', ['default', 'empty']),
  entry('tasks', 'analysis-phase-select', 'AnalysisPhaseSelect', 'components/analysis/AnalysisPhaseSelect.tsx', ['interactive', 'states']),
  entry('tasks', 'task-panel', 'TaskPanel', 'components/tasks/TaskPanel.tsx', ['default', 'loading', 'states']),
  entry('watchlist', 'home-stock-workspace', 'HomeStockWorkspace', 'components/watchlist/HomeStockWorkspace.tsx', ['interactive', 'loading', 'empty', 'error']),
  entry('watchlist', 'watchlist-score-column', 'WatchlistScoreColumn', 'components/watchlist/WatchlistScoreColumn.tsx', ['default', 'interactive', 'empty']),
  entry('watchlist', 'home-watchlist-groups-section', 'HomeWatchlistGroupsSection', 'components/watchlist/HomeWatchlistGroupsSection.tsx', ['default', 'loading', 'error']),
  entry('watchlist', 'watchlist-groups-panel', 'WatchlistGroupsPanel', 'components/watchlist/WatchlistGroupsPanel.tsx', ['interactive', 'empty', 'error']),
];

export const PLAYGROUND_ENTRY_BY_ID = new Map(PLAYGROUND_CATALOG.map((item) => [item.id, item]));

export function getPlaygroundEntry(id: string | undefined): PlaygroundEntry {
  return (id && PLAYGROUND_ENTRY_BY_ID.get(id)) || PLAYGROUND_CATALOG[0];
}

export function getPlaygroundScenario(entryValue: PlaygroundEntry, id: string | undefined): PlaygroundScenarioId {
  return entryValue.scenarios.some((item) => item.id === id)
    ? id as PlaygroundScenarioId
    : entryValue.scenarios[0].id;
}
