import type {
  AnalysisContextPackOverview,
  AnalysisReport,
  HistoryItem,
  MarketReviewPayload,
  MarketStructureContext,
  RunDiagnosticSummary,
  StockBarItem,
  TaskInfo,
} from '../types/analysis';
import type { AlertNotificationItem, AlertRuleItem, AlertTriggerItem } from '../types/alerts';
import type {
  DecisionSignalFeedbackItem,
  DecisionSignalItem,
  DecisionSignalOutcomeItem,
} from '../types/decisionSignals';
import type { RunFlowSnapshot } from '../types/runFlow';
import type { StockSuggestion } from '../types/stockIndex';
import type {
  LlmConnectionFieldSchema,
  LlmProviderCatalogEntry,
  SystemConfigItem,
} from '../types/systemConfig';

export const FIXTURE_TIMESTAMP = '2026-07-20T15:30:00Z';

export const fixtureAnalysisContext: AnalysisContextPackOverview = {
  packVersion: '1.0',
  createdAt: FIXTURE_TIMESTAMP,
  subject: { code: '600519', stockName: 'Kweichow Moutai', market: 'cn' },
  blocks: [
    { key: 'quote', label: 'Quote', status: 'available', source: 'fixture_quote', warnings: [], missingReasons: [] },
    { key: 'daily_bars', label: 'Daily bars', status: 'available', source: 'fixture_daily', warnings: [], missingReasons: [] },
    { key: 'news', label: 'News', status: 'partial', source: 'fixture_news', warnings: ['limited_window'], missingReasons: [] },
    { key: 'fundamentals', label: 'Fundamentals', status: 'missing', source: null, warnings: [], missingReasons: ['not_requested'] },
  ],
  counts: {
    available: 2,
    missing: 1,
    notSupported: 0,
    fallback: 0,
    stale: 0,
    estimated: 0,
    partial: 1,
    fetchFailed: 0,
  },
  dataQuality: {
    overallScore: 82,
    level: 'usable',
    blockScores: { quote: 100, daily_bars: 96, news: 65, fundamentals: 0 },
    limitations: ['fundamentals: missing'],
  },
  warnings: ['limited_news_window'],
  metadata: { triggerSource: 'playground', newsResultCount: 2 },
};

export const fixtureMarketStructure: MarketStructureContext = {
  schemaVersion: 'market-structure-v1',
  status: 'partial',
  market: 'cn',
  tradeDate: '2026-07-20',
  marketThemeContext: {
    schemaVersion: 'market-theme-v1',
    status: 'partial',
    market: 'cn',
    activeThemes: [{ name: 'Consumer recovery', rank: 1, changePct: 2.4, source: 'concept', phase: 'accelerating' }],
    leadingConcepts: [{ name: 'Premium consumption', rank: 1, changePct: 2.1, source: 'concept' }],
    leadingIndustries: [{ name: 'Beverages', rank: 2, changePct: 1.6, source: 'industry' }],
    laggingThemes: [{ name: 'Cyclicals', rank: 1, changePct: -0.8, source: 'industry' }],
    themeBreadth: { activeCount: 4, leadingConceptCount: 2, leadingIndustryCount: 1, laggingCount: 1 },
    dataQuality: { status: 'partial', missingFields: ['northbound_flow'], sources: [], errors: [] },
  },
  stockMarketPosition: {
    schemaVersion: 'stock-market-position-v1',
    status: 'partial',
    stockCode: '600519',
    stockName: 'Kweichow Moutai',
    market: 'cn',
    primaryTheme: { name: 'Premium consumption', source: 'concept', phase: 'accelerating', rank: 1, changePct: 2.1 },
    relatedBoards: [{ name: 'Beverages', type: 'industry', rank: 2, changePct: 1.6 }],
    stockRole: 'leader',
    themePhase: 'accelerating',
    riskTags: [{ code: 'crowded_trade', message: 'Crowded positioning' }],
    missingFields: [],
  },
};

export const fixtureReport: AnalysisReport = {
  meta: {
    id: 101,
    queryId: 'fixture-query-101',
    stockCode: '600519',
    stockName: 'Kweichow Moutai',
    reportType: 'detailed',
    reportLanguage: 'en',
    createdAt: FIXTURE_TIMESTAMP,
    currentPrice: 1482.5,
    changePct: 1.28,
    modelUsed: 'fixture-route',
    marketPhaseSummary: {
      market: 'cn',
      phase: 'postmarket',
      marketLocalTime: '2026-07-20T17:00:00+08:00',
      sessionDate: '2026-07-20',
      effectiveDailyBarDate: '2026-07-20',
      isTradingDay: true,
      isMarketOpenNow: false,
      isPartialBar: false,
      minutesToOpen: null,
      minutesToClose: null,
      triggerSource: 'playground',
      analysisIntent: 'auto',
      warnings: [],
    },
  },
  summary: {
    analysisSummary: 'Trend remains constructive while valuation requires disciplined entries.',
    operationAdvice: 'Watch for a pullback toward support.',
    action: 'watch',
    actionLabel: 'Watch',
    trendPrediction: 'Range-bound with a positive bias.',
    sentimentScore: 68,
    sentimentLabel: 'Bullish',
  },
  strategy: {
    idealBuy: '1450 - 1460',
    secondaryBuy: '1410 - 1425',
    stopLoss: '1380',
    takeProfit: '1540 / 1600',
  },
  details: {
    rawResult: { action: 'watch', score: 68, source: 'playground' },
    contextSnapshot: { quote: { price: 1482.5 }, signal: 'constructive' },
    analysisContextPackOverview: fixtureAnalysisContext,
    belongBoards: [
      { name: 'Beverages', type: 'industry' },
      { name: 'Premium consumption', type: 'concept' },
    ],
    sectorRankings: { top: [{ name: 'Beverages', changePct: 1.6 }], bottom: [{ name: 'Cyclicals', changePct: -0.8 }] },
    conceptRankings: { top: [{ name: 'Premium consumption', changePct: 2.1 }], bottom: [] },
    marketStructure: fixtureMarketStructure,
  },
};

export const fixtureMarketReviewPayload: MarketReviewPayload = {
  version: 1,
  kind: 'market_review',
  region: 'cn',
  language: 'en',
  rootTitle: 'Market Review',
  generatedAt: FIXTURE_TIMESTAMP,
  breadth: { upCount: 3120, downCount: 1420, flatCount: 180, limitUpCount: 72, limitDownCount: 4, totalAmount: 9600, turnoverUnit: 'CNY 100m' },
  indices: [{ code: '000300', name: 'CSI 300', current: 3920.2, changePct: 1.2, high: 3940.5, low: 3860.1 }],
  sectors: { top: [{ name: 'Semiconductors', changePct: 2.35 }], bottom: [{ name: 'Coal', changePct: -1.1 }] },
  concepts: { top: [{ name: 'Robotics', changePct: 4.2 }], bottom: [{ name: 'Agriculture', changePct: -2.05 }] },
  sections: [
    { key: 'overview', title: 'Market structure', markdown: 'Breadth improved and turnover expanded.' },
    { key: 'risk', title: 'Risk watch', markdown: 'Monitor crowded momentum themes.' },
  ],
  markdownReport: '# Market Review\n\n## Market structure\n\nBreadth improved and turnover expanded.\n\n## Risk watch\n\nMonitor crowded momentum themes.',
};

export const fixtureMarketReviewReport: AnalysisReport = {
  meta: {
    id: 202,
    queryId: 'fixture-market-review',
    stockCode: 'MARKET',
    stockName: 'Market Review',
    reportType: 'market_review',
    reportLanguage: 'en',
    createdAt: FIXTURE_TIMESTAMP,
  },
  summary: {
    analysisSummary: 'Breadth improved.',
    operationAdvice: 'Maintain balanced exposure.',
    action: 'hold',
    trendPrediction: 'Rotation remains active.',
    sentimentScore: 62,
  },
  details: {
    contextSnapshot: { marketReviewPayload: fixtureMarketReviewPayload },
    marketStructure: fixtureMarketStructure,
  },
};

export const fixtureHistoryItems: HistoryItem[] = [
  {
    id: 101,
    queryId: 'fixture-query-101',
    stockCode: '600519',
    stockName: 'Kweichow Moutai',
    reportType: 'detailed',
    trendPrediction: 'Positive bias',
    analysisSummary: 'Constructive trend',
    sentimentScore: 68,
    operationAdvice: 'Watch',
    action: 'watch',
    actionLabel: 'Watch',
    currentPrice: 1482.5,
    changePct: 1.28,
    volumeRatio: 1.1,
    turnoverRate: 0.42,
    modelUsed: 'fixture-route',
    createdAt: FIXTURE_TIMESTAMP,
  },
  {
    id: 102,
    queryId: 'fixture-query-102',
    stockCode: 'AAPL',
    stockName: 'Apple',
    reportType: 'brief',
    trendPrediction: 'Consolidating',
    analysisSummary: 'Momentum cooled',
    sentimentScore: 54,
    operationAdvice: 'Hold',
    action: 'hold',
    actionLabel: 'Hold',
    currentPrice: 214.6,
    changePct: -0.35,
    modelUsed: 'fixture-route',
    createdAt: '2026-07-19T15:30:00Z',
  },
];

export const fixtureStockBarItems: StockBarItem[] = fixtureHistoryItems.map((item, index) => ({
  id: item.id,
  stockCode: item.stockCode,
  stockName: item.stockName,
  reportType: item.reportType,
  sentimentScore: item.sentimentScore,
  operationAdvice: item.operationAdvice,
  action: item.action,
  actionLabel: item.actionLabel,
  analysisCount: index + 2,
  lastAnalysisTime: item.createdAt,
  modelUsed: item.modelUsed,
}));

export const fixtureDiagnosticSummary: RunDiagnosticSummary = {
  traceId: 'fixture-trace-101',
  taskId: 'fixture-task-101',
  queryId: 'fixture-query-101',
  stockCode: '600519',
  triggerSource: 'playground',
  status: 'degraded',
  statusLabel: 'Degraded',
  reason: 'One optional news source used a fallback.',
  components: {
    realtime_quote: { key: 'realtime_quote', label: 'Realtime quote', status: 'ok', message: 'Fresh quote loaded' },
    daily_data: { key: 'daily_data', label: 'Daily data', status: 'ok', message: 'Daily bars loaded' },
    news: { key: 'news', label: 'News', status: 'degraded', message: 'Fallback source used' },
    llm: { key: 'llm', label: 'Analysis', status: 'ok', message: 'Report generated' },
  },
  copyText: 'fixture-trace-101 | degraded | optional news fallback',
};

export const fixtureDecisionSignal: DecisionSignalItem = {
  id: 301,
  stockCode: '600519',
  stockName: 'Kweichow Moutai',
  market: 'cn',
  sourceType: 'analysis',
  sourceAgent: null,
  sourceReportId: 101,
  traceId: 'fixture-trace-101',
  decisionProfile: 'balanced',
  marketPhase: 'postmarket',
  triggerSource: 'playground',
  action: 'watch',
  actionLabel: 'Watch',
  confidence: 0.74,
  score: 68,
  horizon: '5d',
  entryLow: 1450,
  entryHigh: 1460,
  stopLoss: 1380,
  targetPrice: 1540,
  invalidation: 'Daily close below support.',
  watchConditions: 'Volume expansion near the entry range.',
  reason: 'Constructive trend with disciplined entry requirements.',
  riskSummary: 'Valuation and crowded positioning remain the primary risks.',
  catalystSummary: 'Sector rotation and improving breadth.',
  evidence: { trend: 'up', volumeRatio: 1.1 },
  dataQualitySummary: { level: 'usable', score: 82 },
  planQuality: 'complete',
  status: 'active',
  expiresAt: '2026-07-27T15:30:00Z',
  createdAt: FIXTURE_TIMESTAMP,
  updatedAt: FIXTURE_TIMESTAMP,
  metadata: { fixture: true },
};

export const fixtureDecisionSignals: DecisionSignalItem[] = [
  fixtureDecisionSignal,
  {
    ...fixtureDecisionSignal,
    id: 302,
    stockCode: 'AAPL',
    stockName: 'Apple',
    market: 'us',
    action: 'hold',
    score: 56,
    confidence: 0.61,
    createdAt: '2026-07-19T15:30:00Z',
  },
  {
    ...fixtureDecisionSignal,
    id: 303,
    stockCode: '00700',
    stockName: 'Tencent',
    market: 'hk',
    action: 'reduce',
    status: 'expired',
    score: 42,
    confidence: 0.58,
    createdAt: '2026-07-18T15:30:00Z',
  },
];

export const fixtureDecisionOutcome: DecisionSignalOutcomeItem = {
  id: 401,
  signalId: fixtureDecisionSignal.id,
  horizon: '5d',
  engineVersion: 'fixture-v1',
  evalStatus: 'completed',
  outcome: 'hit',
  directionExpected: 'up',
  directionCorrect: true,
  anchorDate: '2026-07-20',
  evalWindowDays: 5,
  startPrice: 1482.5,
  endClose: 1512.2,
  maxHigh: 1520.1,
  minLow: 1474.8,
  stockReturnPct: 2.0,
  action: 'watch',
  market: 'cn',
  marketPhase: 'postmarket',
  sourceType: 'analysis',
  planQuality: 'complete',
  dataQualityLevel: 'usable',
  holdingState: 'empty',
  createdAt: FIXTURE_TIMESTAMP,
  updatedAt: FIXTURE_TIMESTAMP,
};

export const fixtureDecisionFeedback: DecisionSignalFeedbackItem = {
  signalId: fixtureDecisionSignal.id,
  feedbackValue: 'useful',
  reasonCode: 'clear_plan',
  source: 'web',
  createdAt: FIXTURE_TIMESTAMP,
  updatedAt: FIXTURE_TIMESTAMP,
};

export const fixtureRunFlowSnapshot: RunFlowSnapshot = {
  taskId: 'fixture-task-101',
  traceId: 'fixture-trace-101',
  stockCode: '600519',
  stockName: 'Kweichow Moutai',
  status: 'degraded',
  summary: {
    elapsedMs: 8240,
    bottleneckNodeId: 'analysis_pipeline',
    failedAttempts: 1,
    fallbackCount: 1,
    model: 'fixture-route',
    dataSourceCount: 2,
    eventCount: 5,
  },
  lanes: [
    { id: 'orchestration', label: 'Orchestration', order: 0 },
    { id: 'data', label: 'Data', order: 1 },
    { id: 'analysis', label: 'Analysis', order: 2 },
    { id: 'delivery', label: 'Delivery', order: 3 },
  ],
  nodes: [
    { id: 'task_queue', lane: 'orchestration', kind: 'queue', label: 'Task queue', status: 'success', durationMs: 120 },
    { id: 'quote_primary', lane: 'data', kind: 'data_source', label: 'Realtime quote', provider: 'fixture-primary', status: 'failed', durationMs: 680, attempts: 1 },
    { id: 'quote_fallback', lane: 'data', kind: 'data_source', label: 'Quote fallback', provider: 'fixture-fallback', status: 'fallback', durationMs: 420, attempts: 1, recordCount: 1 },
    { id: 'analysis_pipeline', lane: 'analysis', kind: 'analysis', label: 'Analysis pipeline', status: 'success', durationMs: 6120 },
    { id: 'history_save', lane: 'delivery', kind: 'artifact', label: 'History report', status: 'success', durationMs: 300, recordCount: 1 },
  ],
  edges: [
    { id: 'queue-primary', from: 'task_queue', to: 'quote_primary', kind: 'control', status: 'failed', label: 'Fetch' },
    { id: 'primary-fallback', from: 'quote_primary', to: 'quote_fallback', kind: 'fallback', status: 'fallback', label: 'Fallback' },
    { id: 'fallback-analysis', from: 'quote_fallback', to: 'analysis_pipeline', kind: 'data', status: 'success', label: 'Input' },
    { id: 'analysis-history', from: 'analysis_pipeline', to: 'history_save', kind: 'data', status: 'success', label: 'Persist' },
  ],
  events: [
    { id: 'event-1', timestamp: '2026-07-20T15:29:51Z', severity: 'info', type: 'task_started', nodeId: 'task_queue', title: 'Task started' },
    { id: 'event-2', timestamp: '2026-07-20T15:29:52Z', severity: 'danger', type: 'provider_run', nodeId: 'quote_primary', title: 'Primary quote failed', message: 'Stable fixture timeout' },
    { id: 'event-3', timestamp: '2026-07-20T15:29:53Z', severity: 'warning', type: 'provider_run', nodeId: 'quote_fallback', title: 'Fallback quote loaded' },
    { id: 'event-4', timestamp: '2026-07-20T15:29:59Z', severity: 'success', type: 'llm_run', nodeId: 'analysis_pipeline', title: 'Analysis completed' },
    { id: 'event-5', timestamp: FIXTURE_TIMESTAMP, severity: 'success', type: 'history_run', nodeId: 'history_save', title: 'Report saved' },
  ],
  generatedAt: FIXTURE_TIMESTAMP,
};

export const fixtureAlertRules: AlertRuleItem[] = [
  {
    id: 501,
    name: 'Price breakout',
    targetScope: 'single_symbol',
    target: '600519',
    alertType: 'price_cross',
    parameters: { direction: 'above', price: 1500 },
    severity: 'warning',
    enabled: true,
    source: 'playground',
    cooldownActive: false,
    createdAt: FIXTURE_TIMESTAMP,
    updatedAt: FIXTURE_TIMESTAMP,
  },
  {
    id: 502,
    name: 'Market risk light',
    targetScope: 'market',
    target: 'cn',
    alertType: 'market_light_status',
    parameters: { statuses: ['red', 'yellow'] },
    severity: 'critical',
    enabled: false,
    source: 'playground',
    cooldownActive: true,
    createdAt: FIXTURE_TIMESTAMP,
    updatedAt: FIXTURE_TIMESTAMP,
  },
];

export const fixtureAlertTriggers: AlertTriggerItem[] = [
  {
    id: 601,
    ruleId: 501,
    target: '600519',
    observedValue: 1502.2,
    threshold: 1500,
    reason: 'Price crossed the configured threshold.',
    dataSource: 'fixture_quote',
    dataTimestamp: FIXTURE_TIMESTAMP,
    triggeredAt: FIXTURE_TIMESTAMP,
    status: 'triggered',
    diagnostics: 'fixture-trigger-601',
  },
  {
    id: 602,
    ruleId: 502,
    target: 'cn',
    reason: 'Market signal was below the configured severity.',
    dataSource: 'fixture_market',
    dataTimestamp: FIXTURE_TIMESTAMP,
    triggeredAt: FIXTURE_TIMESTAMP,
    status: 'skipped',
  },
];

export const fixtureAlertNotifications: AlertNotificationItem[] = [
  {
    id: 701,
    triggerId: 601,
    channel: 'email',
    attempt: 1,
    success: true,
    retryable: false,
    latencyMs: 128,
    diagnostics: 'fixture-notification-701',
    createdAt: FIXTURE_TIMESTAMP,
  },
];

export const fixtureTasks: TaskInfo[] = [
  {
    taskId: 'fixture-task-101',
    traceId: 'fixture-trace-101',
    stockCode: '600519',
    stockName: 'Kweichow Moutai',
    status: 'processing',
    progress: 64,
    message: 'Generating analysis report',
    reportType: 'detailed',
    createdAt: FIXTURE_TIMESTAMP,
    analysisPhase: 'postmarket',
  },
  {
    taskId: 'fixture-task-102',
    traceId: 'fixture-trace-102',
    stockCode: 'AAPL',
    stockName: 'Apple',
    status: 'completed',
    progress: 100,
    message: 'Analysis completed',
    reportType: 'brief',
    createdAt: '2026-07-20T15:20:00Z',
    completedAt: FIXTURE_TIMESTAMP,
  },
];

export const fixtureSuggestions: StockSuggestion[] = [
  { canonicalCode: '600519.SH', displayCode: '600519', nameZh: 'Kweichow Moutai', market: 'CN', matchType: 'exact', matchField: 'code', score: 100 },
  { canonicalCode: 'AAPL', displayCode: 'AAPL', nameZh: 'Apple', market: 'US', matchType: 'prefix', matchField: 'code', score: 90 },
  { canonicalCode: '00700.HK', displayCode: '00700', nameZh: 'Tencent', market: 'HK', matchType: 'contains', matchField: 'name', score: 80 },
];

const textField = (key: string, title: string): SystemConfigItem => ({
  key,
  value: '',
  rawValueExists: false,
  isMasked: false,
  schema: {
    key,
    title,
    description: `${title} fixture field`,
    category: 'data_source',
    dataType: 'string',
    uiControl: 'text',
    isSensitive: false,
    isRequired: false,
    isEditable: true,
    defaultValue: '',
    options: [],
    validation: {},
    displayOrder: 10,
  },
});

export const fixtureSystemConfigItems: SystemConfigItem[] = [
  { ...textField('TUSHARE_TOKEN', 'Tushare token'), value: '******', rawValueExists: true, isMasked: true, schema: { ...textField('TUSHARE_TOKEN', 'Tushare token').schema!, uiControl: 'password', isSensitive: true } },
  textField('TAVILY_API_KEY', 'Tavily API key'),
  {
    key: 'REPORT_LANGUAGE',
    value: 'zh',
    rawValueExists: true,
    isMasked: false,
    schema: {
      key: 'REPORT_LANGUAGE',
      title: 'Report language',
      description: 'Default report language',
      category: 'base',
      dataType: 'string',
      uiControl: 'select',
      isSensitive: false,
      isRequired: true,
      isEditable: true,
      defaultValue: 'zh',
      options: [{ value: 'zh', label: 'Chinese' }, { value: 'en', label: 'English' }],
      validation: {},
      displayOrder: 20,
    },
  },
];

export const fixtureProviders: LlmProviderCatalogEntry[] = [
  {
    id: 'fixture-cloud',
    label: 'Fixture Cloud',
    labelZh: 'Fixture Cloud',
    labelEn: 'Fixture Cloud',
    protocol: 'openai',
    defaultBaseUrl: 'https://api.example.invalid/v1',
    credentialUrl: null,
    consoleUrl: null,
    modelsUrl: null,
    docsUrl: null,
    capabilities: ['chat', 'json', 'tools'],
    requiresApiKey: true,
    requiresBaseUrl: false,
    supportsDiscovery: true,
    isLocal: false,
    isCustom: false,
  },
];

export const fixtureConnectionFields: LlmConnectionFieldSchema[] = [
  {
    key: 'api_key',
    envSuffix: 'API_KEY',
    dataType: 'string',
    isSensitive: true,
    isRequired: true,
    contract: { requirement: 'required' },
  },
  {
    key: 'base_url',
    envSuffix: 'BASE_URL',
    dataType: 'string',
    isSensitive: false,
    isRequired: false,
    contract: { requirement: 'optional' },
  },
];
