# -*- coding: utf-8 -*-
# Copyright (c) 2026 SiinXu / StockPulse contributors
# SPDX-License-Identifier: AGPL-3.0-only
"""Reasoning-trace export (Issue #135 / T03).

Builds a machine-readable ``reasoning-trace-v1`` package from *already recorded*
analysis history diagnostics and dashboard synthesis fields. This module is a
read-only consumer: it does not change agent recording behaviour.

Security contract (same redaction path as security audit):
- Every export payload is passed through ``redact_sensitive_data``.
- Supported API-key, token, credentialed-URL, and local-path patterns are
  replaced before the package is returned.
- Export is opt-in via ``REASONING_TRACE_EXPORT_ENABLED`` (default off).
- Oversized packages are truncated with an explicit ``truncated`` marker.
"""

from __future__ import annotations

import hashlib
import json
import logging
import math
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Dict, List, Mapping, Optional, Sequence

from src.utils.sanitize import log_safe_exception, redact_sensitive_data

logger = logging.getLogger(__name__)

# Export-specific local path classes. URLs are redacted by the shared helper
# before this expression runs, so these patterns only target local paths.
_LOCAL_PATH_RE = re.compile(
    r"(?<![\w:])(?:"
    r"(?:/(?:Users|home|root|private|var|tmp|opt|etc|workspace)(?:/[^\s,;|<>]*)?)|"
    r"(?:[A-Za-z]:[\\/][^\s,;|<>]+)|"
    r"(?:\\\\[^\\\s]+\\[^\s,;|<>]+)|"
    r"(?:~[\\/][^\s,;|<>]+)|"
    r"(?:\.\.?[\\/][^\s,;|<>]+)"
    r")"
)
_JWT_RE = re.compile(
    r"(?<![A-Za-z0-9_-])[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\."
    r"[A-Za-z0-9_-]{8,}(?![A-Za-z0-9_-])"
)
# Structural correlation identities (UUID hex, dashed UUID, "history:<pk>", integer
# primary keys) are generated by this system and are not credentials. They must
# survive redaction so exports stay correlatable with runtime logs and audit rows.
# The charset deliberately excludes "." and "/" so JWT-shaped values, credentialed
# URLs, and filesystem paths can never qualify and stay redacted.
_STRUCTURAL_IDENTITY_RE = re.compile(
    r"\A[A-Za-z0-9][A-Za-z0-9_-]{0,63}(?::[A-Za-z0-9][A-Za-z0-9_-]{0,63})?\Z"
)
# ``run`` keys restored after redaction when they pass structural validation.
_STRUCTURAL_IDENTITY_KEYS = ("record_id", "query_id", "trace_id", "run_id", "lookup_key")

SCHEMA_VERSION = "reasoning-trace-v1"
DEFAULT_MAX_EXPORT_CHARS = 500_000
MIN_MAX_EXPORT_CHARS = 10_000
MAX_MAX_EXPORT_CHARS = 2_000_000
DEFAULT_MAX_AGENT_EVENTS = 200
DEFAULT_MAX_TOOL_CALLS_PER_AGENT = 50
DEFAULT_MAX_STRING_CHARS = 4_000
DEFAULT_MAX_SOURCE_RUNS = 100
DEFAULT_MAX_QUALITY_ITEMS = 64

COVERAGE_NOT_RECORDED = (
    "full_agent_prompts_and_system_messages",
    "tool_arguments_without_deep_payload",
    "chat_provider_protocol_thinking_blocks",
    "ephemeral_sse_stream_events",
    "raw_provider_api_responses",
)


class ReasoningTraceExportDisabled(RuntimeError):
    """Raised when export is requested while the feature flag is off."""

    code = "reasoning_trace_export_disabled"

    def __init__(self) -> None:
        super().__init__(self.code)


class ReasoningTraceNotFound(RuntimeError):
    """Raised when the history record (or required payload) cannot be resolved."""

    code = "reasoning_trace_not_found"

    def __init__(self, message: str = "reasoning_trace_not_found") -> None:
        super().__init__(message)
        self.code = "reasoning_trace_not_found"


@dataclass(frozen=True)
class ReasoningTraceExportResult:
    """Exported package plus optional human-readable markdown."""

    package: Dict[str, Any]
    markdown: str
    truncated: bool
    schema_version: str = SCHEMA_VERSION

    def to_json_dict(self) -> Dict[str, Any]:
        return dict(self.package)

    def to_json_text(self) -> str:
        """Return standards-compliant compact JSON used for response sizing."""
        return _strict_json_dump(self.package)


def _resolve_runtime_config(config: Any = None) -> Any:
    """Return an injected config or the composition-root config (no bare get_config)."""
    if config is not None:
        return config
    try:
        from src.application_services import get_application_services

        return get_application_services().config
    except Exception as exc:  # broad-exception: fallback_recorded - Config lookup must not enable export accidentally.
        log_safe_exception(
            logger,
            "Reasoning trace export config lookup failed; using safe defaults",
            exc,
            error_code="reasoning_trace_export_config_lookup_failed",
            level=logging.DEBUG,
        )
        return None


def is_reasoning_trace_export_enabled(config: Any = None) -> bool:
    """Return whether export is enabled (default False — zero impact)."""
    resolved = _resolve_runtime_config(config)
    if resolved is None:
        return False
    return bool(getattr(resolved, "reasoning_trace_export_enabled", False))


def resolve_max_export_chars(config: Any = None) -> int:
    """Return the hard character budget for a single export package."""
    resolved = _resolve_runtime_config(config)
    if resolved is None:
        return DEFAULT_MAX_EXPORT_CHARS
    raw = getattr(resolved, "reasoning_trace_export_max_chars", DEFAULT_MAX_EXPORT_CHARS)
    try:
        value = int(raw)
    except (TypeError, ValueError):
        return DEFAULT_MAX_EXPORT_CHARS
    return min(MAX_MAX_EXPORT_CHARS, max(MIN_MAX_EXPORT_CHARS, value))


def build_config_fingerprint(config: Any = None) -> str:
    """Stable non-secret fingerprint of analysis-relevant config toggles."""
    keys = (
        "agent_observability_enabled",
        "agent_observability_deep_payload",
        "agent_multi_strategy_deliberation",
        "agent_risk_override",
        "generation_backend",
        "report_type",
        "report_language",
    )
    payload: Dict[str, Any] = {}
    if config is not None:
        for key in keys:
            if hasattr(config, key):
                payload[key] = getattr(config, key)
    digest = hashlib.sha256(
        json.dumps(payload, sort_keys=True, default=str).encode("utf-8")
    ).hexdigest()
    return digest[:16]


def _as_mapping(value: Any) -> Dict[str, Any]:
    if isinstance(value, dict):
        return value
    if isinstance(value, Mapping):
        return dict(value)
    return {}


def _as_list(value: Any) -> List[Any]:
    if isinstance(value, list):
        return value
    if isinstance(value, tuple):
        return list(value)
    return []


class _LossLedger:
    """Accumulates every bounded-projection loss so nothing is dropped silently.

    Each bounded projection reports malformed, unsupported, clipped, capped, and
    budget-dropped content here. The ledger is folded into ``package.truncation``
    and reconciled against final coverage on every exit path.
    """

    def __init__(self) -> None:
        self._entries: Dict[tuple[str, str], int] = {}
        self._order: List[tuple[str, str]] = []

    def record(self, path: str, reason: str, count: int = 1) -> None:
        if count <= 0:
            return
        key = (path, reason)
        if key not in self._entries:
            self._entries[key] = 0
            self._order.append(key)
        self._entries[key] += count

    def as_drops(self) -> List[Dict[str, Any]]:
        return [
            {"path": path, "reason": reason, "count": self._entries[(path, reason)]}
            for path, reason in self._order
        ]

    def total(self, path: str) -> int:
        return sum(
            count for (entry_path, _), count in self._entries.items() if entry_path == path
        )

    def __bool__(self) -> bool:
        return bool(self._entries)


def _clip_text(
    value: Any,
    *,
    limit: int = DEFAULT_MAX_STRING_CHARS,
    ledger: Optional[_LossLedger] = None,
    path: Optional[str] = None,
) -> Optional[str]:
    if value is None:
        return None
    if not isinstance(value, (str, int, float, bool)):
        if ledger is not None and path:
            ledger.record(path, "unsupported_value_type")
        return None
    if isinstance(value, float) and not math.isfinite(value):
        if ledger is not None and path:
            ledger.record(path, "non_finite_number")
        return None
    text = str(value)
    if len(text) <= limit:
        return text
    if ledger is not None and path:
        ledger.record(path, "value_clipped")
    return text[: max(0, limit - 16)] + "…[truncated]"


def _finite_float(value: Any) -> Optional[float]:
    if value is None or isinstance(value, bool):
        return None
    try:
        parsed = float(value)
    except (TypeError, ValueError, OverflowError):
        return None
    return parsed if math.isfinite(parsed) else None


def _nonnegative_int(value: Any) -> Optional[int]:
    if value is None or isinstance(value, bool):
        return None
    try:
        parsed = int(value)
    except (TypeError, ValueError, OverflowError):
        return None
    return parsed if parsed >= 0 else None


def _clip_string_list(
    value: Any,
    *,
    limit: int = DEFAULT_MAX_QUALITY_ITEMS,
    ledger: Optional[_LossLedger] = None,
    path: Optional[str] = None,
) -> List[str]:
    items = _as_list(value)
    if ledger is not None and path and len(items) > limit:
        ledger.record(path, "list_cap_dropped", len(items) - limit)
    result: List[str] = []
    for item in items[:limit]:
        clipped = _clip_text(item, limit=256, ledger=ledger, path=path)
        if clipped is None:
            if ledger is not None and path:
                ledger.record(path, "unsupported_list_item")
            continue
        result.append(clipped)
    return result


def _strict_json_dump(payload: Any) -> str:
    return json.dumps(
        payload,
        ensure_ascii=False,
        allow_nan=False,
        separators=(",", ":"),
    )


def _safe_json_size(payload: Any) -> int:
    return len(_strict_json_dump(payload))


def _redact_local_paths(value: Any, *, depth: int = 0, seen: Optional[set[int]] = None) -> Any:
    """Replace absolute local filesystem paths after secret redaction."""
    if seen is None:
        seen = set()
    if depth > 20:
        return value
    if value is None or isinstance(value, (bool, int, float)):
        return value
    if isinstance(value, str):
        value = _JWT_RE.sub("[REDACTED]", value)
        return _LOCAL_PATH_RE.sub("<redacted-path>", value)
    obj_id = id(value)
    if obj_id in seen:
        return value
    if isinstance(value, Mapping):
        seen.add(obj_id)
        return {
            str(k): _redact_local_paths(v, depth=depth + 1, seen=seen)
            for k, v in value.items()
        }
    if isinstance(value, list):
        seen.add(obj_id)
        return [_redact_local_paths(item, depth=depth + 1, seen=seen) for item in value]
    if isinstance(value, tuple):
        return tuple(_redact_local_paths(item, depth=depth + 1, seen=seen) for item in value)
    return value


def redact_export_payload(value: Any) -> Any:
    """Hard boundary for exports: audit-grade secret redaction + local path scrubbing.

    Secret redaction reuses ``redact_sensitive_data`` (same helper as
    ``SecurityAuditService``). Absolute local paths are scrubbed afterwards so
    user home directories never leave the process boundary.
    """
    redacted = redact_sensitive_data(value, redact_opaque_tokens=True)
    return _redact_local_paths(redacted)


def is_structural_identity(value: Any) -> bool:
    """Return whether a value is a safe non-secret structural correlation id."""
    if not isinstance(value, str) or not value:
        return False
    if _JWT_RE.search(value):
        return False
    return bool(_STRUCTURAL_IDENTITY_RE.fullmatch(value))


def _restore_structural_identities(
    redacted_run: Dict[str, Any], original_run: Mapping[str, Any]
) -> None:
    """Re-apply validated structural identities that opaque-token redaction erased.

    Production ``query_id``/``trace_id`` values are 32-character UUID hex strings
    that the opaque-token redactor cannot distinguish from a bearer token. Only
    keys in :data:`_STRUCTURAL_IDENTITY_KEYS` whose *original* value passes
    :func:`is_structural_identity` are restored; anything else stays redacted.
    """
    for key in _STRUCTURAL_IDENTITY_KEYS:
        original = original_run.get(key)
        if key in redacted_run and is_structural_identity(original):
            redacted_run[key] = original


def _has_content(value: Any) -> bool:
    """Return whether a projected container holds at least one real value."""
    if value is None:
        return False
    if isinstance(value, str):
        return bool(value.strip())
    if isinstance(value, Mapping):
        return any(_has_content(item) for item in value.values())
    if isinstance(value, (list, tuple)):
        return any(_has_content(item) for item in value)
    if isinstance(value, bool):
        return True
    if isinstance(value, (int, float)):
        return True
    return True


def _extract_tool_calls(event: Mapping[str, Any]) -> List[Dict[str, Any]]:
    """Project tool-related agent events into a compact call summary."""
    event_type = str(event.get("event_type") or event.get("type") or "")
    name = str(event.get("name") or event.get("tool") or "")
    if "tool" not in event_type.lower() and not name:
        attrs = _as_mapping(event.get("attrs"))
        if not attrs.get("tool") and not attrs.get("tool_name"):
            return []
        name = str(attrs.get("tool") or attrs.get("tool_name") or name)

    if "tool" not in event_type.lower() and "tool" not in name.lower():
        # Still include explicit tool_start / tool_end style names.
        if event_type not in {
            "agent.tool_start",
            "agent.tool_end",
            "tool_start",
            "tool_end",
            "tool",
        }:
            attrs = _as_mapping(event.get("attrs"))
            if not any(k in attrs for k in ("tool", "tool_name", "tool_call_id")):
                return []

    attrs = _as_mapping(event.get("attrs"))
    entry = {
        "name": _clip_text(name or attrs.get("tool") or attrs.get("tool_name") or "tool", limit=120),
        "status": _clip_text(event.get("status") or attrs.get("status"), limit=64),
        "duration_ms": _finite_float(event.get("duration_ms")),
        "step": _clip_text(event.get("step") or attrs.get("step"), limit=120),
        "sequence": _nonnegative_int(event.get("sequence")),
        "timestamp": _clip_text(event.get("timestamp"), limit=64),
    }
    # Deep payloads may carry sanitized argument previews; never re-expand secrets.
    for key in ("tool_call_id", "error_code"):
        if key in attrs:
            entry[key] = _clip_text(attrs.get(key), limit=120)
    return [{k: v for k, v in entry.items() if v is not None}]


def _group_agents_from_events(
    agent_events: Sequence[Any],
    *,
    max_events: int = DEFAULT_MAX_AGENT_EVENTS,
    ledger: Optional[_LossLedger] = None,
) -> tuple[List[Dict[str, Any]], Dict[str, int]]:
    """Group observability events into per-agent role timelines."""
    agents: Dict[str, Dict[str, Any]] = {}
    ordered_roles: List[str] = []

    malformed = 0
    tool_original = 0
    tool_returned = 0
    limited_events = agent_events[:max_events]
    for index, raw in enumerate(limited_events):
        if not isinstance(raw, Mapping):
            malformed += 1
            continue
        event = dict(raw)
        attrs = _as_mapping(event.get("attrs"))
        role = str(
            attrs.get("agent")
            or attrs.get("agent_name")
            or attrs.get("role")
            or event.get("phase")
            or event.get("name")
            or "unknown"
        )
        role = _clip_text(role, limit=64) or "unknown"
        if role not in agents:
            agents[role] = {
                "role": role,
                "input_summary": None,
                "tool_calls": [],
                "output_opinion": None,
                "events": [],
            }
            ordered_roles.append(role)

        bucket = agents[role]
        summary_event = {
            "event_type": _clip_text(event.get("event_type") or event.get("type"), limit=120),
            "name": _clip_text(event.get("name"), limit=120),
            "status": _clip_text(event.get("status"), limit=64),
            "timestamp": _clip_text(event.get("timestamp"), limit=64),
            "duration_ms": _finite_float(event.get("duration_ms")),
            "sequence": _nonnegative_int(event.get("sequence", index)),
            "phase": _clip_text(event.get("phase"), limit=64),
        }
        bucket["events"].append({k: v for k, v in summary_event.items() if v is not None})

        for call in _extract_tool_calls(event):
            tool_original += 1
            if len(bucket["tool_calls"]) < DEFAULT_MAX_TOOL_CALLS_PER_AGENT:
                bucket["tool_calls"].append(call)
                tool_returned += 1

        # Prefer decision/model_end style text as opinion when present.
        event_type = str(event.get("event_type") or "")
        payload = event.get("payload") if isinstance(event.get("payload"), Mapping) else {}
        opinion_candidate = (
            attrs.get("signal")
            or attrs.get("decision")
            or attrs.get("opinion")
            or payload.get("signal")
            or payload.get("decision")
        )
        if opinion_candidate is not None and (
            "decision" in event_type or bucket["output_opinion"] is None
        ):
            bucket["output_opinion"] = _clip_text(
                opinion_candidate, limit=500, ledger=ledger, path="agents.output_opinion"
            )

        input_candidate = attrs.get("input_summary") or attrs.get("summary")
        if input_candidate and bucket["input_summary"] is None:
            bucket["input_summary"] = _clip_text(
                input_candidate, limit=500, ledger=ledger, path="agents.input_summary"
            )

    returned_events = sum(len(agents[role]["events"]) for role in ordered_roles)
    return [agents[role] for role in ordered_roles], {
        "original_events": len(agent_events),
        "returned_events": returned_events,
        "malformed_events": malformed,
        "event_cap_dropped": max(0, len(agent_events) - max_events),
        "original_tools": tool_original,
        "returned_tools": tool_returned,
        "tool_cap_dropped": max(0, tool_original - tool_returned),
    }


def _extract_synthesis(
    raw_result: Mapping[str, Any], *, ledger: Optional[_LossLedger] = None
) -> Dict[str, Any]:
    dashboard = _as_mapping(raw_result.get("dashboard"))
    strategy = _as_mapping(dashboard.get("strategy_synthesis"))
    committee = _as_mapping(dashboard.get("committee_deliberation"))
    core = _as_mapping(dashboard.get("core_conclusion"))
    base = "dashboard.synthesis"

    disagreement: Dict[str, Any] = {}
    if strategy:
        disagreement = {
            "conflict_severity": _clip_text(
                strategy.get("conflict_severity"), limit=64, ledger=ledger, path=base
            ),
            "conflict_count": _nonnegative_int(strategy.get("conflict_count")),
            "consensus_level": _clip_text(
                strategy.get("consensus_level"), limit=64, ledger=ledger, path=base
            ),
            "supporting_skills": _clip_string_list(
                strategy.get("supporting_skills"), ledger=ledger, path=base
            ),
            "opposing_skills": _clip_string_list(
                strategy.get("opposing_skills"), ledger=ledger, path=base
            ),
        }

    final_conclusion = {
        "final_signal": _clip_text(
            strategy.get("final_signal") or core.get("decision_type") or raw_result.get("decision_type"),
            limit=64,
            ledger=ledger,
            path=base,
        ),
        "operation_advice": _clip_text(
            core.get("operation_advice") or raw_result.get("operation_advice"),
            limit=800,
            ledger=ledger,
            path=base,
        ),
        "confidence_level": _clip_text(
            core.get("confidence_level") or raw_result.get("confidence_level"),
            limit=64,
            ledger=ledger,
            path=base,
        ),
        "analysis_summary": _clip_text(
            core.get("analysis_summary") or raw_result.get("analysis_summary"),
            limit=1200,
            ledger=ledger,
            path=base,
        ),
        "sentiment_score": _finite_float(raw_result.get("sentiment_score")),
    }

    consensus = {
        "consensus_level": _clip_text(
            strategy.get("consensus_level"), limit=64, ledger=ledger, path=base
        ),
        "committee_status": _clip_text(
            committee.get("status") or committee.get("outcome"),
            limit=64,
            ledger=ledger,
            path=base,
        ),
    }

    # Empty containers must stay empty: a container of null values is *not*
    # evidence and must never let coverage report the source as present.
    return {
        "disagreement": {k: v for k, v in disagreement.items() if v not in (None, [])},
        "consensus": {k: v for k, v in consensus.items() if v is not None},
        "final_conclusion": {k: v for k, v in final_conclusion.items() if v is not None},
    }


def _extract_token_usage(value: Any) -> Dict[str, int]:
    usage = _as_mapping(value)
    aliases = {
        "prompt_tokens": ("prompt_tokens", "input_tokens"),
        "completion_tokens": ("completion_tokens", "output_tokens"),
        "total_tokens": ("total_tokens",),
    }
    result: Dict[str, int] = {}
    for output_key, input_keys in aliases.items():
        for input_key in input_keys:
            parsed = _nonnegative_int(usage.get(input_key))
            if parsed is not None:
                result[output_key] = parsed
                break
    return result


def _extract_data_quality(
    context_snapshot: Mapping[str, Any], *, ledger: Optional[_LossLedger] = None
) -> Optional[Dict[str, Any]]:
    overview = _as_mapping(context_snapshot.get("analysis_context_pack_overview"))
    data_quality = overview.get("data_quality")
    if not isinstance(data_quality, Mapping):
        data_quality = overview.get("quality") if isinstance(overview.get("quality"), Mapping) else None
    if not isinstance(data_quality, Mapping):
        return None
    base = "context.data_quality"
    projected = {
        "status": _clip_text(
            data_quality.get("status") or data_quality.get("quality_status"),
            limit=64,
            ledger=ledger,
            path=base,
        ),
        "score": _finite_float(data_quality.get("score")),
        "warnings": _clip_string_list(
            data_quality.get("warnings"), ledger=ledger, path=base
        ),
        "missing_fields": _clip_string_list(
            data_quality.get("missing_fields") or data_quality.get("missing"),
            ledger=ledger,
            path=base,
        ),
    }
    return {key: value for key, value in projected.items() if value not in (None, [])} or None


def _projection_loss_counts(
    raw_result: Mapping[str, Any], context_snapshot: Mapping[str, Any]
) -> tuple[int, int]:
    """Count known nested fields omitted by the bounded public projection."""
    overview = _as_mapping(context_snapshot.get("analysis_context_pack_overview"))
    quality = overview.get("data_quality")
    if not isinstance(quality, Mapping):
        quality = overview.get("quality") if isinstance(overview.get("quality"), Mapping) else {}
    quality_known = {"status", "quality_status", "score", "warnings", "missing_fields", "missing"}
    quality_loss = len(set(quality) - quality_known) if isinstance(quality, Mapping) else 0
    if isinstance(quality, Mapping):
        for key in ("warnings", "missing_fields", "missing"):
            values = _as_list(quality.get(key))
            quality_loss += max(0, len(values) - DEFAULT_MAX_QUALITY_ITEMS)

    dashboard = _as_mapping(raw_result.get("dashboard"))
    sections = (
        (_as_mapping(dashboard.get("strategy_synthesis")), {
            "final_signal", "conflict_severity", "conflict_count", "consensus_level",
            "supporting_skills", "opposing_skills",
        }),
        (_as_mapping(dashboard.get("committee_deliberation")), {"status", "outcome"}),
        (_as_mapping(dashboard.get("core_conclusion")), {
            "decision_type", "operation_advice", "confidence_level", "analysis_summary",
        }),
    )
    synthesis_loss = sum(len(set(section) - known) for section, known in sections)
    return quality_loss, synthesis_loss


def _extract_data_sources(
    diagnostics: Mapping[str, Any],
    context_snapshot: Mapping[str, Any],
    *,
    ledger: Optional[_LossLedger] = None,
) -> tuple[Dict[str, Any], Dict[str, Dict[str, int]]]:
    raw_provider_runs = _as_list(diagnostics.get("provider_runs"))
    provider_runs = []
    provider_malformed = 0
    for raw in raw_provider_runs[:DEFAULT_MAX_SOURCE_RUNS]:
        if not isinstance(raw, Mapping):
            provider_malformed += 1
            continue
        provider_runs.append(
            {
                "provider": _clip_text(raw.get("provider"), limit=64),
                "data_type": _clip_text(raw.get("data_type"), limit=64),
                "operation": _clip_text(raw.get("operation"), limit=64),
                "status": _clip_text(raw.get("status"), limit=32),
                "duration_ms": _finite_float(raw.get("duration_ms")),
                "error_code": _clip_text(raw.get("error_code"), limit=64),
            }
        )

    raw_llm_runs = _as_list(diagnostics.get("llm_runs"))
    llm_runs = []
    llm_malformed = 0
    for raw in raw_llm_runs[:DEFAULT_MAX_SOURCE_RUNS]:
        if not isinstance(raw, Mapping):
            llm_malformed += 1
            continue
        llm_runs.append(
            {
                "provider": _clip_text(raw.get("provider"), limit=64),
                "model": _clip_text(raw.get("model"), limit=120),
                "call_type": _clip_text(raw.get("call_type"), limit=64),
                "status": _clip_text(raw.get("status"), limit=32),
                "duration_ms": _finite_float(raw.get("duration_ms")),
                "usage": _extract_token_usage(raw.get("token_usage") or raw.get("usage")),
            }
        )

    raw_stage_runs = _as_list(diagnostics.get("pipeline_stage_runs"))
    stage_runs = []
    stage_malformed = 0
    for raw in raw_stage_runs[:DEFAULT_MAX_SOURCE_RUNS]:
        if not isinstance(raw, Mapping):
            stage_malformed += 1
            continue
        stage_runs.append(
            {
                "stage": _clip_text(raw.get("stage") or raw.get("name"), limit=64),
                "status": _clip_text(raw.get("status"), limit=32),
                "duration_ms": _finite_float(raw.get("duration_ms")),
            }
        )

    sources = {
        "provider_trace": provider_runs,
        "llm_runs": llm_runs,
        "data_quality_status": _extract_data_quality(context_snapshot, ledger=ledger),
        "pipeline_stage_runs": stage_runs,
    }
    stats = {
        "diagnostics.provider_runs": {
            "original": len(raw_provider_runs),
            "returned": len(provider_runs),
            "malformed": provider_malformed,
        },
        "diagnostics.llm_runs": {
            "original": len(raw_llm_runs),
            "returned": len(llm_runs),
            "malformed": llm_malformed,
        },
        "diagnostics.pipeline_stage_runs": {
            "original": len(raw_stage_runs),
            "returned": len(stage_runs),
            "malformed": stage_malformed,
        },
    }
    return sources, stats


def _render_markdown(package: Mapping[str, Any]) -> str:
    """Render stored/model content only inside an inert indented code block."""
    payload = _strict_json_dump(package)
    safe_payload = payload.replace("<", "\\u003c").replace(">", "\\u003e")
    return (
        "# Reasoning Trace (reasoning-trace-v1)\n\n"
        "Stored and model-originated values are rendered as inert code.\n\n"
        f"    {safe_payload}\n"
    )


def _reconciled_response_size(
    package: Dict[str, Any],
    *,
    output_format: str,
    include_markdown: bool,
) -> tuple[int, str]:
    """Reconcile coverage first so the measured body is the body we return."""
    _reconcile_coverage(package)
    return _response_size(
        package, output_format=output_format, include_markdown=include_markdown
    )


def _response_size(
    package: Dict[str, Any],
    *,
    output_format: str,
    include_markdown: bool,
) -> tuple[int, str]:
    markdown = _render_markdown(package) if include_markdown else ""
    if output_format == "markdown":
        return len(markdown), markdown
    candidate = dict(package)
    if include_markdown:
        candidate["markdown"] = markdown
    return _safe_json_size(candidate), markdown


# Coverage sources whose returned count is verifiable against the final payload.
_COVERAGE_COUNTABLE = {
    "diagnostics.provider_runs": "provider_trace",
    "diagnostics.llm_runs": "llm_runs",
    "diagnostics.pipeline_stage_runs": "pipeline_stage_runs",
}


def _add_reason(entry: Dict[str, Any], reason: str) -> None:
    reasons = entry.setdefault("reasons", [])
    if isinstance(reasons, list) and reason not in reasons:
        reasons.append(reason)


def _mark_coverage_export_truncated(package: Dict[str, Any], source: str) -> None:
    coverage = _as_mapping(package.get("coverage"))
    for entry in _as_list(coverage.get("sources")):
        if isinstance(entry, dict) and entry.get("source") == source:
            entry["export_truncated"] = True
            _add_reason(entry, "export_size_budget_exceeded")


def _returned_count_for(package: Mapping[str, Any], source: str) -> Optional[int]:
    """Count what the *final* payload actually carries for a countable source."""
    if source == "diagnostics.agent_events":
        return sum(
            len(_as_list(agent.get("events")))
            for agent in _as_list(package.get("agents"))
            if isinstance(agent, Mapping)
        )
    output_key = _COVERAGE_COUNTABLE.get(source)
    if output_key is None:
        return None
    return len(_as_list(_as_mapping(package.get("data_sources")).get(output_key)))


def _present_for(package: Mapping[str, Any], source: str) -> bool:
    """Derive presence from actual projected data, never from source existence."""
    if source == "run_meta":
        return _has_content(package.get("run"))
    if source == "context.data_quality":
        return _has_content(_as_mapping(package.get("data_sources")).get("data_quality_status"))
    if source == "dashboard.synthesis":
        return _has_content(package.get("synthesis"))
    return bool(_returned_count_for(package, source))


def _reconcile_coverage(package: Dict[str, Any]) -> None:
    """Make coverage agree with the final payload on every exit path.

    Coverage is rewritten from what the response actually carries, so a
    size-budget drop, a cap, or an empty projection can never leave a stale
    ``present=true`` / ``returned_count`` / ``dropped_count=0`` claim behind.
    """
    coverage = _as_mapping(package.get("coverage"))
    for entry in _as_list(coverage.get("sources")):
        if not isinstance(entry, dict):
            continue
        source = str(entry.get("source") or "")
        returned = _returned_count_for(package, source)
        if returned is not None:
            previous = entry.get("returned_count")
            if isinstance(previous, int) and returned < previous:
                entry["export_truncated"] = True
            entry["returned_count"] = returned
            original = entry.get("original_count")
            if isinstance(original, int):
                dropped = max(0, original - returned)
                entry["dropped_count"] = dropped
                if dropped and not (
                    entry.get("source_truncated") or entry.get("export_truncated")
                ):
                    entry["export_truncated"] = True
        present = _present_for(package, source)
        if entry.get("present") and not present:
            entry["export_truncated"] = True
        entry["present"] = present
        entry["absent"] = not present


def _assert_coverage_invariants(package: Mapping[str, Any]) -> None:
    """Fail closed if coverage and the returned payload ever disagree."""
    coverage = _as_mapping(package.get("coverage"))
    for entry in _as_list(coverage.get("sources")):
        if not isinstance(entry, Mapping):
            raise ValueError("reasoning trace coverage entry is malformed")
        source = str(entry.get("source") or "")
        if entry.get("absent") is entry.get("present"):
            raise ValueError(f"coverage presence invariant violated for {source}")
        if entry.get("present") is not _present_for(package, source):
            raise ValueError(f"coverage presence disagrees with payload for {source}")
        returned = _returned_count_for(package, source)
        if returned is not None:
            if entry.get("returned_count") != returned:
                raise ValueError(f"coverage count disagrees with payload for {source}")
            if bool(returned) != bool(entry.get("present")):
                raise ValueError(f"coverage count/presence invariant violated for {source}")
        dropped = entry.get("dropped_count")
        if dropped is not None and dropped < 0:
            raise ValueError(f"coverage dropped_count is negative for {source}")


def _ensure_truncation(package: Dict[str, Any], *, max_chars: int) -> Dict[str, Any]:
    package["truncated"] = True
    truncation = package.get("truncation")
    if not isinstance(truncation, dict):
        truncation = {
            "marker": "truncated",
            "reason": "source_or_export_truncation",
            "max_chars": max_chars,
            "dropped": [],
        }
        package["truncation"] = truncation
    truncation["max_chars"] = max_chars
    return truncation


def _record_budget_drop(
    package: Dict[str, Any],
    *,
    max_chars: int,
    path: str,
    count: Optional[int] = None,
) -> None:
    truncation = _ensure_truncation(package, max_chars=max_chars)
    drop: Dict[str, Any] = {
        "path": path,
        "reason": "export_size_budget_exceeded",
    }
    if count is not None:
        drop["count"] = count
    truncation["dropped"].append(drop)


def _apply_size_budget(
    package: Dict[str, Any],
    *,
    max_chars: int,
    output_format: str,
    include_markdown: bool,
) -> tuple[Dict[str, Any], str]:
    """Fit the complete negotiated response inside ``max_chars`` on every exit."""
    budget = max(1_000, min(MAX_MAX_EXPORT_CHARS, int(max_chars)))
    size, markdown = _reconciled_response_size(
        package, output_format=output_format, include_markdown=include_markdown
    )
    if size <= budget:
        if include_markdown and output_format == "json":
            package["markdown"] = markdown
        return package, markdown

    truncation = _ensure_truncation(package, max_chars=budget)
    truncation["reason"] = "export_size_budget_exceeded"

    agents = _as_list(package.get("agents"))
    dropped_agent_events = 0
    dropped_tool_calls = 0
    dropped_input_summaries = 0
    dropped_output_opinions = 0
    for agent in agents:
        if not isinstance(agent, dict):
            continue
        events = _as_list(agent.get("events"))
        calls = _as_list(agent.get("tool_calls"))
        dropped_agent_events += len(events)
        dropped_tool_calls += len(calls)
        agent["events"] = []
        agent["tool_calls"] = []
        if agent.get("input_summary"):
            dropped_input_summaries += 1
            agent["input_summary"] = None
        if agent.get("output_opinion"):
            dropped_output_opinions += 1
            agent["output_opinion"] = None
    for path, count in (
        ("agents.events", dropped_agent_events),
        ("agents.tool_calls", dropped_tool_calls),
        ("agents.input_summary", dropped_input_summaries),
        ("agents.output_opinion", dropped_output_opinions),
    ):
        if count:
            _record_budget_drop(
                package, max_chars=budget, path=path, count=count
            )
    _mark_coverage_export_truncated(package, "diagnostics.agent_events")
    size, markdown = _reconciled_response_size(
        package, output_format=output_format, include_markdown=include_markdown
    )
    if size <= budget:
        if include_markdown and output_format == "json":
            package["markdown"] = markdown
        return package, markdown

    if agents:
        _record_budget_drop(package, max_chars=budget, path="agents", count=len(agents))
        package["agents"] = []

    sources = _as_mapping(package.get("data_sources"))
    source_paths = {
        "provider_trace": "diagnostics.provider_runs",
        "llm_runs": "diagnostics.llm_runs",
        "pipeline_stage_runs": "diagnostics.pipeline_stage_runs",
    }
    for key, coverage_source in source_paths.items():
        values = _as_list(sources.get(key))
        if values:
            _record_budget_drop(
                package, max_chars=budget, path=f"data_sources.{key}", count=len(values)
            )
            sources[key] = []
            _mark_coverage_export_truncated(package, coverage_source)
    if sources.get("data_quality_status"):
        _record_budget_drop(
            package, max_chars=budget, path="data_sources.data_quality_status"
        )
        sources["data_quality_status"] = None
        _mark_coverage_export_truncated(package, "context.data_quality")

    synthesis = _as_mapping(package.get("synthesis"))
    conclusion = _as_mapping(synthesis.get("final_conclusion"))
    for key in ("analysis_summary", "operation_advice"):
        if conclusion.get(key):
            _record_budget_drop(
                package, max_chars=budget, path=f"synthesis.final_conclusion.{key}"
            )
            conclusion[key] = None

    size, markdown = _reconciled_response_size(
        package, output_format=output_format, include_markdown=include_markdown
    )
    if size <= budget:
        if include_markdown and output_format == "json":
            package["markdown"] = markdown
        return package, markdown

    # Deterministic typed floor. The configured minimum makes this envelope fit;
    # direct test callers with smaller budgets receive an explicit ValueError.
    run = _as_mapping(package.get("run"))
    minimal: Dict[str, Any] = {
        "schema_version": SCHEMA_VERSION,
        "run": {
            key: run[key]
            for key in (
                "record_id",
                "query_id",
                "trace_id",
                "run_id",
                "lookup_key",
                "lookup_mode",
                "config_fingerprint",
                "exported_at",
            )
            if run.get(key) is not None
        },
        "agents": [],
        "synthesis": {"disagreement": {}, "consensus": {}, "final_conclusion": {}},
        "data_sources": {
            "provider_trace": [],
            "llm_runs": [],
            "data_quality_status": None,
            "pipeline_stage_runs": [],
        },
        "coverage": {
            "sources": [],
            "not_recorded": list(COVERAGE_NOT_RECORDED),
            "notes": "All optional evidence was omitted to satisfy the response budget.",
        },
        "truncated": True,
        "truncation": {
            "marker": "truncated",
            "reason": "export_size_budget_exceeded",
            "max_chars": budget,
            "dropped": [
                {
                    "path": "optional_evidence",
                    "reason": "export_size_budget_exceeded",
                }
            ],
        },
    }
    size, markdown = _reconciled_response_size(
        minimal, output_format=output_format, include_markdown=include_markdown
    )
    if size > budget:
        raise ValueError("reasoning trace response budget is too small for the minimal envelope")
    if include_markdown and output_format == "json":
        minimal["markdown"] = markdown
    return minimal, markdown


def build_reasoning_trace_package(
    *,
    run_id: str,
    record_id: Optional[str] = None,
    query_id: Optional[str] = None,
    lookup_key: Optional[str] = None,
    lookup_mode: Optional[str] = None,
    stock_code: Optional[str] = None,
    stock_name: Optional[str] = None,
    market: Optional[str] = None,
    model: Optional[str] = None,
    started_at: Optional[str] = None,
    diagnostics: Optional[Mapping[str, Any]] = None,
    raw_result: Optional[Mapping[str, Any]] = None,
    context_snapshot: Optional[Mapping[str, Any]] = None,
    config: Any = None,
    max_chars: Optional[int] = None,
    include_markdown: bool = True,
    output_format: str = "json",
) -> ReasoningTraceExportResult:
    """Build a redacted reasoning-trace package from already-recorded sources.

    This function does not check the feature flag so unit tests can exercise
    packaging without mutating process config. Callers that gate on the flag
    should use :meth:`ReasoningTraceExportService.export_for_record`.
    """
    diagnostics_map = _as_mapping(diagnostics)
    raw_map = _as_mapping(raw_result)
    context_map = _as_mapping(context_snapshot)
    if not diagnostics_map and isinstance(context_map.get("diagnostics"), Mapping):
        diagnostics_map = _as_mapping(context_map["diagnostics"])

    if output_format not in {"json", "markdown"}:
        raise ValueError("format must be json or markdown")

    ledger = _LossLedger()
    agent_events = _as_list(diagnostics_map.get("agent_events"))
    agents, agent_stats = _group_agents_from_events(agent_events, ledger=ledger)
    synthesis = _extract_synthesis(raw_map, ledger=ledger)
    data_sources, source_stats = _extract_data_sources(
        diagnostics_map, context_map, ledger=ledger
    )
    quality_projection_loss, synthesis_projection_loss = _projection_loss_counts(
        raw_map, context_map
    )

    llm_runs = _as_list(diagnostics_map.get("llm_runs"))
    first_llm_model = None
    if llm_runs and isinstance(llm_runs[0], Mapping):
        first_llm_model = llm_runs[0].get("model")
    resolved_model = (
        model
        or raw_map.get("model_used")
        or diagnostics_map.get("model")
        or first_llm_model
    )

    run_meta = {
        "record_id": _clip_text(record_id, limit=128),
        "query_id": _clip_text(
            query_id or diagnostics_map.get("query_id"), limit=128
        ),
        "trace_id": _clip_text(diagnostics_map.get("trace_id"), limit=128),
        "run_id": _clip_text(run_id, limit=128) or "unknown",
        "lookup_key": _clip_text(lookup_key, limit=128),
        "lookup_mode": lookup_mode,
        "stock_code": _clip_text(
            stock_code or diagnostics_map.get("stock_code") or raw_map.get("code"),
            limit=32,
        ),
        "stock_name": _clip_text(stock_name or raw_map.get("name"), limit=120),
        "market": _clip_text(market, limit=32),
        "model": _clip_text(resolved_model, limit=120),
        "started_at": _clip_text(
            started_at or diagnostics_map.get("started_at"),
            limit=64,
        ),
        "config_fingerprint": build_config_fingerprint(config),
        "exported_at": datetime.now(timezone.utc).isoformat(),
    }

    # Capture-loss accounting. The current runtime writes an ``agent_events_capture``
    # marker, so its loss is provable. A legacy record has no marker: if it sits at
    # the historical 200-event cap we cannot prove whether earlier events were
    # dropped, so capture loss is reported as unknown rather than as zero.
    capture = _as_mapping(diagnostics_map.get("agent_events_capture"))
    has_capture_marker = bool(capture)
    capture_dropped = _nonnegative_int(capture.get("dropped_count")) or 0
    capture_original = _nonnegative_int(capture.get("original_count"))
    capture_loss_unknown = False
    if capture_original is None:
        # The legacy writer trimmed the list to exactly the cap, so a marker-less
        # record holding exactly ``DEFAULT_MAX_AGENT_EVENTS`` events is
        # indistinguishable from one that was trimmed: capture loss is unknown.
        # A marker-less record holding any other count cannot have come from the
        # capped writer, so its capture loss is provably zero.
        if not has_capture_marker and len(agent_events) == DEFAULT_MAX_AGENT_EVENTS:
            capture_loss_unknown = True
            capture_original = None
        else:
            capture_original = len(agent_events) + capture_dropped

    def coverage_entry(
        source: str,
        *,
        present: bool,
        original: Optional[int] = None,
        returned: Optional[int] = None,
        source_dropped: int = 0,
        export_dropped: int = 0,
        malformed: int = 0,
        source_truncated_unknown: bool = False,
        extra_reasons: Sequence[str] = (),
    ) -> Dict[str, Any]:
        reasons: List[str] = []
        if source_dropped:
            reasons.append("source_retention_limit")
        if export_dropped:
            reasons.append("export_projection_limit")
        if malformed:
            reasons.append("malformed_source_entries")
        for reason in extra_reasons:
            if reason not in reasons:
                reasons.append(reason)
        dropped = source_dropped + export_dropped + malformed
        return {
            "source": source,
            "supported": True,
            "present": present,
            "absent": not present,
            "source_truncated": source_dropped > 0,
            "source_truncated_unknown": source_truncated_unknown,
            "export_truncated": export_dropped > 0 or malformed > 0,
            "original_count": original,
            "returned_count": returned,
            # Capture-stage loss (upstream retention), kept separate from the
            # total gap between ``original_count`` and what the response carries.
            "source_dropped_count": None if source_truncated_unknown else source_dropped,
            "dropped_count": None if source_truncated_unknown else dropped,
            "reasons": reasons,
        }

    event_export_dropped = (
        agent_stats["event_cap_dropped"]
        + agent_stats["tool_cap_dropped"]
    )
    coverage_sources = [
        coverage_entry("run_meta", present=True, original=1, returned=1),
        coverage_entry(
            "diagnostics.agent_events",
            # Presence follows the projected payload, not the raw source list.
            present=agent_stats["returned_events"] > 0,
            original=capture_original,
            returned=agent_stats["returned_events"],
            source_dropped=capture_dropped,
            export_dropped=event_export_dropped,
            malformed=agent_stats["malformed_events"],
            source_truncated_unknown=capture_loss_unknown,
            extra_reasons=("legacy_capture_loss_unknown",) if capture_loss_unknown else (),
        ),
    ]
    source_to_output = {
        "diagnostics.provider_runs": "provider_trace",
        "diagnostics.llm_runs": "llm_runs",
        "diagnostics.pipeline_stage_runs": "pipeline_stage_runs",
    }
    for source, stats in source_stats.items():
        output_key = source_to_output[source]
        export_dropped = max(0, stats["original"] - DEFAULT_MAX_SOURCE_RUNS)
        coverage_sources.append(
            coverage_entry(
                source,
                present=bool(data_sources[output_key]),  # reconciled against final payload
                original=stats["original"],
                returned=stats["returned"],
                export_dropped=export_dropped,
                malformed=stats["malformed"],
            )
        )
    coverage_sources.extend(
        [
            # Presence must follow real projected content. An empty ``raw_result``
            # yields containers with no values and must report absent, not present.
            coverage_entry(
                "context.data_quality",
                present=_has_content(data_sources.get("data_quality_status")),
                export_dropped=quality_projection_loss,
            ),
            coverage_entry(
                "dashboard.synthesis",
                present=_has_content(synthesis),
                export_dropped=synthesis_projection_loss,
            ),
        ]
    )

    initial_drops: List[Dict[str, Any]] = []
    if capture_dropped:
        initial_drops.append(
            {
                "path": "diagnostics.agent_events",
                "reason": "source_retention_limit",
                "count": capture_dropped,
            }
        )
    for path, count, reason in (
        ("diagnostics.agent_events", agent_stats["event_cap_dropped"], "export_event_cap"),
        ("agents.tool_calls", agent_stats["tool_cap_dropped"], "export_tool_cap"),
        ("diagnostics.agent_events", agent_stats["malformed_events"], "malformed_source_entries"),
    ):
        if count:
            initial_drops.append({"path": path, "reason": reason, "count": count})
    for source, stats in source_stats.items():
        cap_dropped = max(0, stats["original"] - DEFAULT_MAX_SOURCE_RUNS)
        if cap_dropped:
            initial_drops.append(
                {"path": source, "reason": "export_source_cap", "count": cap_dropped}
            )
        if stats["malformed"]:
            initial_drops.append(
                {
                    "path": source,
                    "reason": "malformed_source_entries",
                    "count": stats["malformed"],
                }
            )
    for path, count in (
        ("context.data_quality.unsupported_fields", quality_projection_loss),
        ("dashboard.synthesis.unsupported_fields", synthesis_projection_loss),
    ):
        if count:
            initial_drops.append(
                {"path": path, "reason": "bounded_projection", "count": count}
            )
    # Value-level clips and unsupported items are losses too: fold the ledger in so
    # no bounded projection can shrink content without an explicit record.
    initial_drops.extend(ledger.as_drops())
    if capture_loss_unknown:
        initial_drops.append(
            {
                "path": "diagnostics.agent_events",
                "reason": "legacy_capture_loss_unknown",
            }
        )

    package: Dict[str, Any] = {
        "schema_version": SCHEMA_VERSION,
        "run": {k: v for k, v in run_meta.items() if v is not None},
        "agents": agents,
        "synthesis": synthesis,
        "data_sources": data_sources,
        "coverage": {
            "sources": coverage_sources,
            "not_recorded": list(COVERAGE_NOT_RECORDED),
            "notes": (
                "Exporter only includes fields already persisted by the analysis "
                "pipeline. Missing stages require agent-core recording work outside T03."
            ),
        },
        "truncated": bool(initial_drops),
    }

    budget = (
        min(MAX_MAX_EXPORT_CHARS, max(1_000, int(max_chars)))
        if max_chars is not None
        else resolve_max_export_chars(config)
    )
    if initial_drops:
        package["truncation"] = {
            "marker": "truncated",
            "reason": "source_or_export_truncation",
            "max_chars": budget,
            "dropped": initial_drops,
        }

    # Redaction and strict serialization happen before the final response budget.
    redacted = redact_export_payload(package)
    if not isinstance(redacted, dict):
        raise ValueError("reasoning trace redaction failed")
    # Opaque-token redaction cannot tell a 32-char UUID correlation id from a
    # bearer token. Restore only validated structural identities; evidence
    # payloads stay redacted.
    _restore_structural_identities(_as_mapping(redacted.get("run")), run_meta)
    _strict_json_dump(redacted)
    redacted, markdown = _apply_size_budget(
        redacted,
        max_chars=budget,
        output_format=output_format,
        include_markdown=include_markdown,
    )
    # The budget mutates only typed primitives; assert both negotiated payloads
    # remain standards-compliant and inside the hard boundary.
    _strict_json_dump(redacted)
    response_size, _ = _response_size(
        redacted,
        output_format=output_format,
        include_markdown=False if output_format == "json" else include_markdown,
    )
    if response_size > budget:
        raise ValueError("reasoning trace response exceeded its hard character budget")
    # Fail closed if coverage ever disagrees with what the response actually carries.
    _assert_coverage_invariants(redacted)

    return ReasoningTraceExportResult(
        package=redacted,
        markdown=markdown,
        truncated=bool(redacted.get("truncated")),
    )


class ReasoningTraceExportService:
    """Load history diagnostics and export a redacted reasoning-trace package."""

    def __init__(
        self,
        *,
        history_service: Any = None,
        config: Any = None,
    ) -> None:
        self._history_service = history_service
        self._config = config

    @property
    def history_service(self) -> Any:
        if self._history_service is None:
            from src.services.history_service import HistoryService

            self._history_service = HistoryService()
        return self._history_service

    @property
    def config(self) -> Any:
        if self._config is None:
            self._config = _resolve_runtime_config(None)
        return self._config

    def ensure_enabled(self) -> None:
        if not is_reasoning_trace_export_enabled(self.config):
            raise ReasoningTraceExportDisabled()

    def export_for_record(
        self,
        record_id: str,
        *,
        format: str = "json",
        include_markdown: bool = True,
    ) -> ReasoningTraceExportResult:
        """Export a reasoning trace for one analysis history record.

        Raises:
            ReasoningTraceExportDisabled: when the feature flag is off.
            ReasoningTraceNotFound: when the record cannot be resolved.
            ValueError: when stored diagnostic JSON is malformed.
        """
        self.ensure_enabled()
        record = self.history_service._resolve_record(record_id)
        if not record:
            raise ReasoningTraceNotFound(f"history record not found: {record_id}")

        parse = getattr(self.history_service, "_parse_diagnostic_json_field", None)
        if callable(parse):
            context_snapshot = parse(getattr(record, "context_snapshot", None), "context_snapshot")
            raw_result = parse(getattr(record, "raw_result", None), "raw_result")
        else:
            context_snapshot = getattr(record, "context_snapshot", None)
            raw_result = getattr(record, "raw_result", None)

        if isinstance(context_snapshot, str):
            context_snapshot = json.loads(context_snapshot) if context_snapshot.strip() else None
        if isinstance(raw_result, str):
            raw_result = json.loads(raw_result) if raw_result.strip() else None

        diagnostics = None
        if isinstance(context_snapshot, Mapping):
            diagnostics = context_snapshot.get("diagnostics")

        primary_id = getattr(record, "id", None)
        selected_record_id = str(primary_id) if primary_id is not None else str(record_id)
        selected_query_id = getattr(record, "query_id", None)
        diagnostic_trace_id = (
            diagnostics.get("trace_id") if isinstance(diagnostics, Mapping) else None
        )
        stable_run_id = str(
            diagnostic_trace_id
            or selected_query_id
            or f"history:{selected_record_id}"
        )
        # Report how the record was *actually* resolved, not how the request string
        # parses. ``_resolve_record`` tries the integer primary key first and falls
        # back to latest-by-query_id, so a numeric value that is not a primary key
        # can still resolve through the query fallback to a different record.
        requested_pk: Optional[int] = None
        try:
            requested_pk = int(record_id)
        except (TypeError, ValueError):
            requested_pk = None
        resolved_pk: Optional[int] = None
        if primary_id is not None:
            try:
                resolved_pk = int(primary_id)
            except (TypeError, ValueError):
                resolved_pk = None
        if requested_pk is not None and resolved_pk is not None and resolved_pk == requested_pk:
            lookup_mode = "primary_key"
        else:
            lookup_mode = "latest_by_query_id"

        started_at = getattr(record, "created_at", None)
        if hasattr(started_at, "isoformat"):
            started_at = started_at.isoformat()

        result = build_reasoning_trace_package(
            run_id=stable_run_id,
            record_id=selected_record_id,
            query_id=str(selected_query_id) if selected_query_id is not None else None,
            lookup_key=str(record_id),
            lookup_mode=lookup_mode,
            stock_code=getattr(record, "code", None),
            stock_name=getattr(record, "name", None),
            market=getattr(record, "market", None) or getattr(record, "region", None),
            model=getattr(record, "model_used", None),
            started_at=str(started_at) if started_at is not None else None,
            diagnostics=diagnostics if isinstance(diagnostics, Mapping) else None,
            raw_result=raw_result if isinstance(raw_result, Mapping) else None,
            context_snapshot=context_snapshot if isinstance(context_snapshot, Mapping) else None,
            config=self.config,
            include_markdown=include_markdown or format == "markdown",
            output_format=format,
        )
        return result
