"""Agent configuration field definitions."""

from typing import Any, Dict

from src.config import AGENT_CONTEXT_COMPRESSION_PROFILES, AGENT_MAX_STEPS_DEFAULT

AGENT_FIELD_DEFINITIONS: Dict[str, Dict[str, Any]] = {
    "AGENT_MODE": {
        "title": "Agent Mode",
        "description": "Enable ReAct Agent for stock analysis.",
        "category": "agent",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "false",
        "options": [],
        "validation": {},
        "display_order": 10,
        "help_key": "settings.agent.AGENT_MODE",
        "examples": [
            "AGENT_MODE=true",
            "AGENT_MODE=false",
        ],
        "docs": [
            {
                "label": "完整指南：Agent 配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "AGENT_GENERATION_BACKEND": {
        "title": "Ask-Stock Generation Method",
        "description": "Generation method used by the ask-stock assistant to generate replies and use tools.",
        "category": "agent",
        "data_type": "string",
        "ui_control": "select",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "auto",
        "options": [
            {"label": "Auto", "value": "auto"},
            {"label": "Default model settings", "value": "litellm"},
        ],
        "validation": {"enum": ["auto", "litellm"]},
        "display_order": 2,
        "help_key": "settings.agent.AGENT_GENERATION_BACKEND",
        "examples": [
            "AGENT_GENERATION_BACKEND=auto",
            "AGENT_GENERATION_BACKEND=litellm",
        ],
        "docs": [
            {
                "label": "LLM 配置指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md",
            },
        ],
        "warning_codes": [],
    },
    "AGENT_MAX_STEPS": {
        "title": "Agent Max Steps",
        "description": f"Maximum reasoning-step limit for Agent mode. At the default ({AGENT_MAX_STEPS_DEFAULT}), each sub-agent keeps its own preset. When raised above {AGENT_MAX_STEPS_DEFAULT}, all sub-agents adopt this value. When lowered below a sub-agent's preset, that sub-agent is capped at this value.",
        "category": "agent",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": str(AGENT_MAX_STEPS_DEFAULT),
        "options": [],
        "validation": {"min": 1, "max": 50},
        "display_order": 20,
        "help_key": "settings.agent.AGENT_MAX_STEPS",
        "examples": [
            f"AGENT_MAX_STEPS={AGENT_MAX_STEPS_DEFAULT}",
            "AGENT_MAX_STEPS=25",
        ],
        "docs": [
            {
                "label": "完整指南：Agent 配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "AGENT_SKILLS": {
        "title": "Agent Strategies",
        "description": "Comma-separated list of active agent strategy skills. Leave empty to use the primary default strategy skill declared in metadata (built-in default: bull_trend). When set to specific skills (not 'all'), scheduled tasks will automatically use the Agent pipeline.",
        "category": "agent",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "",
        "options": [],
        "validation": {},
        "display_order": 30,
        "help_key": "settings.agent.AGENT_SKILLS",
        "examples": [
            "AGENT_SKILLS=",
            "AGENT_SKILLS=bull_trend,mean_reversion",
            "AGENT_SKILLS=all",
        ],
        "docs": [
            {
                "label": "完整指南：Agent 配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "AGENT_SKILL_DIR": {
        "title": "Agent Strategy Dir",
        "description": "Directory containing agent strategy-skill definition files (YAML or SKILL.md bundles).",
        "category": "agent",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "strategies",
        "options": [],
        "validation": {},
        "display_order": 40,
        "help_key": "settings.agent.AGENT_SKILL_DIR",
        "examples": [
            "AGENT_SKILL_DIR=strategies",
            "AGENT_SKILL_DIR=my_strategies",
        ],
        "docs": [
            {
                "label": "完整指南：Agent 配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "AGENT_NL_ROUTING": {
        "title": "Agent NL Routing",
        "description": "Enable natural-language routing in bot dispatcher. When on, high-confidence stock queries in private chat (or @mentions) are routed to the agent even without an explicit command.",
        "category": "agent",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "false",
        "options": [],
        "validation": {},
        "display_order": 50,
        "help_key": "settings.agent.AGENT_NL_ROUTING",
        "examples": [
            "AGENT_NL_ROUTING=true",
            "AGENT_NL_ROUTING=false",
        ],
        "docs": [
            {
                "label": "完整指南：Agent 配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "AGENT_ARCH": {
        "title": "Agent Architecture",
        "description": "Agent execution architecture. 'single' uses the classic ReAct executor; 'multi' uses the orchestrator pipeline with specialised sub-agents.",
        "category": "agent",
        "data_type": "string",
        "ui_control": "select",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "single",
        "options": [
            {"label": "Single Agent", "value": "single"},
            {"label": "Multi Agent (Orchestrator)", "value": "multi"},
        ],
        "validation": {},
        "display_order": 60,
        "help_key": "settings.agent.AGENT_ARCH",
        "examples": [
            "AGENT_ARCH=single",
            "AGENT_ARCH=multi",
        ],
        "docs": [
            {
                "label": "完整指南：Agent 配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "AGENT_ORCHESTRATOR_MODE": {
        "title": "Orchestrator Mode",
        "description": "Pipeline mode when AGENT_ARCH=multi. 'quick' (tech→decision), 'standard' (tech→intel→decision), 'full' (tech→intel→risk→decision), 'specialist' (full + per-strategy specialist agents).",
        "category": "agent",
        "data_type": "string",
        "ui_control": "select",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "standard",
        "options": [
            {"label": "Quick", "value": "quick"},
            {"label": "Standard", "value": "standard"},
            {"label": "Full", "value": "full"},
            {"label": "Specialist", "value": "specialist"},
        ],
        "validation": {"enum": ["quick", "standard", "full", "specialist", "strategy", "skill"]},
        "display_order": 61,
        "help_key": "settings.agent.AGENT_ORCHESTRATOR_MODE",
        "examples": [
            "AGENT_ORCHESTRATOR_MODE=standard",
            "AGENT_ORCHESTRATOR_MODE=full",
        ],
        "docs": [
            {
                "label": "完整指南：Agent 配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "AGENT_ORCHESTRATOR_TIMEOUT_S": {
        "title": "Agent Timeout",
        "description": "Shared timeout budget in seconds for Agent execution. Single-agent runs use it as the overall ReAct loop budget; multi-agent mode uses it as the cooperative pipeline budget. Set to 0 to disable.",
        "category": "agent",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "600",
        "unit": "s",
        "options": [],
        "validation": {"min": 0, "max": 3600},
        "display_order": 62,
        "help_key": "settings.agent.AGENT_ORCHESTRATOR_TIMEOUT_S",
        "examples": [
            "AGENT_ORCHESTRATOR_TIMEOUT_S=600",
            "AGENT_ORCHESTRATOR_TIMEOUT_S=0",
        ],
        "docs": [
            {
                "label": "完整指南：Agent 配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "AGENT_RISK_OVERRIDE": {
        "title": "Risk Agent Override",
        "description": "Allow the risk agent to veto buy signals when critical risk flags are detected.",
        "category": "agent",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 63,
        "help_key": "settings.agent.AGENT_RISK_OVERRIDE",
        "examples": [
            "AGENT_RISK_OVERRIDE=true",
            "AGENT_RISK_OVERRIDE=false",
        ],
        "docs": [
            {
                "label": "完整指南：Agent 配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "AGENT_DEEP_RESEARCH_BUDGET": {
        "title": "Deep Research Token Budget",
        "description": "Maximum token budget for Deep Research planning, follow-up research, and final synthesis.",
        "category": "agent",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "30000",
        "options": [],
        "validation": {"min": 5000, "max": 100000},
        "display_order": 64,
        "help_key": "settings.agent.DEEP_RESEARCH",
        "examples": [
            "AGENT_DEEP_RESEARCH_BUDGET=30000",
            "AGENT_DEEP_RESEARCH_BUDGET=50000",
        ],
        "docs": [
            {
                "label": "完整指南：Agent 配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "AGENT_DEEP_RESEARCH_TIMEOUT": {
        "title": "Deep Research Timeout",
        "description": "Maximum seconds allowed for a Deep Research request before returning a timeout response.",
        "category": "agent",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "180",
        "options": [],
        "validation": {"min": 30, "max": 600},
        "display_order": 65,
        "help_key": "settings.agent.DEEP_RESEARCH",
        "examples": [
            "AGENT_DEEP_RESEARCH_TIMEOUT=180",
            "AGENT_DEEP_RESEARCH_TIMEOUT=300",
        ],
        "docs": [
            {
                "label": "完整指南：Agent 配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "AGENT_MEMORY_ENABLED": {
        "title": "Agent Memory",
        "description": "Enable the memory & calibration system. Tracks prediction accuracy and adjusts agent confidence over time.",
        "category": "agent",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "false",
        "options": [],
        "validation": {},
        "display_order": 66,
        "help_key": "settings.agent.AGENT_MEMORY_ENABLED",
        "examples": [
            "AGENT_MEMORY_ENABLED=true",
            "AGENT_MEMORY_ENABLED=false",
        ],
        "docs": [
            {
                "label": "完整指南：Agent 配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "AGENT_SKILL_AUTOWEIGHT": {
        "title": "Auto-Weight Strategies",
        "description": "Automatically weight strategy-skill opinions by their historical backtest performance.",
        "category": "agent",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 67,
        "help_key": "settings.agent.AGENT_SKILL_AUTOWEIGHT",
        "examples": [
            "AGENT_SKILL_AUTOWEIGHT=true",
            "AGENT_SKILL_AUTOWEIGHT=false",
        ],
        "docs": [
            {
                "label": "完整指南：Agent 配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "AGENT_SKILL_ROUTING": {
        "title": "Strategy Routing",
        "description": "Strategy-skill selection mode. 'auto' detects market regime and picks relevant skills; 'manual' uses AGENT_SKILLS list only.",
        "category": "agent",
        "data_type": "string",
        "ui_control": "select",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "auto",
        "options": [
            {"label": "Auto (Regime-based)", "value": "auto"},
            {"label": "Manual (Use AGENT_SKILLS)", "value": "manual"},
        ],
        "validation": {},
        "display_order": 68,
        "help_key": "settings.agent.AGENT_SKILL_ROUTING",
        "examples": [
            "AGENT_SKILL_ROUTING=auto",
            "AGENT_SKILL_ROUTING=manual",
        ],
        "docs": [
            {
                "label": "完整指南：Agent 配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "AGENT_CONTEXT_COMPRESSION_ENABLED": {
        "title": "Agent Context Compression",
        "description": "Enable rolling compression of visible Agent chat history. Default is off to preserve existing behavior.",
        "category": "agent",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "false",
        "options": [],
        "validation": {},
        "display_order": 72,
        "help_key": "settings.agent.context_compression",
        "examples": [
            "AGENT_CONTEXT_COMPRESSION_ENABLED=false",
            "AGENT_CONTEXT_COMPRESSION_ENABLED=true",
        ],
        "docs": [
            {
                "label": "LLM 配置指南：问股可见对话上下文压缩",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md#问股可见对话上下文压缩",
            },
            {
                "label": "完整指南：环境变量完整列表",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "AGENT_CONTEXT_COMPRESSION_PROFILE": {
        "title": "Context Compression Profile",
        "description": "Preset for visible chat history compression. Trigger/protected-turn fields can be left empty to follow the selected profile.",
        "category": "agent",
        "data_type": "string",
        "ui_control": "select",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "balanced",
        "options": [
            {"label": "成本优先", "value": "cost"},
            {"label": "均衡推荐", "value": "balanced"},
            {"label": "长上下文原文优先", "value": "long_context_raw_first"},
        ],
        "validation": {"enum": list(AGENT_CONTEXT_COMPRESSION_PROFILES.keys())},
        "display_order": 73,
        "help_key": "settings.agent.context_compression",
        "examples": [
            "AGENT_CONTEXT_COMPRESSION_PROFILE=balanced",
            "AGENT_CONTEXT_COMPRESSION_PROFILE=cost",
            "AGENT_CONTEXT_COMPRESSION_PROFILE=long_context_raw_first",
        ],
        "docs": [
            {
                "label": "LLM 配置指南：问股可见对话上下文压缩",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md#问股可见对话上下文压缩",
            },
            {
                "label": "完整指南：环境变量完整列表",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "AGENT_CONTEXT_COMPRESSION_TRIGGER_TOKENS": {
        "title": "Context Compression Trigger Tokens",
        "description": "Token threshold for visible chat history compression. Leave empty to follow the selected compression profile preset.",
        "category": "agent",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "",
        "options": [],
        "validation": {"min": 1000, "max": 200000},
        "display_order": 74,
        "help_key": "settings.agent.context_compression",
        "examples": [
            "AGENT_CONTEXT_COMPRESSION_TRIGGER_TOKENS=",
            "AGENT_CONTEXT_COMPRESSION_TRIGGER_TOKENS=12000",
        ],
        "docs": [
            {
                "label": "LLM 配置指南：问股可见对话上下文压缩",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md#问股可见对话上下文压缩",
            },
            {
                "label": "完整指南：环境变量完整列表",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "AGENT_CONTEXT_PROTECTED_TURNS": {
        "title": "Context Protected Turns",
        "description": "Recent user turns preserved verbatim during visible chat history compression. Leave empty to follow the selected compression profile preset.",
        "category": "agent",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "",
        "options": [],
        "validation": {"min": 1, "max": 20},
        "display_order": 75,
        "help_key": "settings.agent.context_compression",
        "examples": [
            "AGENT_CONTEXT_PROTECTED_TURNS=",
            "AGENT_CONTEXT_PROTECTED_TURNS=4",
        ],
        "docs": [
            {
                "label": "LLM 配置指南：问股可见对话上下文压缩",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md#问股可见对话上下文压缩",
            },
            {
                "label": "完整指南：环境变量完整列表",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "AGENT_EVENT_MONITOR_ENABLED": {
        "title": "Event Monitor",
        "description": "Enable background Event Monitor polling in schedule mode.",
        "category": "agent",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "false",
        "options": [],
        "validation": {},
        "display_order": 69,
        "help_key": "settings.agent.event_monitor",
        "examples": [
            "AGENT_EVENT_MONITOR_ENABLED=true",
            "AGENT_EVENT_MONITOR_INTERVAL_MINUTES=5",
        ],
        "docs": [
            {
                "label": "告警中心文档",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/alerts.md",
            },
        ],
        "warning_codes": [],
    },
    "AGENT_EVENT_MONITOR_INTERVAL_MINUTES": {
        "title": "Event Monitor Interval",
        "description": "Polling interval, in minutes, for background Event Monitor checks.",
        "category": "agent",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "5",
        "options": [],
        "validation": {"min": 1, "max": 1440},
        "display_order": 70,
        "help_key": "settings.agent.event_monitor",
        "examples": [
            "AGENT_EVENT_MONITOR_INTERVAL_MINUTES=5",
            "AGENT_EVENT_MONITOR_INTERVAL_MINUTES=15",
        ],
        "docs": [
            {
                "label": "告警中心文档",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/alerts.md",
            },
        ],
        "warning_codes": [],
    },
    "AGENT_EVENT_ALERT_RULES_JSON": {
        "title": "Event Alert Rules",
        "description": (
            "JSON array of Event Monitor rules loaded by schedule mode. "
            "Legacy JSON supports only price_cross, price_change_percent, and volume_spike. "
            "Technical indicator, watchlist, portfolio, and market light alert rules "
            "are available through the Alert API/Web center."
        ),
        "category": "agent",
        "data_type": "json",
        "ui_control": "textarea",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "",
        "options": [],
        "validation": {},
        "display_order": 71,
        "help_key": "settings.agent.EVENT_ALERT_RULES_JSON",
        "examples": [
            'AGENT_EVENT_ALERT_RULES_JSON=[{"alert_type":"price_cross","stock_code":"600519","direction":"above","price":1800}]',
            'AGENT_EVENT_ALERT_RULES_JSON=[{"alert_type":"volume_spike","stock_code":"300750","multiplier":2.5}]',
        ],
        "docs": [
            {
                "label": "告警中心文档",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/alerts.md",
            },
        ],
        "warning_codes": ["legacy_json_only_basic_rules"],
    },
}
