"""AI model configuration field definitions."""

from typing import Any, Dict

AI_MODEL_FIELD_DEFINITIONS: Dict[str, Dict[str, Any]] = {
    # ------------------------------------------------------------------
    # AI Model – LiteLLM unified config
    # ------------------------------------------------------------------
    "GENERATION_BACKEND": {
        "title": "Analysis Generation Method",
        "description": "Generation method used by stock analysis, market reviews, and regular text generation.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "select",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "litellm",
        "options": [
            {"label": "Default model settings", "value": "litellm"},
            {"label": "Codex CLI (experimental)", "value": "codex_cli"},
            {"label": "Claude Code CLI (experimental)", "value": "claude_code_cli"},
            {"label": "OpenCode CLI (experimental)", "value": "opencode_cli"},
        ],
        "validation": {"enum": ["litellm", "codex_cli", "claude_code_cli", "opencode_cli"]},
        "display_order": 0,
        "help_key": "settings.ai_model.GENERATION_BACKEND",
        "examples": [
            "GENERATION_BACKEND=litellm",
            "GENERATION_BACKEND=codex_cli",
            "GENERATION_BACKEND=claude_code_cli",
            "GENERATION_BACKEND=opencode_cli",
        ],
        "docs": [
            {
                "label": "LLM 配置指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md",
            },
        ],
        "warning_codes": [],
    },
    "OPENCODE_CLI_MODEL": {
        "title": "OpenCode CLI Model",
        "description": "Optional model override passed to OpenCode CLI when GENERATION_BACKEND=opencode_cli. Leave empty to use OpenCode's default model.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "",
        "placeholder": "optional provider/model override",
        "validation": {"pattern": r"^$|^[^\s|<>;`$]+$"},
        "contract": {
            "requirement": "optional",
            "visible_when": [
                {"key": "GENERATION_BACKEND", "operator": "equals", "value": "opencode_cli"},
            ],
        },
        "display_order": 1,
        "help_key": "settings.ai_model.OPENCODE_CLI_MODEL",
        "examples": [
            "OPENCODE_CLI_MODEL=provider/model",
            "OPENCODE_CLI_MODEL=opencode/model-name",
        ],
        "docs": [
            {
                "label": "LLM 配置指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md",
            },
        ],
        "warning_codes": [],
    },
    "GENERATION_FALLBACK_BACKEND": {
        "title": "Fallback Generation Method",
        "description": "Backend-level fallback method. Empty disables backend fallback; litellm can be used as fallback for local CLI generation backends.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "select",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "litellm",
        "options": [
            {"label": "Disabled", "value": ""},
            {"label": "Default model settings", "value": "litellm"},
        ],
        "validation": {"enum": ["", "litellm"]},
        "display_order": 0,
        "help_key": "settings.ai_model.GENERATION_FALLBACK_BACKEND",
        "examples": ["GENERATION_FALLBACK_BACKEND=litellm", "GENERATION_FALLBACK_BACKEND="],
        "docs": [
            {
                "label": "LLM 配置指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md",
            },
        ],
        "warning_codes": [],
    },
    "GENERATION_BACKEND_TIMEOUT_SECONDS": {
        "title": "Generation Backend Timeout",
        "description": "Maximum seconds allowed for one generation backend call. Applies to local CLI backends; LiteLLM behavior is unchanged.",
        "category": "ai_model",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "300",
        "options": [],
        "validation": {"min": 1, "max": 3600},
        "display_order": 1,
        "help_key": "settings.ai_model.GENERATION_BACKEND_TIMEOUT_SECONDS",
        "examples": ["GENERATION_BACKEND_TIMEOUT_SECONDS=300"],
        "docs": [
            {
                "label": "LLM 配置指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md",
            },
        ],
        "warning_codes": [],
    },
    "GENERATION_BACKEND_MAX_OUTPUT_BYTES": {
        "title": "Generation Backend Max Output Bytes",
        "description": (
            "Maximum captured diagnostic stdout/stderr and final-response bytes "
            "for one local CLI backend call."
        ),
        "category": "ai_model",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "1048576",
        "options": [],
        "validation": {"min": 1, "max": 33554432},
        "display_order": 1,
        "help_key": "settings.ai_model.GENERATION_BACKEND_MAX_OUTPUT_BYTES",
        "examples": ["GENERATION_BACKEND_MAX_OUTPUT_BYTES=1048576"],
        "docs": [
            {
                "label": "LLM 配置指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md",
            },
        ],
        "warning_codes": [],
    },
    "GENERATION_BACKEND_MAX_CONCURRENCY": {
        "title": "Generation Backend Max Concurrency",
        "description": "Global generation backend concurrency cap. Local CLI effective concurrency also respects LOCAL_CLI_BACKEND_MAX_CONCURRENCY.",
        "category": "ai_model",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "1",
        "options": [],
        "validation": {"min": 1, "max": 16},
        "display_order": 1,
        "help_key": "settings.ai_model.GENERATION_BACKEND_MAX_CONCURRENCY",
        "examples": ["GENERATION_BACKEND_MAX_CONCURRENCY=1"],
        "docs": [
            {
                "label": "LLM 配置指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md",
            },
        ],
        "warning_codes": [],
    },
    "LOCAL_CLI_BACKEND_MAX_CONCURRENCY": {
        "title": "Local CLI Backend Max Concurrency",
        "description": "Local CLI backend concurrency cap. Effective local CLI concurrency is the minimum of this value and GENERATION_BACKEND_MAX_CONCURRENCY.",
        "category": "ai_model",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "1",
        "options": [],
        "validation": {"min": 1, "max": 4},
        "display_order": 1,
        "help_key": "settings.ai_model.LOCAL_CLI_BACKEND_MAX_CONCURRENCY",
        "examples": ["LOCAL_CLI_BACKEND_MAX_CONCURRENCY=1"],
        "docs": [
            {
                "label": "LLM 配置指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md",
            },
        ],
        "warning_codes": [],
    },
    "LITELLM_MODEL": {
        "title": "Primary Model",
        "description": "Primary model in provider/model format (e.g. gemini/gemini-3.1-pro-preview, deepseek/deepseek-v4-flash, anthropic/claude-sonnet-4-6). If empty, it is auto-inferred from available API keys or channel declarations.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 1,
        "help_key": "settings.ai_model.LITELLM_MODEL",
        "examples": [
            "LITELLM_MODEL=deepseek/deepseek-v4-flash",
            "LITELLM_MODEL=gemini/gemini-3.1-pro-preview",
            "LITELLM_MODEL=ollama/qwen3:8b",
        ],
        "docs": [
            {
                "label": "LLM 配置指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md",
            },
            {
                "label": "完整指南：AI 模型配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#ai-模型配置",
            },
            {
                "label": "LiteLLM Providers（官方）",
                "href": "https://docs.litellm.ai/docs/providers",
            },
            {
                "label": "LiteLLM OpenAI-compatible（官方）",
                "href": "https://docs.litellm.ai/docs/providers/openai_compatible",
            },
            {
                "label": "LiteLLM model_list（官方）",
                "href": "https://docs.litellm.ai/docs/proxy/configs#the-model_list-key",
            },
        ],
        "warning_codes": ["provider_prefix_required"],
    },
    "AGENT_LITELLM_MODEL": {
        "title": "Agent Primary Model",
        "description": "Optional Agent-only primary model in provider/model format. When empty, Agent inherits the primary model. Bare model names are normalized to openai/<model>.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 2,
        "help_key": "settings.ai_model.AGENT_LITELLM_MODEL",
        "examples": [
            "AGENT_LITELLM_MODEL=deepseek/deepseek-v4-pro",
            "AGENT_LITELLM_MODEL=gemini/gemini-3.1-pro-preview",
        ],
        "docs": [
            {
                "label": "LLM 配置指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md",
            },
            {
                "label": "完整指南：AI 模型配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#ai-模型配置",
            },
        ],
        "warning_codes": ["inherits_primary_when_empty"],
    },
    "VISION_MODEL": {
        "title": "Vision Model",
        "description": "Optional model used for image understanding. When empty, vision tasks follow the configured default behavior.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 3,
        "help_key": "settings.ai_model.VISION_MODEL",
        "examples": ["VISION_MODEL=openai/gpt-5.4-mini"],
        "docs": [
            {
                "label": "LLM 配置指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md",
            },
        ],
        "warning_codes": ["vision_model_must_be_available"],
    },
    "LITELLM_FALLBACK_MODELS": {
        "title": "Fallback Models",
        "description": "Comma-separated fallback models tried when the primary model fails (e.g. anthropic/claude-sonnet-4-6,openai/gpt-5.4-mini). Useful for cross-provider redundancy.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 2,
        "help_key": "settings.ai_model.LITELLM_FALLBACK_MODELS",
        "examples": [
            "LITELLM_FALLBACK_MODELS=deepseek/deepseek-v4-pro,gemini/gemini-3-flash-preview",
            "LITELLM_FALLBACK_MODELS=openai/gpt-5.4-mini",
        ],
        "docs": [
            {
                "label": "LLM 配置指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md",
            },
            {
                "label": "完整指南：AI 模型配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#ai-模型配置",
            },
            {
                "label": "LiteLLM Providers（官方）",
                "href": "https://docs.litellm.ai/docs/providers",
            },
            {
                "label": "LiteLLM config（官方）",
                "href": "https://docs.litellm.ai/docs/proxy/configs",
            },
        ],
        "warning_codes": ["fallback_models_must_be_available"],
    },
    # ------------------------------------------------------------------
    # AI Model – Multi-channel LLM configuration
    # ------------------------------------------------------------------
    "LLM_CONFIG_MODE": {
        "title": "Model config mode",
        "description": "Which model configuration source is active. 'auto' keeps the historical precedence (YAML > Channels > legacy keys); 'channels'/'yaml'/'legacy' force a single source so the active configuration is unambiguous.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "select",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "auto",
        "options": [
            {"label": "Auto (compatible)", "value": "auto"},
            {"label": "Web Channels (recommended)", "value": "channels"},
            {"label": "YAML (advanced)", "value": "yaml"},
            {"label": "Legacy provider keys (compatibility)", "value": "legacy"},
        ],
        "validation": {"enum": ["auto", "channels", "yaml", "legacy"]},
        "display_order": 2,
        "help_key": "settings.ai_model.LLM_CONFIG_MODE",
        "examples": [
            "LLM_CONFIG_MODE=auto",
            "LLM_CONFIG_MODE=channels",
        ],
        "docs": [
            {
                "label": "LLM 配置指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md",
            },
        ],
        "warning_codes": [],
    },
    "LITELLM_CONFIG": {
        "title": "Advanced Model Routing Config",
        "description": "Path to an advanced model routing YAML file (expert use). When valid/parseable and yields a model_list, it takes priority over channels and legacy keys; otherwise channels/legacy are used as fallback.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 3,
        "help_key": "settings.ai_model.LITELLM_CONFIG",
        "examples": [
            "LITELLM_CONFIG=./litellm_config.yaml",
        ],
        "docs": [
            {
                "label": "LLM 配置指南：YAML 模式",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md#方式三litellm-原生-yaml-配置适合专家或复杂路由",
            },
            {
                "label": "LiteLLM proxy config（官方）",
                "href": "https://docs.litellm.ai/docs/proxy/configs",
            },
        ],
        "warning_codes": ["yaml_config_overrides_channel_editor"],
    },
    "LLM_CHANNELS": {
        "title": "LLM Channels",
        "description": "Channel names (comma-separated). Managed by the channel editor above.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 4,
        "help_key": "settings.ai_model.LLM_CHANNELS",
        "examples": [
            "LLM_CHANNELS=deepseek,aihubmix",
            "LLM_DEEPSEEK_BASE_URL=https://api.deepseek.com",
            "LLM_DEEPSEEK_API_KEY=sk-xxxx",
            "LLM_DEEPSEEK_MODELS=deepseek-v4-flash,deepseek-v4-pro",
        ],
        "docs": [
            {
                "label": "LLM 配置指南：渠道模式",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md#方式二渠道channels模式配置适合进阶多模型",
            },
            {
                "label": "LLM 服务商配置速查",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/llm-providers.md",
            },
            {
                "label": "LiteLLM OpenAI-compatible（官方）",
                "href": "https://docs.litellm.ai/docs/providers/openai_compatible",
            },
        ],
        "warning_codes": ["channels_override_legacy_keys"],
    },
    "LLM_TEMPERATURE": {
        "title": "Temperature",
        "description": "Unified sampling temperature for all LLM calls. Range [0.0, 2.0], default 0.7.",
        "category": "ai_model",
        "data_type": "number",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "0.7",
        "options": [],
        "validation": {"min": 0.0, "max": 2.0},
        "display_order": 5,
        "help_key": "settings.ai_model.LLM_TEMPERATURE",
        "examples": [
            "LLM_TEMPERATURE=0.2",
            "LLM_TEMPERATURE=0.7",
        ],
        "docs": [
            {
                "label": "完整指南：AI 模型配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#ai-模型配置",
            },
        ],
        "warning_codes": [],
    },
    "LLM_PROMPT_CACHE_TELEMETRY_ENABLED": {
        "title": "Prompt Cache Telemetry",
        "description": "Records provider prompt-cache usage telemetry and normalized cache diagnostics when providers return cache usage fields. This does not enable or disable provider implicit cache.",
        "category": "ai_model",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 6,
        "help_key": "settings.ai_model.LLM_PROMPT_CACHE_TELEMETRY_ENABLED",
        "examples": [
            "LLM_PROMPT_CACHE_TELEMETRY_ENABLED=true",
            "LLM_PROMPT_CACHE_TELEMETRY_ENABLED=false",
        ],
        "docs": [
            {
                "label": "LLM 配置指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md",
            },
        ],
        "warning_codes": [],
    },
    "LLM_PROMPT_CACHE_HINTS_ENABLED": {
        "title": "Prompt Cache Hints",
        "description": "Allows the project to send verified provider-specific prompt-cache hints such as prompt_cache_key or cache_control. Unknown providers and unverified routes remain telemetry-only.",
        "category": "ai_model",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "false",
        "options": [],
        "validation": {},
        "display_order": 7,
        "help_key": "settings.ai_model.LLM_PROMPT_CACHE_HINTS_ENABLED",
        "examples": [
            "LLM_PROMPT_CACHE_HINTS_ENABLED=false",
        ],
        "docs": [
            {
                "label": "LLM 配置指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md",
            },
        ],
        "warning_codes": [],
    },
    "LLM_PROMPT_CACHE_DIAGNOSTICS_LEVEL": {
        "title": "Prompt Cache Diagnostics",
        "description": "Controls non-sensitive prompt-cache capability and hint decision diagnostics. Values: off, basic, debug.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "select",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "off",
        "options": [
            {"value": "off", "label": "Off"},
            {"value": "basic", "label": "Basic"},
            {"value": "debug", "label": "Debug"},
        ],
        "validation": {"enum": ["off", "basic", "debug"]},
        "display_order": 8,
        "help_key": "settings.ai_model.LLM_PROMPT_CACHE_DIAGNOSTICS_LEVEL",
        "examples": [
            "LLM_PROMPT_CACHE_DIAGNOSTICS_LEVEL=off",
            "LLM_PROMPT_CACHE_DIAGNOSTICS_LEVEL=basic",
        ],
        "docs": [
            {
                "label": "LLM 配置指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md",
            },
        ],
        "warning_codes": [],
    },
    "LLM_USAGE_HMAC_SECRET": {
        "title": "LLM Usage HMAC Secret",
        "description": "Optional deployment-scoped secret for LLM usage telemetry prompt/message HMAC. Leave empty to use a local generated secret file. If set, use a high-entropy random value and do not commit it to version control.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 9,
        "help_key": "settings.ai_model.LLM_USAGE_HMAC_SECRET",
        "examples": [
            "LLM_USAGE_HMAC_SECRET=<64-char random hex from openssl rand -hex 32>",
        ],
        "docs": [
            {
                "label": "LLM 配置指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md",
            },
        ],
        "warning_codes": ["secret_value"],
    },
    "LLM_USAGE_HMAC_KEY_VERSION": {
        "title": "LLM Usage HMAC Key Version",
        "description": "Version label for the LLM usage telemetry HMAC key. Change it when rotating LLM_USAGE_HMAC_SECRET.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "local-v1",
        "options": [],
        "validation": {},
        "display_order": 10,
        "help_key": "settings.ai_model.LLM_USAGE_HMAC_KEY_VERSION",
        "examples": [
            "LLM_USAGE_HMAC_KEY_VERSION=prod-2026-06",
        ],
        "docs": [
            {
                "label": "LLM 配置指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md",
            },
        ],
        "warning_codes": [],
    },
    "AIHUBMIX_KEY": {
        "title": "AIHubmix Key",
        "description": "AIHubmix API key for multiple model families. Automatically uses aihubmix.com/v1 unless a different Base URL is configured. Get a key at https://aihubmix.com/.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 5,
        "help_key": "settings.ai_model.provider_keys",
        "examples": [
            "AIHUBMIX_KEY=sk-xxxx",
        ],
        "docs": [
            {
                "label": "LLM 配置指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md",
            },
            {
                "label": "LLM 服务商配置速查",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/llm-providers.md",
            },
        ],
        "warning_codes": ["secret_value"],
    },
    "ANSPIRE_LLM_ENABLED": {
        "title": "Anspire LLM Enabled",
        "description": "Use ANSPIRE_API_KEYS as an OpenAI-compatible Anspire LLM key when no higher-priority LLM channel or OpenAI-compatible key is configured.",
        "category": "ai_model",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 6,
    },
    "ANSPIRE_LLM_BASE_URL": {
        "title": "Anspire LLM Base URL",
        "description": "Anspire OpenAI-compatible gateway. Default: https://open-gateway.anspire.cn/v6; global endpoint: https://open-gateway.anspire.ai/v6.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "https://open-gateway.anspire.cn/v6",
        "options": [],
        "validation": {"format": "url"},
        "display_order": 7,
    },
    "ANSPIRE_LLM_MODEL": {
        "title": "Anspire LLM Model",
        "description": "Default model used when ANSPIRE_API_KEYS enables the Anspire LLM gateway without an explicit LITELLM_MODEL.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "Doubao-Seed-2.0-lite",
        "options": [],
        "validation": {},
        "display_order": 8,
    },
    # ------------------------------------------------------------------
    # AI Model – DeepSeek official (independent from OpenAI-compatible)
    # ------------------------------------------------------------------
    "DEEPSEEK_API_KEY": {
        "title": "DeepSeek API Key",
        "description": "Official DeepSeek API key (from https://platform.deepseek.com). For compatibility, a key set alone still auto-infers deepseek/deepseek-chat and logs a deprecation warning; new configs should migrate to deepseek/deepseek-v4-flash. Also works in multi-channel mode.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 6,
        "help_key": "settings.ai_model.provider_keys",
        "examples": [
            "DEEPSEEK_API_KEY=sk-xxxx",
            "LITELLM_MODEL=deepseek/deepseek-v4-flash",
        ],
        "docs": [
            {
                "label": "LLM 配置指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md",
            },
            {
                "label": "LLM 服务商配置速查",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/llm-providers.md",
            },
        ],
        "warning_codes": ["secret_value"],
    },
    "DEEPSEEK_API_KEYS": {
        "title": "DeepSeek API Keys (Multi)",
        "description": "Comma-separated DeepSeek API keys for load balancing. Takes priority over DEEPSEEK_API_KEY.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"multi_value": True, "delimiter": ","},
        "display_order": 7,
    },
}

AI_MODEL_LEGACY_FIELD_DEFINITIONS: Dict[str, Dict[str, Any]] = {
    "GEMINI_API_KEY": {
        "title": "Gemini API Key",
        "description": "Single API key for Gemini service (from https://aistudio.google.com).",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 10,
        "help_key": "settings.ai_model.provider_keys",
        "examples": [
            "GEMINI_API_KEY=your_gemini_api_key",
            "LITELLM_MODEL=gemini/gemini-3.1-pro-preview",
        ],
        "docs": [
            {
                "label": "LLM 配置指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md",
            },
            {
                "label": "LLM 服务商配置速查",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/llm-providers.md",
            },
        ],
        "warning_codes": ["secret_value"],
    },
    "GEMINI_API_KEYS": {
        "title": "Gemini API Keys (Multi)",
        "description": "Comma-separated Gemini API keys for load balancing. Takes priority over GEMINI_API_KEY.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"multi_value": True, "delimiter": ","},
        "display_order": 11,
    },
    "GEMINI_MODEL": {
        "title": "Gemini Model",
        "description": "Gemini model name.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "gemini-3.1-pro-preview",
        "options": [],
        "validation": {},
        "display_order": 20,
    },
    "GEMINI_MODEL_FALLBACK": {
        "title": "Gemini Fallback Model",
        "description": "Fallback Gemini model name (used when LITELLM_FALLBACK_MODELS is not set and primary is Gemini).",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "gemini-3-flash-preview",
        "options": [],
        "validation": {},
        "display_order": 21,
    },
    "GEMINI_TEMPERATURE": {
        "title": "Gemini Temperature",
        "description": "Temperature in range [0.0, 2.0].",
        "category": "ai_model",
        "data_type": "number",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "0.7",
        "options": [],
        "validation": {"min": 0.0, "max": 2.0},
        "display_order": 30,
    },
    "OPENAI_API_KEY": {
        "title": "OpenAI API Key",
        "description": "API key for OpenAI-compatible service.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 40,
        "help_key": "settings.ai_model.provider_keys",
        "examples": [
            "OPENAI_API_KEY=sk-xxxx",
            "OPENAI_BASE_URL=https://api.example.com/v1",
            "LITELLM_MODEL=openai/gpt-5.5",
        ],
        "docs": [
            {
                "label": "LLM 配置指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md",
            },
            {
                "label": "LLM 服务商配置速查",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/llm-providers.md",
            },
        ],
        "warning_codes": ["secret_value"],
    },
    "OPENAI_API_KEYS": {
        "title": "OpenAI API Keys (Multi)",
        "description": "Comma-separated OpenAI-compatible API keys for load balancing. Takes priority over AIHUBMIX_KEY and OPENAI_API_KEY.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"multi_value": True, "delimiter": ","},
        "display_order": 41,
    },
    "OPENAI_BASE_URL": {
        "title": "OpenAI Base URL",
        "description": "Base URL for OpenAI-compatible endpoint.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 50,
        "help_key": "settings.ai_model.OPENAI_BASE_URL",
        "examples": [
            "OPENAI_BASE_URL=https://api.openai.com/v1",
            "OPENAI_BASE_URL=https://api.example.com/v1",
        ],
        "docs": [
            {
                "label": "LLM 配置指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md",
            },
            {
                "label": "LLM 服务商配置速查",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/llm-providers.md",
            },
        ],
        "warning_codes": ["base_url_must_match_provider"],
    },
    "OPENAI_MODEL": {
        "title": "OpenAI Model",
        "description": "Model name for OpenAI-compatible endpoint.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "gpt-5.5",
        "options": [],
        "validation": {},
        "display_order": 60,
    },
    "OPENAI_VISION_MODEL": {
        "title": "OpenAI Vision Model",
        "description": "Model for image extraction (some APIs e.g. DeepSeek lack vision). Leave empty to use OPENAI_MODEL.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 61,
    },
    "OPENAI_TEMPERATURE": {
        "title": "OpenAI Temperature",
        "description": "Temperature for OpenAI-compatible models in range [0.0, 2.0].",
        "category": "ai_model",
        "data_type": "number",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "0.7",
        "options": [],
        "validation": {"min": 0.0, "max": 2.0},
        "display_order": 62,
    },
    "ANTHROPIC_API_KEY": {
        "title": "Anthropic API Key",
        "description": "Anthropic Claude API key (from https://console.anthropic.com).",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 35,
        "help_key": "settings.ai_model.provider_keys",
        "examples": [
            "ANTHROPIC_API_KEY=sk-ant-xxxx",
            "LITELLM_MODEL=anthropic/claude-sonnet-4-6",
        ],
        "docs": [
            {
                "label": "LLM 配置指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/LLM_CONFIG_GUIDE.md",
            },
            {
                "label": "LLM 服务商配置速查",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/llm-providers.md",
            },
        ],
        "warning_codes": ["secret_value"],
    },
    "ANTHROPIC_API_KEYS": {
        "title": "Anthropic API Keys (Multi)",
        "description": "Comma-separated Anthropic API keys for load balancing. Takes priority over ANTHROPIC_API_KEY.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"multi_value": True, "delimiter": ","},
        "display_order": 35,
    },
    "ANTHROPIC_MODEL": {
        "title": "Anthropic Model",
        "description": "Claude 模型名称（如 claude-sonnet-4-6）。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "claude-sonnet-4-6",
        "options": [],
        "validation": {},
        "display_order": 36,
    },
    "ANTHROPIC_TEMPERATURE": {
        "title": "Anthropic Temperature",
        "description": "温度参数，范围 [0.0, 1.0]。",
        "category": "ai_model",
        "data_type": "number",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "0.7",
        "options": [],
        "validation": {"min": 0.0, "max": 1.0},
        "display_order": 37,
    },
    "ANTHROPIC_MAX_TOKENS": {
        "title": "Anthropic Max Tokens",
        "description": "Anthropic API 响应最大 token 数（默认 8192）。",
        "category": "ai_model",
        "data_type": "number",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "8192",
        "options": [],
        "validation": {"min": 256, "max": 8192},
        "display_order": 38,
    },
}
