"""Data-source configuration field definitions."""

from typing import Any, Dict

from src.config import DEFAULT_ALPHASIFT_INSTALL_SPEC

DATA_SOURCE_FIELD_DEFINITIONS: Dict[str, Dict[str, Any]] = {
    "TUSHARE_TOKEN": {
        "title": "Tushare Token",
        "description": "Token for Tushare Pro API.",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 10,
        "help_key": "settings.data_source.TUSHARE_TOKEN",
        "examples": [
            "TUSHARE_TOKEN=your_tushare_token",
        ],
        "docs": [
            {
                "label": "Tushare 股票列表指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/TUSHARE_STOCK_LIST_GUIDE.md",
            },
            {
                "label": "完整指南：环境变量完整列表",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": ["secret_value"],
    },
    "TICKFLOW_API_KEY": {
        "title": "TickFlow API Key",
        "description": "API key for optional TickFlow A-share daily K-lines, realtime quotes, stock list/name lookup, and market review enhancement. Permission failures fail open to existing providers.",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 15,
    },
    "TICKFLOW_PRIORITY": {
        "title": "TickFlow Daily K-line Priority",
        "description": "Priority for TickFlow daily K-line fetcher. Lower numbers are tried earlier; realtime quote order is controlled separately by REALTIME_SOURCE_PRIORITY.",
        "category": "data_source",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "2",
        "options": [],
        "validation": {"min": 0, "max": 99},
        "display_order": 16,
    },
    "TICKFLOW_KLINE_ADJUST": {
        "title": "TickFlow K-line Adjust",
        "description": "Adjustment mode for TickFlow daily K-lines. Default none preserves the existing unadjusted technical-indicator baseline.",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "select",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "none",
        "options": ["none", "forward", "backward", "forward_additive", "backward_additive"],
        "validation": {},
        "display_order": 17,
    },
    "TICKFLOW_BATCH_DAILY_ENABLED": {
        "title": "TickFlow Batch Daily Enabled",
        "description": "Enable TickFlow batch daily K-line prefetch when the current plan allows it. Permission failures fail open and fall back to per-stock providers.",
        "category": "data_source",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 18,
    },
    "TICKFLOW_BATCH_SIZE": {
        "title": "TickFlow Batch Size",
        "description": "Maximum symbols per TickFlow batch request for daily K-lines and realtime quotes.",
        "category": "data_source",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "100",
        "options": [],
        "validation": {"min": 1, "max": 500},
        "display_order": 19,
    },
    "STOCK_INDEX_REMOTE_UPDATE_ENABLED": {
        "title": "Remote Stock Index Updates",
        "description": "Automatically refresh the local stock autocomplete index from the built-in GitHub main source.",
        "category": "data_source",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 16,
        "help_key": "settings.data_source.stock_index_remote",
        "examples": [
            "STOCK_INDEX_REMOTE_UPDATE_ENABLED=true",
            "STOCK_INDEX_REMOTE_UPDATE_ENABLED=false",
        ],
        "docs": [
            {
                "label": "Tushare 股票列表指南",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/TUSHARE_STOCK_LIST_GUIDE.md",
            },
        ],
        "warning_codes": [],
    },
    "ALPHASIFT_ENABLED": {
        "title": "AlphaSift Screening",
        "description": "Enable the built-in AlphaSift stock screening tab. Disabled by default. This switch only affects the AlphaSift screening path; it does not migrate, sanitize, or clear existing LLM/runtime fields in `.env`.",
        "category": "data_source",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "false",
        "options": [],
        "validation": {},
        "display_order": 17,
        "help_key": "settings.data_source.ALPHASIFT_ENABLED",
        "examples": [
            "ALPHASIFT_ENABLED=false",
            "ALPHASIFT_ENABLED=true",
        ],
        "docs": [
            {
                "label": "LiteLLM Providers（官方）",
                "href": "https://docs.litellm.ai/docs/providers",
            },
            {
                "label": "LiteLLM OpenAI-compatible（官方）",
                "href": "https://docs.litellm.ai/docs/providers/openai_compatible",
            },
            {
                "label": "OpenAI 请求与鉴权（官方）",
                "href": "https://platform.openai.com/docs/api-reference/authentication",
            },
            {
                "label": "AlphaSift 集成说明",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/alphasift-integration.md",
            },
        ],
    },
    "ALPHASIFT_INSTALL_SPEC": {
        "title": "AlphaSift Install Spec",
        "description": "Pinned AlphaSift pip source used for explicit repair installs and source verification. It is not used for normal runtime calls after startup dependency installation; runtime compatibility is built from StockPulse's resolved LLM/runtime context.",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": DEFAULT_ALPHASIFT_INSTALL_SPEC,
        "options": [],
        "validation": {},
        "display_order": 18,
        "help_key": "settings.data_source.ALPHASIFT_INSTALL_SPEC",
        "examples": [
            f"ALPHASIFT_INSTALL_SPEC={DEFAULT_ALPHASIFT_INSTALL_SPEC}",
        ],
        "docs": [
            {
                "label": "requirements.txt（版本与依赖边界）",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/requirements.txt",
            },
            {
                "label": "AlphaSift 集成说明",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/alphasift-integration.md",
            },
        ],
    },
    "REALTIME_SOURCE_PRIORITY": {
        "title": "Realtime Source Priority",
        "description": "Ordered priority for realtime quote providers; earlier entries are tried first.",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "tencent,akshare_sina,efinance,akshare_em",
        # No allowed_values on purpose: stored aliases (e.g. akshare_qq) and
        # custom sources must keep validating; the UI only offers the catalog.
        "options": [
            {"label": "tencent", "value": "tencent"},
            {"label": "akshare_sina", "value": "akshare_sina"},
            {"label": "efinance", "value": "efinance"},
            {"label": "akshare_em", "value": "akshare_em"},
            {"label": "tushare", "value": "tushare"},
            {"label": "tickflow", "value": "tickflow"},
        ],
        "validation": {"multi_value": True, "delimiter": ",", "ordered": True},
        "display_order": 20,
        "help_key": "settings.data_source.REALTIME_SOURCE_PRIORITY",
        "examples": [
            "REALTIME_SOURCE_PRIORITY=tencent,akshare_sina,efinance,akshare_em",
        ],
        "docs": [
            {
                "label": "完整指南：数据源配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#数据源配置",
            },
        ],
        "warning_codes": ["provider_priority_order"],
    },
    "ENABLE_REALTIME_TECHNICAL_INDICATORS": {
        "title": "Realtime Technical Indicators",
        "description": "Use intraday realtime price for MA5/MA10/MA20 and trend analysis (Issue #234). Disable to use yesterday close.",
        "category": "data_source",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 21,
        "help_key": "settings.data_source.realtime_quotes",
        "examples": [
            "ENABLE_REALTIME_TECHNICAL_INDICATORS=true",
            "ENABLE_REALTIME_TECHNICAL_INDICATORS=false",
        ],
        "docs": [
            {
                "label": "完整指南：数据源配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#数据源配置",
            },
        ],
        "warning_codes": [],
    },
    "ANSPIRE_API_KEYS": {
        "title": "Anspire API Keys",
        "description": "Comma-separated Anspire Open API keys. Used by Anspire Search and, by default, the Anspire OpenAI-compatible LLM gateway.",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"multi_value": True, "delimiter": ","},
        "display_order": 22,
        "help_key": "settings.data_source.search_api_keys",
        "examples": [
            "ANSPIRE_API_KEYS=key1,key2",
        ],
        "docs": [
            {
                "label": "完整指南：搜索服务配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#搜索服务配置",
            },
        ],
        "warning_codes": ["secret_value", "comma_separated_keys"],
    },
    "TAVILY_API_KEYS": {
        "title": "Tavily API Keys",
        "description": "Comma-separated Tavily API keys.",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"multi_value": True, "delimiter": ","},
        "display_order": 30,
        "help_key": "settings.data_source.search_api_keys",
        "examples": [
            "TAVILY_API_KEYS=tvly-xxxx",
            "TAVILY_API_KEYS=tvly-key-1,tvly-key-2",
        ],
        "docs": [
            {
                "label": "完整指南：搜索服务配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#搜索服务配置",
            },
        ],
        "warning_codes": ["secret_value", "comma_separated_keys"],
    },
    "SERPAPI_API_KEYS": {
        "title": "SerpAPI Keys",
        "description": "Comma-separated SerpAPI keys.",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"multi_value": True, "delimiter": ","},
        "display_order": 40,
    },
    "BRAVE_API_KEYS": {
        "title": "Brave API Keys",
        "description": "Comma-separated Brave Search API keys.",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"multi_value": True, "delimiter": ","},
        "display_order": 50,
    },
    "BOCHA_API_KEYS": {
        "title": "Bocha API Keys",
        "description": "Comma-separated Bocha Search API keys.",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"multi_value": True, "delimiter": ","},
        "display_order": 51,
    },
    "MINIMAX_API_KEYS": {
        "title": "MiniMax API Key",
        "description": "MiniMax API key (search priority: Bocha > Tavily > Brave > SerpAPI > MiniMax > SearXNG).",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"multi_value": True, "delimiter": ","},
        "display_order": 53,
    },
    "SEARXNG_BASE_URLS": {
        "title": "SearXNG Base URLs",
        "description": "Comma-separated SearXNG instance URLs (self-hosted, no quota). Enable format: json in settings.yml.",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {
            "multi_value": True,
            "delimiter": ",",
            "item_type": "url",
            "allowed_schemes": ["http", "https"],
        },
        "display_order": 52,
        "help_key": "settings.data_source.SEARXNG_BASE_URLS",
        "examples": [
            "SEARXNG_BASE_URLS=https://search.example.com",
            "SEARXNG_PUBLIC_INSTANCES_ENABLED=false",
        ],
        "docs": [
            {
                "label": "完整指南：搜索服务配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#搜索服务配置",
            },
        ],
        "warning_codes": ["requires_json_format"],
    },
    "SEARXNG_PUBLIC_INSTANCES_ENABLED": {
        "title": "SearXNG Public Instances",
        "description": "Auto-discover public SearXNG instances from searx.space when SEARXNG_BASE_URLS is empty. Default: true; set false to disable.",
        "category": "data_source",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 53,
    },
    "ENABLE_REALTIME_QUOTE": {
        "title": "Enable Realtime Quote",
        "description": "Enable realtime market quotes. Disable to only use historical close prices.",
        "category": "data_source",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 22,
        "help_key": "settings.data_source.realtime_quotes",
        "examples": [
            "ENABLE_REALTIME_QUOTE=true",
            "ENABLE_REALTIME_QUOTE=false",
        ],
        "docs": [
            {
                "label": "完整指南：数据源配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#数据源配置",
            },
        ],
        "warning_codes": [],
    },
    "ENABLE_CHIP_DISTRIBUTION": {
        "title": "Enable Chip Distribution",
        "description": "Enable chip distribution analysis. May be unstable; recommended to disable on cloud deployments.",
        "category": "data_source",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 23,
        "help_key": "settings.data_source.ENABLE_CHIP_DISTRIBUTION",
        "examples": [
            "ENABLE_CHIP_DISTRIBUTION=true",
            "ENABLE_CHIP_DISTRIBUTION=false",
        ],
        "docs": [
            {
                "label": "完整指南：数据源配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#数据源配置",
            },
        ],
        "warning_codes": ["cloud_deployments_may_disable"],
    },
    "NEWS_MAX_AGE_DAYS": {
        "title": "News Max Age (Days)",
        "description": "Maximum age of news in days. Older articles are excluded from analysis context.",
        "category": "data_source",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "3",
        "options": [],
        "validation": {"min": 1, "max": 30},
        "display_order": 60,
        "help_key": "settings.data_source.news_window",
        "examples": [
            "NEWS_MAX_AGE_DAYS=3",
            "NEWS_STRATEGY_PROFILE=short",
        ],
        "docs": [
            {
                "label": "完整指南：环境变量完整列表",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "NEWS_STRATEGY_PROFILE": {
        "title": "News Strategy Profile",
        "description": "News window profile: ultra_short(1d), short(3d), medium(7d), long(30d). Effective window = min(profile, NEWS_MAX_AGE_DAYS).",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "select",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "short",
        "options": ["ultra_short", "short", "medium", "long"],
        "validation": {"enum": ["ultra_short", "short", "medium", "long"]},
        "display_order": 61,
        "help_key": "settings.data_source.news_window",
        "examples": [
            "NEWS_STRATEGY_PROFILE=short",
            "NEWS_MAX_AGE_DAYS=3",
        ],
        "docs": [
            {
                "label": "完整指南：环境变量完整列表",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "BIAS_THRESHOLD": {
        "title": "Bias Threshold (%)",
        "description": "Deviation threshold from MA5 (%). Exceeding this triggers 'do not chase' warning. Strong trend stocks auto-widen to 1.5x.",
        "category": "data_source",
        "data_type": "number",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "5.0",
        "options": [],
        "validation": {"min": 0.0, "max": 50.0},
        "display_order": 62,
    },
    "PYTDX_HOST": {
        "title": "Pytdx Host",
        "description": "Tongdaxin data server IP. Used with PYTDX_PORT. Overrides built-in defaults.",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 55,
    },
    "PYTDX_PORT": {
        "title": "Pytdx Port",
        "description": "Tongdaxin data server port (e.g. 7709). Used with PYTDX_HOST.",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 56,
    },
    "PYTDX_SERVERS": {
        "title": "Pytdx Servers",
        "description": "Comma-separated ip:port (e.g. 192.168.1.1:7709,10.0.0.1:7709). Overrides PYTDX_HOST+PYTDX_PORT.",
        "category": "data_source",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 57,
    },
}
