"""System configuration field definitions."""

from typing import Any, Dict

SYSTEM_FIELD_DEFINITIONS: Dict[str, Dict[str, Any]] = {
    "SCHEDULE_TIME": {
        "title": "Schedule Time",
        "description": "Daily schedule time in HH:MM format.",
        "category": "system",
        "data_type": "time",
        "ui_control": "time",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "18:00",
        "options": [],
        "validation": {"pattern": r"^([01]\d|2[0-3]):[0-5]\d$"},
        "display_order": 10,
        "help_key": "settings.system.schedule",
        "examples": [
            "SCHEDULE_TIME=18:00",
            "SCHEDULE_ENABLED=true",
            "SCHEDULE_RUN_IMMEDIATELY=false",
        ],
        "docs": [
            {
                "label": "完整指南：其他配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#其他配置",
            },
        ],
        "warning_codes": ["local_timezone"],
    },
    "SCHEDULE_TIMES": {
        "title": "Schedule Times",
        "description": "Comma-separated daily schedule times in HH:MM format. Falls back to SCHEDULE_TIME when empty.",
        "category": "system",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "",
        "options": [],
        "validation": {"pattern": r"^\s*(?:(?:[01]\d|2[0-3]):[0-5]\d\s*(?:,\s*(?:[01]\d|2[0-3]):[0-5]\d\s*)*)?$"},
        "display_order": 11,
        "help_key": "settings.system.schedule",
        "examples": [
            "SCHEDULE_TIMES=09:20,12:30,15:10,18:00",
            "SCHEDULE_TIME=18:00",
            "SCHEDULE_ENABLED=true",
        ],
        "docs": [
            {
                "label": "Full guide: configuration",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#其他配置",
            },
        ],
        "warning_codes": ["local_timezone"],
    },
    "HTTP_PROXY": {
        "title": "HTTP Proxy",
        "description": "Optional HTTP proxy endpoint.",
        "category": "system",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 20,
        "help_key": "settings.system.HTTP_PROXY",
        "examples": [
            "HTTP_PROXY=http://127.0.0.1:7890",
            "HTTPS_PROXY=http://127.0.0.1:7890",
        ],
        "docs": [
            {
                "label": "完整指南：环境变量完整列表",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": ["network_scope"],
    },
    "LOG_LEVEL": {
        "title": "Log Level",
        "description": "Application log level.",
        "category": "system",
        "data_type": "string",
        "ui_control": "select",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "INFO",
        "options": ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
        "validation": {"enum": ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]},
        "display_order": 30,
        "help_key": "settings.system.LOG_LEVEL",
        "examples": [
            "LOG_LEVEL=INFO",
            "LOG_LEVEL=DEBUG",
        ],
        "docs": [
            {
                "label": "完整指南：环境变量完整列表",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": ["restart_required"],
    },
    "LOG_DIR": {
        "title": "Log Directory",
        "description": "Directory for application logs. The runtime user or container must be able to write to this path.",
        "category": "system",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "./logs",
        "options": [],
        "validation": {},
        "display_order": 31,
        "help_key": "settings.system.LOG_DIR",
        "examples": [
            "LOG_DIR=./logs",
            "LOG_DIR=/app/logs",
        ],
        "docs": [
            {
                "label": "完整指南：环境变量完整列表",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": ["restart_required", "path_must_be_writable"],
    },
    "WEBUI_ENABLED": {
        "title": "Web UI Enabled",
        "description": "Startup-time compatibility flag for default WebUI/API service mode. Saving this setting does not start or stop the current process.",
        "category": "system",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "false",
        "options": [],
        "validation": {},
        "display_order": 37,
        "help_key": "settings.system.WEBUI_ENABLED",
        "examples": [
            "WEBUI_ENABLED=false",
            "WEBUI_ENABLED=true",
        ],
        "docs": [
            {
                "label": "完整指南：WebUI 与 API",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#webui-与-api-服务",
            },
            {
                "label": "云服务器访问 WebUI",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/deploy-webui-cloud.md",
            },
        ],
        "warning_codes": ["restart_required"],
    },
    "WEBUI_AUTO_BUILD": {
        "title": "Web UI Auto Build",
        "description": "Build or verify the Web frontend assets before backend WebUI startup. Disable only when assets are prebuilt.",
        "category": "system",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 38,
        "help_key": "settings.system.WEBUI_AUTO_BUILD",
        "examples": [
            "WEBUI_AUTO_BUILD=true",
            "WEBUI_AUTO_BUILD=false",
        ],
        "docs": [
            {
                "label": "完整指南：WebUI 与 API",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#webui-与-api-服务",
            },
            {
                "label": "云服务器访问 WebUI",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/deploy-webui-cloud.md",
            },
        ],
        "warning_codes": ["restart_required", "requires_built_web_assets"],
    },
    "WEBUI_HOST": {
        "title": "Web UI Host",
        "description": "Host address for Web UI service binding.",
        "category": "system",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "127.0.0.1",
        "options": [],
        "validation": {},
        "display_order": 39,
        "help_key": "settings.system.WEBUI_HOST",
        "examples": [
            "WEBUI_HOST=127.0.0.1",
            "WEBUI_HOST=0.0.0.0",
        ],
        "docs": [
            {
                "label": "云服务器访问 WebUI",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/deploy-webui-cloud.md",
            },
            {
                "label": "完整指南：WebUI 与 API",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#webui-与-api-服务",
            },
        ],
        "warning_codes": ["public_bind_requires_auth", "restart_required"],
    },
    "WEBUI_PORT": {
        "title": "Web UI Port",
        "description": "Port for Web UI service.",
        "category": "system",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "8000",
        "options": [],
        "validation": {"min": 1, "max": 65535},
        "display_order": 40,
        "help_key": "settings.system.WEBUI_PORT",
        "examples": [
            "WEBUI_PORT=8000",
            "WEBUI_PORT=18000",
        ],
        "docs": [
            {
                "label": "云服务器访问 WebUI",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/deploy-webui-cloud.md",
            },
            {
                "label": "完整指南：WebUI 与 API",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#webui-与-api-服务",
            },
        ],
        "warning_codes": ["port_mapping_required", "restart_required"],
    },
    "RUN_IMMEDIATELY": {
        "title": "Run Immediately",
        "description": "Whether to run analysis immediately on startup (non-schedule mode).",
        "category": "system",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 45,
        "help_key": "settings.system.RUN_IMMEDIATELY",
        "examples": [
            "RUN_IMMEDIATELY=true",
            "RUN_IMMEDIATELY=false",
        ],
        "docs": [
            {
                "label": "完整指南：其他配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#其他配置",
            },
        ],
        "warning_codes": ["restart_required"],
    },
    "SCHEDULE_ENABLED": {
        "title": "Schedule Enabled",
        "description": "Enable daily scheduled analysis run.",
        "category": "system",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "false",
        "options": [],
        "validation": {},
        "display_order": 8,
        "help_key": "settings.system.schedule",
        "examples": [
            "SCHEDULE_ENABLED=true",
            "SCHEDULE_TIME=18:00",
            "SCHEDULE_RUN_IMMEDIATELY=false",
        ],
        "docs": [
            {
                "label": "完整指南：其他配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#其他配置",
            },
        ],
        "warning_codes": ["restart_required"],
    },
    "ADMIN_AUTH_ENABLED": {
        "title": "Admin Auth Enabled",
        "description": "Enable password protection for Web UI. The first visit initializes the admin password.",
        "category": "system",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": False,
        "default_value": "false",
        "options": [],
        "validation": {},
        "display_order": 41,
        "help_key": "settings.system.ADMIN_AUTH_ENABLED",
        "examples": [
            "ADMIN_AUTH_ENABLED=true",
            "python -m src.auth reset_password",
        ],
        "docs": [
            {
                "label": "完整指南：其他配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#其他配置",
            },
            {
                "label": "云服务器访问 WebUI",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/deploy-webui-cloud.md",
            },
        ],
        "warning_codes": ["public_webui_requires_auth", "auth_settings_endpoint_required"],
    },
    "TRUST_X_FORWARDED_FOR": {
        "title": "Trust X-Forwarded-For",
        "description": "Use X-Forwarded-For as the client IP behind one trusted reverse proxy.",
        "category": "system",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "false",
        "options": [],
        "validation": {},
        "display_order": 42,
        "help_key": "settings.system.TRUST_X_FORWARDED_FOR",
        "examples": [
            "TRUST_X_FORWARDED_FOR=false",
            "TRUST_X_FORWARDED_FOR=true",
        ],
        "docs": [
            {
                "label": "完整指南：其他配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#其他配置",
            },
            {
                "label": "云服务器访问 WebUI",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/deploy-webui-cloud.md",
            },
        ],
        "warning_codes": ["trusted_proxy_only"],
    },
    "SCHEDULE_RUN_IMMEDIATELY": {
        "title": "Schedule Run Immediately",
        "description": "Whether to run one analysis immediately on startup in schedule mode.",
        "category": "system",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 11,
        "help_key": "settings.system.schedule",
        "examples": [
            "SCHEDULE_RUN_IMMEDIATELY=true",
            "SCHEDULE_RUN_IMMEDIATELY=false",
        ],
        "docs": [
            {
                "label": "完整指南：其他配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#其他配置",
            },
        ],
        "warning_codes": ["restart_required"],
    },
    "TRADING_DAY_CHECK_ENABLED": {
        "title": "Trading Day Check",
        "description": "Skip analysis on non-trading days. Set to false or use --force-run to override.",
        "category": "system",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 12,
        "help_key": "settings.system.TRADING_DAY_CHECK_ENABLED",
        "examples": [
            "TRADING_DAY_CHECK_ENABLED=true",
            "TRADING_DAY_CHECK_ENABLED=false",
        ],
        "docs": [
            {
                "label": "完整指南：其他配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#其他配置",
            },
        ],
        "warning_codes": ["force_run_override"],
    },
    "MARKET_REVIEW_ENABLED": {
        "title": "Market Review Enabled",
        "description": "Enable market overview/review in analysis reports.",
        "category": "system",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 46,
        "help_key": "settings.system.market_review",
        "examples": [
            "MARKET_REVIEW_ENABLED=true",
            "MARKET_REVIEW_REGION=cn",
        ],
        "docs": [
            {
                "label": "完整指南：环境变量完整列表",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "DAILY_MARKET_CONTEXT_ENABLED": {
        "title": "Daily Market Context Enabled",
        "description": "Inject daily market context into stock-analysis prompts and apply conservative decision guardrails.",
        "category": "system",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 47,
        "help_key": "settings.system.market_review",
        "examples": [
            "DAILY_MARKET_CONTEXT_ENABLED=true",
            "DAILY_MARKET_CONTEXT_ENABLED=false",
        ],
        "docs": [
            {
                "label": "完整指南：环境变量完整列表",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "MARKET_REVIEW_REGION": {
        "title": "Market Review Region",
        "description": "Market region for review: cn (A-shares), hk (Hong Kong), us (US stocks), jp (Japan), kr (Korea), or both (all markets).",
        "category": "system",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "cn",
        "options": ["cn", "hk", "us", "jp", "kr", "both"],
        "validation": {"allowed_values": ["cn", "hk", "us", "jp", "kr", "both"], "multi_value": True, "delimiter": ","},
        "display_order": 48,
        "help_key": "settings.system.market_review",
        "examples": [
            "MARKET_REVIEW_REGION=cn",
            "MARKET_REVIEW_REGION=jp",
            "MARKET_REVIEW_REGION=both",
        ],
        "docs": [
            {
                "label": "完整指南：环境变量完整列表",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "MARKET_REVIEW_COLOR_SCHEME": {
        "title": "Market Review Color Scheme",
        "description": "Index change color style in market-review tables: green_up (green for gains, red for losses) or red_up (red for gains, green for losses).",
        "category": "system",
        "data_type": "string",
        "ui_control": "select",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "green_up",
        "options": [
            {"label": "Green Up / Red Down", "value": "green_up"},
            {"label": "Red Up / Green Down", "value": "red_up"},
        ],
        "validation": {"enum": ["green_up", "red_up"]},
        "display_order": 49,
        "help_key": "settings.system.market_review",
        "examples": [
            "MARKET_REVIEW_COLOR_SCHEME=green_up",
            "MARKET_REVIEW_COLOR_SCHEME=red_up",
        ],
        "docs": [
            {
                "label": "完整指南：环境变量完整列表",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "MAX_WORKERS": {
        "title": "Max Workers",
        "description": "Maximum concurrent analysis threads. Keep low to avoid API rate limits.",
        "category": "system",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "3",
        "options": [],
        "validation": {"min": 1, "max": 20},
        "display_order": 50,
        "help_key": "settings.system.MAX_WORKERS",
        "examples": [
            "MAX_WORKERS=3",
            "MAX_WORKERS=5",
        ],
        "docs": [
            {
                "label": "完整指南：环境变量完整列表",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "ANALYSIS_DELAY": {
        "title": "Analysis Delay",
        "description": "Delay in seconds between individual stock analyses (for API rate limiting).",
        "category": "system",
        "data_type": "number",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "0",
        "options": [],
        "validation": {"min": 0, "max": 60},
        "display_order": 51,
        "help_key": "settings.system.ANALYSIS_DELAY",
        "examples": [
            "ANALYSIS_DELAY=0",
            "ANALYSIS_DELAY=5",
        ],
        "docs": [
            {
                "label": "完整指南：环境变量完整列表",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
    "SAVE_CONTEXT_SNAPSHOT": {
        "title": "Save Context Snapshot",
        "description": "Persist the full analysis_history.context_snapshot for history/API/Web transparency. Disable only to stop storing snapshots; it does not disable AnalysisContextPack prompt summaries during the current run.",
        "category": "system",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "true",
        "options": [],
        "validation": {},
        "display_order": 52,
        "help_key": "settings.system.SAVE_CONTEXT_SNAPSHOT",
        "examples": [
            "SAVE_CONTEXT_SNAPSHOT=true",
            "SAVE_CONTEXT_SNAPSHOT=false",
            "python main.py --no-context-snapshot",
        ],
        "docs": [
            {
                "label": "AnalysisContextPack P6 文档、迁移与回滚",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/analysis-context-pack.md#p6-文档迁移与回滚",
            },
            {
                "label": "完整指南：其他配置",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#其他配置",
            },
        ],
        "warning_codes": [],
    },
    "DEBUG": {
        "title": "Debug Mode",
        "description": "Enable debug mode with verbose logging.",
        "category": "system",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "false",
        "options": [],
        "validation": {},
        "display_order": 55,
        "help_key": "settings.system.DEBUG",
        "examples": [
            "DEBUG=true",
            "DEBUG=false",
        ],
        "docs": [
            {
                "label": "完整指南：环境变量完整列表",
                "href": "https://github.com/SiinXu/stock-pulse-ai/blob/main/docs/full-guide.md#环境变量完整列表",
            },
        ],
        "warning_codes": [],
    },
}
