# -*- coding: utf-8 -*-
"""Shared text sanitizers for logs, diagnostics, and API payloads."""

from __future__ import annotations

import sys
import types

from . import log_safe as _log_safe
from . import redaction as _redaction
from . import text as _text
from .log_safe import (
    _collapse_log_exception_summaries,
    _collapse_redacted_exception_diagnostics,
    _safe_log_context_fields,
    log_safe_exception,
    safe_before_sleep_log,
)
from .redaction import (
    _EXACT_REDACTION_VALUE_LIMIT,
    _EXCEPTION_REDACTION_FAIL_CLOSED_LIMIT,
    _EXCEPTION_REDACTION_PROVENANCE,
    _ExceptionRedactionMarker,
    _ExceptionRedactionSnapshot,
    _ExceptionRedactionValue,
    _ExceptionRedactionValues,
    _NormalizedRedactionValues,
    _REDACTED,
    _SAFE_EXCEPTION_CHAIN_LIMIT,
    _SAFE_EXCEPTION_PART_MAX_LENGTH,
    _SAFE_EXCEPTION_SUMMARY_MAX_LENGTH,
    _SAFE_RENDER_FAILURE,
    _UNSAFE_EXCEPTION_ACCESS,
    _bounded_render_failure,
    _matching_exception_snapshot,
    _normalize_redaction_values,
    _redact_exact_values,
    _safe_exception_diagnostic_source,
    _safe_next_exception,
    _safe_string,
    _safe_structured_string,
    has_matching_exception_snapshot,
)
from .text import (
    _BEARER_PATTERN,
    _FOLDED_FIELD_LINE_PATTERN,
    _OPAQUE_TOKEN_PATTERN,
    _ORDINARY_DIAGNOSTIC_FIELD_PATTERN,
    _PUBLIC_AUTHORIZATION_PUNCTUATION,
    _PUBLIC_DIAGNOSTIC_FIELD_PATTERN,
    _PUBLIC_REDACTED_URL_VALUES,
    _PUBLIC_REDACTION_FIELD_VALUES,
    _SAFE_SET_COOKIE_ATTRIBUTE_PATTERN,
    _SENSITIVE_COMPACT_KEY_PATTERN,
    _SENSITIVE_COMPACT_KEY_PHRASES,
    _SENSITIVE_FIELD_SEPARATOR_PATTERN,
    _SENSITIVE_KEY_PARTS,
    _SENSITIVE_KEY_PHRASES,
    _TEXT_FIELD_BOUNDARY_LOOKAHEAD,
    _TEXT_FIELD_KEY_PART_LIMIT,
    _TEXT_FIELD_KEY_PATTERN,
    _TEXT_FIELD_START_PATTERN,
    _TOKEN_LIKE_PATTERN,
    _URL_COMPONENT_DECODE_LIMIT,
    _URL_CREDENTIALS_PATTERN,
    _URL_PATTERN,
    _URL_USERINFO_REDACTION,
    _classify_text_field_match,
    _decode_url_component,
    _encoded_field_key_start,
    _first_unquoted_semicolon,
    _has_sensitive_phrase,
    _has_sensitive_url_assignment,
    _has_sensitive_url_params,
    _is_complete_public_redaction_field_value,
    _is_http_url_redacted_at_boundary,
    _is_next_diagnostic_field,
    _is_public_redacted_url_boundary,
    _is_sensitive_mapping_key,
    _is_sensitive_mapping_key_text,
    _is_sensitive_url,
    _is_structured_field_suffix,
    _is_text_field_key_joiner,
    _is_verified_field_boundary,
    _is_webhook_url,
    _mapping_key_parts,
    _next_sensitive_text_field_match,
    _outer_quote_token,
    _redact_common_secret_patterns,
    _redact_mapping_key,
    _redact_sensitive_data_value,
    _redact_sensitive_field_spans,
    _redact_sensitive_url_match,
    _redact_serialized_json_text,
    _safe_set_cookie_suffix,
    _sanitize_decision_signal_payload_values,
    _sensitive_field_end,
    _sensitive_text_field_kind,
    _sensitive_text_field_kind_at,
    _sensitive_text_field_starts_at,
    _starts_with_public_redaction_marker,
    _text_field_key_starts,
    exception_chain_redaction_values,
    is_sensitive_key,
    redact_sensitive_data,
    redact_sensitive_mapping,
    redact_sensitive_text,
    safe_exception_type_name,
    sanitize_decision_signal_payload,
    sanitize_decision_signal_text,
    sanitize_diagnostic_text,
    sanitize_exception_chain,
    sanitize_sensitive_text,
)

# Map re-exported names to their defining submodule so monkeypatch.setattr
# on this package continues to affect the implementation modules.
_OWNER_MODULES = {
    "log_safe": _log_safe,
    "redaction": _redaction,
    "text": _text,
}
_NAME_OWNERS = {
    "_BEARER_PATTERN": "text",
    "_EXACT_REDACTION_VALUE_LIMIT": "redaction",
    "_EXCEPTION_REDACTION_FAIL_CLOSED_LIMIT": "redaction",
    "_EXCEPTION_REDACTION_PROVENANCE": "redaction",
    "_ExceptionRedactionMarker": "redaction",
    "_ExceptionRedactionSnapshot": "redaction",
    "_ExceptionRedactionValue": "redaction",
    "_ExceptionRedactionValues": "redaction",
    "_FOLDED_FIELD_LINE_PATTERN": "text",
    "_NormalizedRedactionValues": "redaction",
    "_OPAQUE_TOKEN_PATTERN": "text",
    "_ORDINARY_DIAGNOSTIC_FIELD_PATTERN": "text",
    "_PUBLIC_AUTHORIZATION_PUNCTUATION": "text",
    "_PUBLIC_DIAGNOSTIC_FIELD_PATTERN": "text",
    "_PUBLIC_REDACTED_URL_VALUES": "text",
    "_PUBLIC_REDACTION_FIELD_VALUES": "text",
    "_REDACTED": "redaction",
    "_SAFE_EXCEPTION_CHAIN_LIMIT": "redaction",
    "_SAFE_EXCEPTION_PART_MAX_LENGTH": "redaction",
    "_SAFE_EXCEPTION_SUMMARY_MAX_LENGTH": "redaction",
    "_SAFE_RENDER_FAILURE": "redaction",
    "_SAFE_SET_COOKIE_ATTRIBUTE_PATTERN": "text",
    "_SENSITIVE_COMPACT_KEY_PATTERN": "text",
    "_SENSITIVE_COMPACT_KEY_PHRASES": "text",
    "_SENSITIVE_FIELD_SEPARATOR_PATTERN": "text",
    "_SENSITIVE_KEY_PARTS": "text",
    "_SENSITIVE_KEY_PHRASES": "text",
    "_TEXT_FIELD_BOUNDARY_LOOKAHEAD": "text",
    "_TEXT_FIELD_KEY_PART_LIMIT": "text",
    "_TEXT_FIELD_KEY_PATTERN": "text",
    "_TEXT_FIELD_START_PATTERN": "text",
    "_TOKEN_LIKE_PATTERN": "text",
    "_UNSAFE_EXCEPTION_ACCESS": "redaction",
    "_URL_COMPONENT_DECODE_LIMIT": "text",
    "_URL_CREDENTIALS_PATTERN": "text",
    "_URL_PATTERN": "text",
    "_URL_USERINFO_REDACTION": "text",
    "_bounded_render_failure": "redaction",
    "_classify_text_field_match": "text",
    "_collapse_log_exception_summaries": "log_safe",
    "_collapse_redacted_exception_diagnostics": "log_safe",
    "_decode_url_component": "text",
    "_encoded_field_key_start": "text",
    "_first_unquoted_semicolon": "text",
    "_has_sensitive_phrase": "text",
    "_has_sensitive_url_assignment": "text",
    "_has_sensitive_url_params": "text",
    "_is_complete_public_redaction_field_value": "text",
    "_is_http_url_redacted_at_boundary": "text",
    "_is_next_diagnostic_field": "text",
    "_is_public_redacted_url_boundary": "text",
    "_is_sensitive_mapping_key": "text",
    "_is_sensitive_mapping_key_text": "text",
    "_is_sensitive_url": "text",
    "_is_structured_field_suffix": "text",
    "_is_text_field_key_joiner": "text",
    "_is_verified_field_boundary": "text",
    "_is_webhook_url": "text",
    "_mapping_key_parts": "text",
    "_matching_exception_snapshot": "redaction",
    "_next_sensitive_text_field_match": "text",
    "_normalize_redaction_values": "redaction",
    "_outer_quote_token": "text",
    "_redact_common_secret_patterns": "text",
    "_redact_exact_values": "redaction",
    "_redact_mapping_key": "text",
    "_redact_sensitive_data_value": "text",
    "_redact_sensitive_field_spans": "text",
    "_redact_sensitive_url_match": "text",
    "_redact_serialized_json_text": "text",
    "_safe_exception_diagnostic_source": "redaction",
    "_safe_log_context_fields": "log_safe",
    "_safe_next_exception": "redaction",
    "_safe_set_cookie_suffix": "text",
    "_safe_string": "redaction",
    "_safe_structured_string": "redaction",
    "_sanitize_decision_signal_payload_values": "text",
    "_sensitive_field_end": "text",
    "_sensitive_text_field_kind": "text",
    "_sensitive_text_field_kind_at": "text",
    "_sensitive_text_field_starts_at": "text",
    "_starts_with_public_redaction_marker": "text",
    "_text_field_key_starts": "text",
    "exception_chain_redaction_values": "text",
    "has_matching_exception_snapshot": "redaction",
    "is_sensitive_key": "text",
    "log_safe_exception": "log_safe",
    "redact_sensitive_data": "text",
    "redact_sensitive_mapping": "text",
    "redact_sensitive_text": "text",
    "safe_before_sleep_log": "log_safe",
    "safe_exception_type_name": "text",
    "sanitize_decision_signal_payload": "text",
    "sanitize_decision_signal_text": "text",
    "sanitize_diagnostic_text": "text",
    "sanitize_exception_chain": "text",
    "sanitize_sensitive_text": "text",
}

class _SanitizePackage(types.ModuleType):
    """Propagate attribute writes to the submodule that owns the name."""

    def __setattr__(self, name: str, value: object) -> None:
        super().__setattr__(name, value)
        owner_key = _NAME_OWNERS.get(name)
        if owner_key is None:
            return
        owner = _OWNER_MODULES.get(owner_key)
        if owner is not None:
            setattr(owner, name, value)

sys.modules[__name__].__class__ = _SanitizePackage

__all__ = [
    "exception_chain_redaction_values",
    "has_matching_exception_snapshot",
    "is_sensitive_key",
    "log_safe_exception",
    "redact_sensitive_data",
    "redact_sensitive_mapping",
    "redact_sensitive_text",
    "safe_before_sleep_log",
    "safe_exception_type_name",
    "sanitize_decision_signal_payload",
    "sanitize_decision_signal_text",
    "sanitize_diagnostic_text",
    "sanitize_exception_chain",
    "sanitize_sensitive_text",
]
