"""Attribute parity and composition guards for Config domain sub-configs."""

from dataclasses import fields

from src.config import Config
from src.config_parts.notification import NotificationConfig
from src.config_parts.share_image import ShareImageConfig


# Frozen at W6-07 phase-1 extraction: every pre-split Config field name that must
# still resolve on the flat facade (including names now owned by domain objects).
_LEGACY_FLAT_ATTRIBUTE_NAMES = (
    'stock_list',
    'feishu_app_id',
    'feishu_app_secret',
    'feishu_folder_token',
    'tushare_token',
    'tickflow_api_key',
    'tickflow_kline_adjust',
    'tickflow_priority',
    'tickflow_batch_daily_enabled',
    'tickflow_batch_size',
    'tencent_priority',
    'finnhub_api_key',
    'alphavantage_api_key',
    'longbridge_app_key',
    'longbridge_app_secret',
    'longbridge_access_token',
    'longbridge_oauth_client_id',
    'stock_index_remote_update_enabled',
    'alphasift_enabled',
    'alphasift_install_spec',
    'kronos_enabled',
    'kronos_model_size',
    'kronos_weights_dir',
    'multimodal_agent_tools_enabled',
    'multimodal_file_root',
    'decision_memory_enabled',
    'decision_memory_lookback',
    'decision_memory_min_age_days',
    'decision_memory_min_samples',
    'signal_scorecard_public_enabled',
    'signal_scorecard_min_samples',
    'paper_portfolio_initial_cash',
    'generation_backend',
    'generation_fallback_backend',
    'generation_backend_timeout_seconds',
    'generation_backend_max_output_bytes',
    'generation_backend_max_concurrency',
    'local_cli_backend_max_concurrency',
    'opencode_cli_model',
    'litellm_model',
    'litellm_fallback_models',
    'llm_temperature',
    'llm_prompt_cache_telemetry_enabled',
    'llm_prompt_cache_hints_enabled',
    'llm_prompt_cache_diagnostics_level',
    'litellm_config_path',
    'llm_config_mode',
    'llm_models_source',
    'llm_channels',
    'llm_channel_names',
    'llm_channel_config_issues',
    'llm_blocks_legacy_fallback',
    'llm_blocked_hermes_routes',
    'llm_model_list',
    'gemini_api_keys',
    'anthropic_api_keys',
    'openai_api_keys',
    'deepseek_api_keys',
    'gemini_api_key',
    'gemini_model',
    'gemini_model_fallback',
    'gemini_temperature',
    'gemini_request_delay',
    'gemini_max_retries',
    'gemini_retry_delay',
    'anthropic_api_key',
    'anthropic_model',
    'anthropic_temperature',
    'anthropic_max_tokens',
    'openai_api_key',
    'openai_base_url',
    'openai_model',
    'openai_vision_model',
    'openai_temperature',
    'vision_model',
    'vision_provider_priority',
    'anspire_api_keys',
    'bocha_api_keys',
    'minimax_api_keys',
    'tavily_api_keys',
    'brave_api_keys',
    'serpapi_keys',
    'searxng_base_urls',
    'searxng_public_instances_enabled',
    'social_sentiment_api_key',
    'social_sentiment_api_url',
    'news_max_age_days',
    'news_strategy_profile',
    'news_intel_retention_days',
    'news_intel_fetch_timeout_sec',
    'news_intel_max_items_per_source',
    'news_intel_auto_fetch_enabled',
    'newsnow_base_url',
    'bias_threshold',
    'agent_generation_backend',
    'agent_litellm_model',
    'agent_mode',
    '_agent_mode_explicit',
    'agent_max_steps',
    'agent_skills',
    'agent_skill_dir',
    'agent_nl_routing',
    'agent_arch',
    'agent_orchestrator_mode',
    'agent_orchestrator_timeout_s',
    'agent_critic_enabled',
    'agent_investment_committee_mode',
    'skill_opinion_recording_enabled',
    'agent_technical_agent_timeout_s',
    'agent_intel_agent_timeout_s',
    'agent_risk_agent_timeout_s',
    'agent_decision_agent_timeout_s',
    'agent_portfolio_agent_timeout_s',
    'agent_skill_agent_timeout_s',
    'agent_risk_override',
    'agent_deep_research_budget',
    'agent_deep_research_timeout',
    'agent_memory_enabled',
    'agent_skill_autoweight',
    'agent_skill_routing',
    'agent_context_compression_enabled',
    'agent_context_compression_profile',
    'agent_context_compression_trigger_tokens',
    'agent_context_protected_turns',
    'agent_event_monitor_enabled',
    'agent_event_monitor_interval_minutes',
    'agent_event_alert_rules_json',
    'wechat_webhook_url',
    'feishu_webhook_url',
    'feishu_webhook_secret',
    'feishu_webhook_keyword',
    'dingtalk_webhook_url',
    'dingtalk_secret',
    'feishu_chat_id',
    'feishu_receive_id_type',
    'feishu_domain',
    'telegram_bot_token',
    'telegram_chat_id',
    'telegram_message_thread_id',
    'email_sender',
    'email_sender_name',
    'email_password',
    'email_receivers',
    'stock_email_groups',
    'pushover_user_key',
    'pushover_api_token',
    'ntfy_url',
    'ntfy_token',
    'gotify_url',
    'gotify_token',
    'custom_webhook_urls',
    'custom_webhook_bearer_token',
    'custom_webhook_body_template',
    'webhook_verify_ssl',
    'discord_bot_token',
    'discord_main_channel_id',
    'discord_webhook_url',
    'discord_interactions_public_key',
    'slack_webhook_url',
    'slack_bot_token',
    'slack_channel_id',
    'astrbot_token',
    'astrbot_url',
    'notification_report_channels',
    'notification_alert_channels',
    'notification_system_error_channels',
    'notification_dedup_ttl_seconds',
    'notification_cooldown_seconds',
    'notification_quiet_hours',
    'notification_timezone',
    'notification_min_severity',
    'notification_daily_digest_enabled',
    'notification_delta_first',
    'single_stock_notify',
    'report_type',
    'report_language',
    'report_summary_only',
    'report_show_llm_model',
    'report_templates_dir',
    'report_mode',
    'report_renderer_enabled',
    'report_integrity_enabled',
    'report_integrity_retry',
    'report_history_compare_n',
    'pushplus_token',
    'pushplus_topic',
    'serverchan3_sendkey',
    'analysis_delay',
    'merge_email_notification',
    'feishu_max_bytes',
    'feishu_send_as_file',
    'wechat_max_bytes',
    'discord_max_words',
    'wechat_msg_type',
    'markdown_to_image_channels',
    'markdown_to_image_max_chars',
    'md2img_engine',
    'share_image_max_chars',
    'share_image_xiaohongshu_url',
    'share_image_xiaohongshu_handle',
    'share_image_xiaohongshu_id',
    'share_image_xiaohongshu_qr_path',
    'prefetch_realtime_quotes',
    'database_path',
    'sqlite_wal_enabled',
    'sqlite_busy_timeout_ms',
    'sqlite_write_retry_max',
    'sqlite_write_retry_base_delay',
    'save_context_snapshot',
    'backtest_enabled',
    'backtest_eval_window_days',
    'backtest_min_age_days',
    'backtest_engine_version',
    'backtest_neutral_band_pct',
    'log_dir',
    'log_level',
    'max_workers',
    'debug',
    'http_proxy',
    'https_proxy',
    'schedule_enabled',
    'schedule_time',
    'schedule_times',
    'schedule_run_immediately',
    'run_immediately',
    'market_review_enabled',
    'daily_market_context_enabled',
    'market_review_region',
    'market_review_color_scheme',
    'trading_day_check_enabled',
    'enable_realtime_quote',
    'enable_realtime_technical_indicators',
    'enable_chip_distribution',
    'enable_eastmoney_patch',
    'realtime_source_priority',
    'realtime_cache_ttl',
    'circuit_breaker_cooldown',
    'enable_fundamental_pipeline',
    'fundamental_stage_timeout_seconds',
    'fundamental_fetch_timeout_seconds',
    'fundamental_retry_max',
    'fundamental_cache_ttl_seconds',
    'fundamental_cache_max_entries',
    'portfolio_idempotency_replay_window_days',
    'portfolio_risk_concentration_alert_pct',
    'portfolio_risk_drawdown_alert_pct',
    'portfolio_risk_stop_loss_alert_pct',
    'portfolio_risk_stop_loss_near_ratio',
    'portfolio_risk_lookback_days',
    'portfolio_fx_update_enabled',
    'discord_bot_status',
    'akshare_sleep_min',
    'akshare_sleep_max',
    'tushare_rate_limit_per_minute',
    'max_retries',
    'retry_base_delay',
    'retry_max_delay',
    'webui_enabled',
    'webui_host',
    'webui_port',
    'bot_enabled',
    'bot_command_prefix',
    'bot_rate_limit_requests',
    'bot_rate_limit_window',
    'bot_admin_users',
    'feishu_verification_token',
    'feishu_encrypt_key',
    'feishu_stream_enabled',
    'dingtalk_app_key',
    'dingtalk_app_secret',
    'dingtalk_stream_enabled',
    'wecom_corpid',
    'wecom_token',
    'wecom_encoding_aes_key',
    'wecom_agent_id',
    'telegram_webhook_secret',
    'config_validate_mode',
)


def test_legacy_flat_attribute_names_still_resolve():
    config = Config()
    missing = [name for name in _LEGACY_FLAT_ATTRIBUTE_NAMES if not hasattr(config, name)]
    assert missing == [], f"flat facade missing attributes: {missing}"


def test_notification_and_share_image_are_composed_domain_objects():
    config = Config()
    assert isinstance(config.notification, NotificationConfig)
    assert isinstance(config.share_image, ShareImageConfig)


def test_flat_and_domain_access_share_storage():
    config = Config(
        email_sender_name="Alias",
        wechat_webhook_url="https://example.invalid/wechat",
        share_image_max_chars=42,
        share_image_xiaohongshu_handle="@demo",
    )
    assert config.notification.email_sender_name == "Alias"
    assert config.notification.wechat_webhook_url == "https://example.invalid/wechat"
    assert config.share_image.share_image_max_chars == 42
    assert config.share_image.share_image_xiaohongshu_handle == "@demo"

    config.notification.email_sender_name = "NestedWrite"
    config.share_image.share_image_max_chars = 7
    assert config.email_sender_name == "NestedWrite"
    assert config.share_image_max_chars == 7

    config.feishu_max_bytes = 1234
    config.share_image_xiaohongshu_id = "id-9"
    assert config.notification.feishu_max_bytes == 1234
    assert config.share_image.share_image_xiaohongshu_id == "id-9"


def test_domain_field_defaults_match_flat_facade_metadata():
    assert Config.__dataclass_fields__["email_sender_name"].default == "StockPulse"
    assert Config.__dataclass_fields__["share_image_max_chars"].default == 100000
    assert {f.name for f in fields(NotificationConfig)}.issubset(
        set(Config.__dataclass_fields__)
    )
    assert {f.name for f in fields(ShareImageConfig)}.issubset(
        set(Config.__dataclass_fields__)
    )


def test_composed_domain_kwargs_and_flat_kwargs_construct():
    nested = Config(
        notification=NotificationConfig(pushplus_token="tok"),
        share_image=ShareImageConfig(share_image_max_chars=9),
    )
    assert nested.pushplus_token == "tok"
    assert nested.share_image_max_chars == 9

    mixed = Config(
        notification=NotificationConfig(pushplus_token="keep"),
        pushplus_token="override",
        share_image_max_chars=11,
    )
    assert mixed.pushplus_token == "override"
    assert mixed.share_image_max_chars == 11
