# Copyright (c) 2026 SiinXu / StockPulse contributors
# SPDX-License-Identifier: AGPL-3.0-only
"""Public contracts for the StockPulse plugin core."""

from .agent_tools import (
    AgentToolRegistrationBackend,
    build_agent_tool_extension_contract,
    build_agent_tool_extension_registry,
    validate_agent_tool_definition,
)
from .analysis_strategies import (
    AnalysisStrategyCatalogSnapshot,
    AnalysisStrategyDefinition,
    AnalysisStrategyRegistry,
    RegisteredAnalysisStrategy,
    build_analysis_strategy_extension_contract,
    validate_analysis_strategy_definition,
)
from .constants import PLUGIN_APPLICATION_VERSION
from .data_provider_binding import (
    DATA_PROVIDER_BIND_ERROR_INTERFACE,
    DATA_PROVIDER_BIND_ERROR_PRIORITY,
    DATA_PROVIDER_BIND_ERROR_UNAVAILABLE,
    PLUGIN_DATA_PROVIDER_AUTO_BIND_ENV,
    build_data_provider_bound_contracts,
    build_data_provider_bound_registry,
    data_provider_auto_bind_enabled,
    extract_data_provider_contract,
    resolve_data_provider_registry,
    try_build_auto_bound_registry,
)
from .errors import PluginContextClosedError, PluginError, PluginRegistryError
from .health import PluginHealthEntry, PluginHealthReport, build_plugin_health_report
from .lifecycle_audit import (
    PLUGIN_LIFECYCLE_EVENT_TYPE,
    LifecycleAuditRecorder,
    PluginLifecycleAuditor,
)
from .surface import (
    PLUGIN_EXTENSION_SURFACE_VERSION,
    PLUGIN_EXTENSION_SURFACE_V1_AUTHOR_EXPORTS,
    PLUGIN_EXTENSION_SURFACE_V1_POINT_ORDER,
    PLUGIN_EXTENSION_SURFACE_V1_POINTS,
)
from .event_hooks import (
    EVENT_HOOK_NAMES,
    EVENT_HOOK_SCHEMA_VERSION,
    EventHook,
    EventHookRegistration,
    PluginEvent,
    dispatch_analysis_event,
    dispatch_market_review_event,
    event_hook_extension_contract,
    validate_event_hook_registration,
)
from .loader import ExternalPluginLoader, ExternalPluginResult
from .manager import (
    PluginLifecycleAuditCompletionUnavailable,
    PluginManager,
    PluginOperationResult,
    PluginReloadResult,
    PluginSnapshot,
    PluginSource,
    PluginState,
)
from .state_store import PluginLifecycleStateStore
from .manifest import PluginManifest
from .notification_channels import (
    NotificationAdapterResult,
    NotificationChannelAdapter,
    NotificationChannelFactory,
    NotificationChannelLifecycleSnapshot,
    NotificationChannelRegistry,
    NotificationChannelSnapshot,
    NotificationRequest,
    available_notification_channel_snapshot,
    build_notification_channel_extension_contract,
    validate_notification_channel_factory,
)
from .plugin import Plugin
from .report_templates import (
    ReportPlatform,
    ReportRenderRequest,
    ReportTemplate,
    SUPPORTED_REPORT_PLATFORMS,
    normalize_report_platform,
    validate_report_template,
)
from .registry import (
    EXTENSION_POINTS,
    ExtensionContract,
    ExtensionPoint,
    ExtensionRegistration,
    ExtensionRegistry,
    JSONValue,
    NativeRegistrationBackend,
    PluginContext,
    RegistrationHandle,
    default_extension_contracts,
)
from .runtime import build_application_extension_registry

__all__ = [
    "AgentToolRegistrationBackend",
    "AnalysisStrategyCatalogSnapshot",
    "AnalysisStrategyDefinition",
    "AnalysisStrategyRegistry",
    "DATA_PROVIDER_BIND_ERROR_INTERFACE",
    "DATA_PROVIDER_BIND_ERROR_PRIORITY",
    "DATA_PROVIDER_BIND_ERROR_UNAVAILABLE",
    "EXTENSION_POINTS",
    "EVENT_HOOK_NAMES",
    "EVENT_HOOK_SCHEMA_VERSION",
    "EventHook",
    "EventHookRegistration",
    "ExternalPluginLoader",
    "ExternalPluginResult",
    "ExtensionContract",
    "ExtensionPoint",
    "ExtensionRegistration",
    "ExtensionRegistry",
    "JSONValue",
    "LifecycleAuditRecorder",
    "NativeRegistrationBackend",
    "NotificationAdapterResult",
    "NotificationChannelAdapter",
    "NotificationChannelFactory",
    "NotificationChannelLifecycleSnapshot",
    "NotificationChannelRegistry",
    "NotificationChannelSnapshot",
    "NotificationRequest",
    "PLUGIN_DATA_PROVIDER_AUTO_BIND_ENV",
    "PLUGIN_LIFECYCLE_EVENT_TYPE",
    "Plugin",
    "PluginEvent",
    "PLUGIN_APPLICATION_VERSION",
    "PLUGIN_EXTENSION_SURFACE_VERSION",
    "PLUGIN_EXTENSION_SURFACE_V1_AUTHOR_EXPORTS",
    "PLUGIN_EXTENSION_SURFACE_V1_POINT_ORDER",
    "PLUGIN_EXTENSION_SURFACE_V1_POINTS",
    "PluginContext",
    "PluginContextClosedError",
    "PluginError",
    "PluginHealthEntry",
    "PluginHealthReport",
    "PluginLifecycleAuditor",
    "PluginLifecycleAuditCompletionUnavailable",
    "PluginManager",
    "PluginManifest",
    "PluginOperationResult",
    "PluginReloadResult",
    "PluginLifecycleStateStore",
    "PluginRegistryError",
    "PluginSnapshot",
    "PluginSource",
    "PluginState",
    "ReportPlatform",
    "ReportRenderRequest",
    "ReportTemplate",
    "RegistrationHandle",
    "SUPPORTED_REPORT_PLATFORMS",
    "RegisteredAnalysisStrategy",
    "available_notification_channel_snapshot",
    "build_agent_tool_extension_contract",
    "build_agent_tool_extension_registry",
    "build_analysis_strategy_extension_contract",
    "build_application_extension_registry",
    "build_data_provider_bound_contracts",
    "build_data_provider_bound_registry",
    "build_notification_channel_extension_contract",
    "build_plugin_health_report",
    "data_provider_auto_bind_enabled",
    "default_extension_contracts",
    "dispatch_analysis_event",
    "dispatch_market_review_event",
    "event_hook_extension_contract",
    "extract_data_provider_contract",
    "resolve_data_provider_registry",
    "normalize_report_platform",
    "try_build_auto_bound_registry",
    "validate_agent_tool_definition",
    "validate_analysis_strategy_definition",
    "validate_event_hook_registration",
    "validate_notification_channel_factory",
    "validate_report_template",
]
