# Copyright (c) 2026 SiinXu / StockPulse contributors
# SPDX-License-Identifier: AGPL-3.0-only
"""Shared plugin compatibility constants."""

from .surface import (
    PLUGIN_EXTENSION_SURFACE_VERSION,
    PLUGIN_EXTENSION_SURFACE_V1_AUTHOR_EXPORTS,
    PLUGIN_EXTENSION_SURFACE_V1_POINT_ORDER,
    PLUGIN_EXTENSION_SURFACE_V1_POINTS,
)

PLUGIN_APPLICATION_VERSION = "3.26.3"

__all__ = [
    "PLUGIN_APPLICATION_VERSION",
    "PLUGIN_EXTENSION_SURFACE_VERSION",
    "PLUGIN_EXTENSION_SURFACE_V1_AUTHOR_EXPORTS",
    "PLUGIN_EXTENSION_SURFACE_V1_POINT_ORDER",
    "PLUGIN_EXTENSION_SURFACE_V1_POINTS",
]
