import type { ReportLanguage } from '../types/analysis';
import type { UiLanguage } from '../i18n/uiText';

export const normalizeReportLanguage = (value?: string | null): ReportLanguage =>
  value === 'en' ? 'en' : value === 'ko' ? 'ko' : 'zh';

export const getReportLanguageForUi = (language: UiLanguage): ReportLanguage =>
  language === 'zh' || language === 'zh-TW' ? 'zh' : language === 'ko' ? 'ko' : 'en';

const REPORT_TEXT = {
  zh: {
    keyInsights: '核心洞察',
    noAnalysisSummary: '暂无分析结论',
    actionAdvice: '操作建议',
    noAdvice: '暂无建议',
    trendPrediction: '趋势预测',
    noPrediction: '暂无预测',
    marketSentiment: '市场情绪',
    strategyPoints: '策略点位',
    sniperLevels: '狙击点位',
    idealBuy: '理想买入',
    secondaryBuy: '二次买入',
    stopLoss: '止损价位',
    takeProfit: '止盈目标',
    noValue: '—',
    newsFeed: '资讯动态',
    relatedNews: '相关资讯',
    refresh: '刷新',
    retry: '重试',
    dismiss: '关闭',
    details: '查看详情',
    loadingNews: '加载资讯中...',
    noNews: '暂无相关资讯',
    noNewsDescription: '可稍后刷新以获取最新资讯。',
    openLink: '跳转',
    transparency: '透明度',
    traceability: '数据追溯',
    rawResult: '原始分析结果',
    analysisSnapshot: '分析快照',
    copy: '复制',
    copied: '已复制',
    recordId: '记录 ID',
    fullReport: '完整分析报告',
    loadingReport: '加载报告中...',
    loadReportFailed: '加载报告失败',
    copyMarkdownSource: '复制 Markdown 源码',
    copyPlainText: '复制纯文本',
    analysisModel: '分析模型',
    fearGreedIndex: '恐惧贪婪指数',
    boardLinkage: '板块联动',
    relatedBoards: '关联板块',
    leadingBoard: '领涨',
    laggingBoard: '领跌',
    neutralBoard: '中性',
    reanalyze: '重新分析',
    evidenceStrata: '证据分层',
    verifiedFacts: '已核实事实',
    missingOrConflicts: '缺失数据或来源冲突',
    modelInference: '模型推断',
    risksCounterEvidence: '风险与反证',
    frameworkAlignment: '与个人框架对齐',
    frameworkNotConfigured: '个人投资框架未配置',
    disclaimerHeading: '非投资建议声明',
    defaultDisclaimer: 'AI生成，仅供参考，不构成投资建议',
    factSource: '来源',
    factAsOf: '截至',
    sourceUnknown: '来源未标注',
    asOfUnknown: '时间未标注',
    gapMissing: '缺失',
    gapConflict: '冲突',
  },
  en: {
    keyInsights: 'KEY INSIGHTS',
    noAnalysisSummary: 'No analysis summary yet',
    actionAdvice: 'Action Advice',
    noAdvice: 'No advice yet',
    trendPrediction: 'Trend Outlook',
    noPrediction: 'No forecast yet',
    marketSentiment: 'Market Sentiment',
    strategyPoints: 'STRATEGY POINTS',
    sniperLevels: 'Action Levels',
    idealBuy: 'Ideal Entry',
    secondaryBuy: 'Secondary Entry',
    stopLoss: 'Stop Loss',
    takeProfit: 'Take Profit',
    noValue: '—',
    newsFeed: 'NEWS FEED',
    relatedNews: 'Related News',
    refresh: 'Refresh',
    retry: 'Retry',
    dismiss: 'Close',
    details: 'View details',
    loadingNews: 'Loading news...',
    noNews: 'No related news',
    noNewsDescription: 'Refresh later to check for the latest updates.',
    openLink: 'Open',
    transparency: 'TRANSPARENCY',
    traceability: 'Data Traceability',
    rawResult: 'Raw Analysis Result',
    analysisSnapshot: 'Analysis Snapshot',
    copy: 'Copy',
    copied: 'Copied!',
    recordId: 'Record ID',
    fullReport: 'Full Analysis Report',
    loadingReport: 'Loading report...',
    loadReportFailed: 'Failed to load report',
    copyMarkdownSource: 'Copy Markdown Source',
    copyPlainText: 'Copy Plain Text',
    analysisModel: 'Model',
    fearGreedIndex: 'Fear & Greed Index',
    boardLinkage: 'BOARD LINKAGE',
    relatedBoards: 'Related Boards',
    leadingBoard: 'Leading',
    laggingBoard: 'Lagging',
    neutralBoard: 'Neutral',
    reanalyze: 'Reanalyze',
    evidenceStrata: 'Evidence Strata',
    verifiedFacts: 'Verified Facts',
    missingOrConflicts: 'Missing Data or Source Conflicts',
    modelInference: 'Model Inference',
    risksCounterEvidence: 'Risks / Counter-Evidence',
    frameworkAlignment: 'Alignment with User Framework',
    frameworkNotConfigured: 'Personal investment framework not configured',
    disclaimerHeading: 'Non-Investment-Advice Disclaimer',
    defaultDisclaimer: 'AI-generated content for reference only. Not investment advice.',
    factSource: 'Source',
    factAsOf: 'As of',
    sourceUnknown: 'source not labeled',
    asOfUnknown: 'timestamp missing',
    gapMissing: 'Missing',
    gapConflict: 'Conflict',
  },
  ko: {
    keyInsights: '핵심 인사이트',
    noAnalysisSummary: '분석 결론 없음',
    actionAdvice: '대응 전략',
    noAdvice: '제안 없음',
    trendPrediction: '추세 전망',
    noPrediction: '예측 없음',
    marketSentiment: '시장 심리',
    strategyPoints: '전략 가격대',
    sniperLevels: '대응 가격대',
    idealBuy: '이상적 매수가',
    secondaryBuy: '추가 매수가',
    stopLoss: '손절가',
    takeProfit: '목표가',
    noValue: '—',
    newsFeed: '뉴스 피드',
    relatedNews: '관련 뉴스',
    refresh: '새로고침',
    retry: '다시 시도',
    dismiss: '닫기',
    details: '상세 보기',
    loadingNews: '뉴스 불러오는 중...',
    noNews: '관련 뉴스 없음',
    noNewsDescription: '잠시 후 새로고침하여 최신 소식을 확인하세요.',
    openLink: '열기',
    transparency: '투명성',
    traceability: '데이터 추적',
    rawResult: '원본 분석 결과',
    analysisSnapshot: '분석 스냅샷',
    copy: '복사',
    copied: '복사됨!',
    recordId: '레코드 ID',
    fullReport: '전체 분석 리포트',
    loadingReport: '리포트 불러오는 중...',
    loadReportFailed: '리포트 불러오기 실패',
    copyMarkdownSource: 'Markdown 소스 복사',
    copyPlainText: '일반 텍스트 복사',
    analysisModel: '분석 모델',
    fearGreedIndex: '공포·탐욕 지수',
    boardLinkage: '섹터 연동',
    relatedBoards: '관련 섹터',
    leadingBoard: '강세',
    laggingBoard: '약세',
    neutralBoard: '중립',
    reanalyze: '재분석',
    evidenceStrata: '증거 계층',
    verifiedFacts: '검증된 사실',
    missingOrConflicts: '누락 데이터 또는 출처 충돌',
    modelInference: '모델 추론',
    risksCounterEvidence: '리스크 / 반증',
    frameworkAlignment: '개인 프레임워크 정합',
    frameworkNotConfigured: '개인 투자 프레임워크가 구성되지 않음',
    disclaimerHeading: '투자 권유 아님 고지',
    defaultDisclaimer: 'AI 생성 참고용이며 투자 권유가 아닙니다.',
    factSource: '출처',
    factAsOf: '기준 시각',
    sourceUnknown: '출처 미표기',
    asOfUnknown: '시각 미표기',
    gapMissing: '누락',
    gapConflict: '충돌',
  },
} as const;

export const getReportText = (language?: string | null) => REPORT_TEXT[normalizeReportLanguage(language)];
