// Copyright (c) 2026 SiinXu / StockPulse contributors
// SPDX-License-Identifier: AGPL-3.0-only

import { createUiLanguageRecord } from '../i18n/createUiLanguageRecord';

export const PORTFOLIO_INSIGHTS_TEXT = createUiLanguageRecord(
  'locales.portfolioInsights.PORTFOLIO_INSIGHTS_TEXT',
  {
    zh: {
      tabLabel: '洞察', viewsLabel: '组合洞察视图', healthView: '健康分', basketView: '多标的', stressView: '压力测试', rebalanceView: '再平衡',
      basketTitle: '多标的组合分析', basketDescription: '把 1–20 个标的作为一个合成组合，统一分析相关性、集中度、共享风险、历史观点与可选压力情景。',
      basketSymbols: '标的与可选权重', basketSymbolsHint: '每行或用逗号分隔。可写 AAPL:2；未填权重的标的使用等权基线。', basketPlaceholder: 'AAPL:2\nMSFT:1\n600519', basketIncludeStress: '包含市场下跌 10% 压力覆盖', basketRun: '分析组合', basketRunning: '正在分析组合…', basketInputRequired: '请输入 1–20 个不重复的标的。', basketTooMany: '一次最多分析 20 个标的。', basketResult: '组合分析结果', basketSymbolsUsed: '纳入标的', basketDegraded: '降级标的', basketNoDegraded: '所有请求标的均已纳入。', basketCorrelations: '高相关性', basketNoCorrelations: '当前没有超过阈值的相关性组合。', basketSharedRisks: '共享风险暴露', basketNoSharedRisks: '当前没有额外共享风险暴露。', basketStance: '已有分析观点', basketScored: '已有评分', basketUnanalyzed: '未分析', basketAverage: '平均分', basketHealth: '合成组合健康', basketStress: '压力覆盖',
      stressTitle: '组合压力测试', stressDescription: '使用只读持仓快照运行确定性即时冲击；不是历史回放、蒙特卡洛或交易指令。', stressMode: '压力测试模式', stressPreset: '预设情景', stressCustom: '自定义冲击', stressScenario: '压力情景', stressCatalogLoading: '正在加载压力情景…', stressCatalogFailed: '无法加载压力情景目录', stressFactor: '冲击因子', stressFactorMarket: '市场', stressFactorSector: '行业', stressFactorFx: '汇率', stressFactorRate: '利率', stressShockPct: '冲击幅度（%）', stressShockBp: '冲击幅度（基点）', stressTargetSector: '目标行业', stressSectorMap: '标的行业映射', stressSectorMapHint: '每行 SYMBOL=SECTOR；行业预设必须提供映射。', stressRun: '运行压力测试', stressRunning: '正在运行压力测试…', stressResult: '压力测试结果', stressPnl: '估算盈亏', stressPnlPct: '估算盈亏率', stressPortfolioValue: '冲击前市值', stressStressedValue: '冲击后市值', stressPositions: '纳入持仓', stressTopLosers: '主要负面影响', stressTopWinners: '主要正面影响', stressNoImpacts: '当前没有对应方向的持仓影响。', stressHistoricalUnavailable: '仅提供确定性即时冲击；历史回放不可用。', stressSectorRequired: '行业情景需要目标行业和至少一条标的行业映射。',
      rebalanceTitle: '再平衡建议', rebalanceDescription: '基于当前持仓和风险指标生成只读、可解释的权重建议；不会执行交易。', rebalanceRiskTolerance: '风险偏好', rebalanceConservative: '保守', rebalanceModerate: '均衡', rebalanceAggressive: '进取', rebalanceDrift: '最小偏离阈值（百分点）', rebalanceLookback: '历史回看交易日', rebalanceRun: '生成建议', rebalanceRunning: '正在生成建议…', rebalanceResult: '再平衡结果', rebalanceRefused: '当前拒绝生成建议', rebalanceRefusedHint: '历史或风险输入不足时，系统不会编造交易建议。', rebalanceEmpty: '当前组合为空', rebalanceNoSuggestions: '当前没有超过阈值的再平衡建议。', rebalanceSuggestions: '调整建议', rebalanceBands: '持仓目标区间', rebalanceMaxSingle: '单一持仓上限', rebalanceEffectiveN: '有效持仓数', rebalanceVar: '风险价值（VaR）', rebalanceFromTo: '当前 {from}% → 目标 {to}%', rebalanceBandRange: '当前 {current}% · 区间 {low}%–{high}% · 中点 {mid}%', rebalanceNotional: '约 {value}', rebalanceSuggestionOnly: '仅供人工复核，不会自动执行。',
      status: '状态', statusOk: '正常', statusPartial: '部分可用', statusUnavailable: '不可用', statusEmpty: '空组合', runFailed: '请求失败', retry: '重试',
    },
    en: {
      tabLabel: 'Insights', viewsLabel: 'Portfolio insights views', healthView: 'Health', basketView: 'Basket', stressView: 'Stress test', rebalanceView: 'Rebalance',
      basketTitle: 'Multi-symbol portfolio analysis', basketDescription: 'Analyze 1–20 symbols as one synthetic basket across correlation, concentration, shared risk, existing stances, and an optional stress overlay.',
      basketSymbols: 'Symbols and optional weights', basketSymbolsHint: 'Separate with lines or commas. Use AAPL:2 for a weight; omitted weights receive an equal baseline.', basketPlaceholder: 'AAPL:2\nMSFT:1\n600519', basketIncludeStress: 'Include market-down-10% stress overlay', basketRun: 'Analyze basket', basketRunning: 'Analyzing basket…', basketInputRequired: 'Enter 1–20 unique symbols.', basketTooMany: 'A basket can contain at most 20 symbols.', basketResult: 'Basket analysis result', basketSymbolsUsed: 'Symbols used', basketDegraded: 'Degraded symbols', basketNoDegraded: 'All requested symbols were included.', basketCorrelations: 'High correlations', basketNoCorrelations: 'No symbol pair currently exceeds the correlation threshold.', basketSharedRisks: 'Shared risk exposures', basketNoSharedRisks: 'No additional shared risk exposure was identified.', basketStance: 'Existing analysis stances', basketScored: 'Scored', basketUnanalyzed: 'Unanalyzed', basketAverage: 'Average score', basketHealth: 'Synthetic basket health', basketStress: 'Stress overlay',
      stressTitle: 'Portfolio stress test', stressDescription: 'Run deterministic instantaneous shocks against a read-only holdings snapshot; this is not historical replay, Monte Carlo, or a trade instruction.', stressMode: 'Stress test mode', stressPreset: 'Preset scenario', stressCustom: 'Custom shock', stressScenario: 'Stress scenario', stressCatalogLoading: 'Loading stress scenarios…', stressCatalogFailed: 'Could not load the stress scenario catalog', stressFactor: 'Shock factor', stressFactorMarket: 'Market', stressFactorSector: 'Sector', stressFactorFx: 'FX', stressFactorRate: 'Rate', stressShockPct: 'Shock value (%)', stressShockBp: 'Shock value (basis points)', stressTargetSector: 'Target sector', stressSectorMap: 'Symbol-to-sector map', stressSectorMapHint: 'One SYMBOL=SECTOR per line; sector presets require this map.', stressRun: 'Run stress test', stressRunning: 'Running stress test…', stressResult: 'Stress test result', stressPnl: 'Estimated P&L', stressPnlPct: 'Estimated P&L (%)', stressPortfolioValue: 'Value before shock', stressStressedValue: 'Value after shock', stressPositions: 'Positions used', stressTopLosers: 'Largest negative impacts', stressTopWinners: 'Largest positive impacts', stressNoImpacts: 'No position impact in this direction.', stressHistoricalUnavailable: 'Only deterministic instantaneous shocks are available; historical replay is unavailable.', stressSectorRequired: 'A sector scenario requires a target sector and at least one symbol-to-sector mapping.',
      rebalanceTitle: 'Rebalancing recommendations', rebalanceDescription: 'Generate read-only, explainable weight guidance from current holdings and risk metrics; no trade is executed.', rebalanceRiskTolerance: 'Risk tolerance', rebalanceConservative: 'Conservative', rebalanceModerate: 'Moderate', rebalanceAggressive: 'Aggressive', rebalanceDrift: 'Minimum drift (percentage points)', rebalanceLookback: 'History lookback (trading days)', rebalanceRun: 'Generate recommendations', rebalanceRunning: 'Generating recommendations…', rebalanceResult: 'Rebalancing result', rebalanceRefused: 'Recommendations refused for current inputs', rebalanceRefusedHint: 'When history or risk inputs are insufficient, the system does not invent trades.', rebalanceEmpty: 'The portfolio is empty', rebalanceNoSuggestions: 'No rebalancing recommendation currently exceeds the threshold.', rebalanceSuggestions: 'Weight suggestions', rebalanceBands: 'Position target bands', rebalanceMaxSingle: 'Maximum single position', rebalanceEffectiveN: 'Effective positions', rebalanceVar: 'Value at risk (VaR)', rebalanceFromTo: 'Current {from}% → target {to}%', rebalanceBandRange: 'Current {current}% · range {low}%–{high}% · midpoint {mid}%', rebalanceNotional: 'About {value}', rebalanceSuggestionOnly: 'For human review only; nothing is auto-executed.',
      status: 'Status', statusOk: 'OK', statusPartial: 'Partial', statusUnavailable: 'Unavailable', statusEmpty: 'Empty portfolio', runFailed: 'Request failed', retry: 'Retry',
    },
  } as const,
);
