# -*- coding: utf-8 -*-
"""Compatibility facade for :mod:`src.market.analyzer`."""

from src.market._facade import load_legacy_module as _load_legacy_module
from src.market.analyzer import (
    Any,
    DataFetcherManager,
    Dict,
    GenerationError,
    GenerationErrorCode,
    IntelligenceService,
    List,
    MARKET_LIGHT_REGIONS,
    MarketAnalyzer,
    MarketIndex,
    MarketLightReviewResult,
    MarketLightSnapshot,
    MarketOverview,
    MarketProfile,
    Optional,
    SearchService,
    build_sector_analysis_payload,
    dataclass,
    datetime,
    exception_chain_redaction_values,
    field,
    get_config,
    get_market_strategy_blueprint,
    get_profile,
    getattr_static,
    has_matching_exception_snapshot,
    log_safe_exception,
    logger,
    logging,
    normalize_report_language,
    pd,
    re,
    record_llm_run,
    record_llm_run_started,
    render_sector_analysis_markdown,
    render_sector_analysis_prompt_context,
    resolve_generation_backend_id,
    resolve_generation_fallback_backend_id,
    sanitize_diagnostic_text,
    time,
)


__all__ = (
    "Any",
    "DataFetcherManager",
    "Dict",
    "GenerationError",
    "GenerationErrorCode",
    "IntelligenceService",
    "List",
    "MARKET_LIGHT_REGIONS",
    "MarketAnalyzer",
    "MarketIndex",
    "MarketLightReviewResult",
    "MarketLightSnapshot",
    "MarketOverview",
    "MarketProfile",
    "Optional",
    "SearchService",
    "build_sector_analysis_payload",
    "dataclass",
    "datetime",
    "exception_chain_redaction_values",
    "field",
    "get_config",
    "get_market_strategy_blueprint",
    "get_profile",
    "getattr_static",
    "has_matching_exception_snapshot",
    "log_safe_exception",
    "logger",
    "logging",
    "normalize_report_language",
    "pd",
    "re",
    "record_llm_run",
    "record_llm_run_started",
    "render_sector_analysis_markdown",
    "render_sector_analysis_prompt_context",
    "resolve_generation_backend_id",
    "resolve_generation_fallback_backend_id",
    "sanitize_diagnostic_text",
    "time",
)

_load_legacy_module("src.market.analyzer", globals(), __all__)
del _load_legacy_module
