# -*- coding: utf-8 -*-
"""Compatibility facade for :mod:`src.notification_parts.noise`."""

from src.notification_parts._facade import load_legacy_module as _load_legacy_module
from src.notification_parts.noise import (
    DEFAULT_NOTIFICATION_SEVERITY_BY_ROUTE,
    Dict,
    NOTIFICATION_SEVERITIES,
    NOTIFICATION_SEVERITY_RANK,
    NotificationNoiseDecision,
    Optional,
    P4_NOISE_ENV_KEYS,
    Tuple,
    ZoneInfo,
    ZoneInfoNotFoundError,
    annotations,
    dataclass,
    datetime,
    evaluate_notification_noise,
    hashlib,
    is_supported_notification_severity,
    is_time_in_quiet_hours,
    log_safe_exception,
    logger,
    logging,
    normalize_notification_severity,
    parse_notification_quiet_hours,
    re,
    record_notification_noise,
    release_notification_noise,
    reset_notification_noise_state,
    threading,
    uuid,
    validate_notification_timezone,
)


__all__ = (
    "DEFAULT_NOTIFICATION_SEVERITY_BY_ROUTE",
    "Dict",
    "NOTIFICATION_SEVERITIES",
    "NOTIFICATION_SEVERITY_RANK",
    "NotificationNoiseDecision",
    "Optional",
    "P4_NOISE_ENV_KEYS",
    "Tuple",
    "ZoneInfo",
    "ZoneInfoNotFoundError",
    "annotations",
    "dataclass",
    "datetime",
    "evaluate_notification_noise",
    "hashlib",
    "is_supported_notification_severity",
    "is_time_in_quiet_hours",
    "log_safe_exception",
    "logger",
    "logging",
    "normalize_notification_severity",
    "parse_notification_quiet_hours",
    "re",
    "record_notification_noise",
    "release_notification_noise",
    "reset_notification_noise_state",
    "threading",
    "uuid",
    "validate_notification_timezone",
)

_load_legacy_module("src.notification_parts.noise", globals(), __all__)
del _load_legacy_module
